package gr.cti.eslate.database;

import java.util.ListResourceBundle;

public class InfoBundle_el_GR extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"compo",                       "Ψηφίδα Επεξεργαστής Βάσεων Δεδομένων, έκδοση "},
        {"compo1",                      "Επεξεργαστής Βάσεων"},
        {"part",                        "Τμήμα του περιβάλλοντος Αβάκιο (http://E-Slate.cti.gr)"},
        //{"concept",         "Original concept: M. Koutlis"},
        //{"design",          "Σχεδιασμός: Γ. Τσιρώνης (contribution: Π. Σιούτη, Μ. Κουτλής)"},
        {"development",                 "Ανάπτυξη: Γ. Τσιρώνης"},
        //{"funding",         "Χρηματοδότηση: Έργο \"ΟΔΥΣΣΕΑΣ\" (ΥΠΕΠΘ - ΕΠΕΑΕΚ)"},
        {"contribution",                "Συμβολή: Π. Σιούτη, Χ. Κυνηγός"},
        {"Table",                       "Πίνακας"},
        {"DatabaseMenu",                "Βάση"},
        {"DatabaseMenuNew",             "Νέα βάση"},
        {"DatabaseMenuOpen",            "Άνοιγμα"},
        {"DatabaseMenuClose",           "Κλείσιμο"},
        {"DatabaseMenuRename",          "Αλλαγή τίτλου"},
        {"DatabaseMenuSave",            "Αποθήκευση"},
        {"DatabaseMenuSaveAs",          "Αποθήκευση ως"},
        {"DatabaseMenuImport",          "Εισαγωγή πίνακα"},
        {"DatabaseMenuExport",          "Εξαγωγή πίνακα"},
        {"DatabaseUserLevel",           "Επίπεδο Χρηστών"},
        {"Description",                 "Περιγραφή..."},
        {"DatabaseProperties",          "Ιδιότητες"},
        {"DatabaseMenuExit",            "Έξοδος"},
        {"TableMenu",                   "Πίνακας"},
        {"TableMenuNew",                "Νέος πίνακας"},
        {"TableMenuAuto",               "Αυτόματη δημιουργία"},
        {"TableMenuLoad",               "Προσθήκη"},
        {"TableMenuRemove",             "Αφαίρεση"},
        {"TableMenuSave",               "Αποθήκευση"},
        {"TableMenuSaveAs",             "Αποθήκευση ως"},
        {"TableMenuSaveUISettings",     "Αποθήκευση ρυθμίσεων εμφάνισης"},
        {"TableMenuRename",             "Αλλαγή ονόματος"},
        {"TableMenuHidden",             "Κρυφός"},
        {"TableMenuSort",               "Ταξινόμηση"},
        {"TableMenuFind",               "Εύρεση"},
        {"TableMenuFindNext",           "Εύρεση επομένου"},
        {"TableMenuFindPrevious",       "Εύρεση προηγούμενου"},
        {"TableMenuUnion",              "Ένωση"},
        {"TableMenuIntersect",          "Τομή"},
        {"TableMenuJoin",               "Σύνδεση"},
        {"TableMenuThJoin",             "Σύνδεση υπό συνθήκη"},
        {"TableMenuAutoResize",         "Αυτόματη ρύθμιση πλάτους πεδίων"},
        {"TableMenuAutoResizeOff",      "Μη ενεργή"},
        {"TableMenuAutoResizeLast",     "Τελευταίου πεδίου"},
        {"TableMenuAutoResizeAll",      "Όλων των πεδίων"},
        {"TableMenuProperties",         "Πληροφορίες..."},
        {"TableMenuPreferences",        "Προτιμήσεις..."},
        {"FieldMenu",                   "Πεδίο"},
        {"FieldMenuNew",                "Νέο πεδίο"},
        {"FieldMenuEdit",               "Ιδιότητες"},
        {"FieldMenuRemove",             "Διαγραφή"},
        {"FieldMenuEditable",           "Μεταβαλλόμενο"},
        {"FieldMenuHidden",             "Κρυφό"},
        {"FieldMenuRemovable",          "Διαγράψιμο"},
        {"FieldMenuKey",                "Κλειδί"},
        {"FieldMenuCalculated",         "Υπολογιζόμενο"},
        {"FieldMenuDataType",           "Τύπος πεδίου"},
        {"Number",                      "Αριθμός"},
        {"Integer",                     "Ακέραιος"},
        {"Float",                       "Float"},
        {"Alphanumeric",                "Αλφαριθμητικός"},
        {"Boolean (Yes/No)",            "Αληθές/Ψευδές"},
        {"Date",                        "Ημερομηνία"},
        {"Time",                        "Ώρα"},
        {"CDate",                       "Ημερομηνία"},
        {"CTime",                       "Ώρα"},
        {"URL",                         "URL"},
        {"Image",                       "Εικόνα"},
        {"Boolean",                     "Αληθές/Ψευδές"},
        {"true",                        "Αληθές"},
        {"false",                       "Ψευδές"},
        {"FieldMenuSortAsc",            "Αύξουσα ταξινόμηση"},
        {"FieldMenuSortDesc",           "Φθίνουσα ταξινόμηση"},
        {"FieldMenuSelectAll",          "Επιλογή όλων"},
        {"FieldMenuClearSel",           "Αποεπιλογή όλων"},
        {"FieldMenuWidth",              "Πλάτος"},
        {"FieldMenuFreeze",             "Παγίωση πλάτους"},
        {"RecordMenu",                  "Εγγραφή"},
        {"RecordMenuNew",               "Νέα εγγραφή"},
        {"RecordMenuRemoveSelected",    "Διαγραφή επιλεγμένων εγγραφών"},
        {"RecordMenuRemoveActive",      "Διαγραφή ενεργής εγγραφής"},
        {"RecordMenuSelectAll",         "Επιλογή όλων"},
        {"RecordMenuInvertSel",         "Αντιστροφή επιλογής"},
        {"RecordMenuClearSel",          "Αποεπιλογή όλων"},
        {"RecordMenuSelectedFirst",     "Προαγωγή επιλεγμένων"},
        {"Yes",                 "Ναί"},
        {"No",                  "Όχι"},
        {"OK",                  "Αποδοχή"},
        {"Cancel",              "Άκυρο"},
        {"Error",               "Λάθος"},
        {"Warning",             "Προειδοποίηση"},
        {"Close",               "Κλείσιμο"},
        {"WaitMessage",         "Παρακαλώ περιμένετε..."},
        {"Confirmation",        "Επιβεβαίωση"},
        {"Confirm removal",     "Επιβεβαίωση διαγραφής"},
        {"DatabaseMsg1",        "Δεν βρίσκεται το \"Windows\" Look&Feel"},
        {"DatabaseMsg2",        "Δεν αρχικοποιείται το \"Windows\" Look&Feel"},
        {"DatabaseMsg3",        "Εσωτερικό λάθος! Δεν είναι δυνατή η δημιουργία νέας βάσης"},
        {"DatabaseMsg4",        "Νέος τίτλος για τη βάση δεδομένων"},
        {"DatabaseMsg5",        "Τίτλος βάσης δεδομένων"},
        {"DatabaseMsg6",        "Διαχωριστής πεδίων στο αρχείο \""},
        {"DatabaseMsg7",        "Επιλέξτε διαχωριστή πεδίων"},
        {"DatabaseMsg8",        "Διαχωριστής πεδίων στο προς εξαγωγή αρχείο"},
        {"DatabaseMsg9",        "Επιλέξτε διαχωριστή πεδίων"},
        {"DatabaseMsg10",       "Τοποθέτηση των δεδομένων του πίνακα εντός εισαγωγικών;"},
        {"DatabaseMsg11",       "Xrhsh eisagvgikwn;"},
        {"DatabaseMsg12",       "Η τρέχουσα βάση δεδομένων έχει αλλάξει. Θέλετε να αποθηκευτεί πριν κλείσει;"},
        {"DatabaseMsg13",       "Νέο όνομα πίνακα"},
        {"DatabaseMsg14",       "Όνομα πίνακα"},
        {"DatabaseMsg15",       "Επιλέξτε πίνακα"},
        {"DatabaseMsg16",       "Λάθος πίνακας. Δεν είναι δυνατή η ένωση ενός πίνακα με το εαυτό του"},
        {"DatabaseMsg17",       "Λάθος πίνακας. Δεν είναι δυνατή η τομή ενός πίνακα με το εαυτό του"},
        {"DatabaseMsg18",       "Λάθος πίνακας. Δεν είναι δυνατή η σύνδεση ενός πίνακα με το εαυτό του"},
        {"DatabaseMsg19",       "Λάθος πίνακας. Δεν είναι δυνατή η υπό-συνθήκη σύνδεση ενός πίνακα με το εαυτό του"},
        {"DatabaseMsg20",       "Δεν υπάρχει επιλεγμένο πεδίο"},
        {"DatabaseMsg21",       "Θέλετε να γίνουν οι υπόλοιπες αλλαγές;"},
        {"DatabaseMsg22",       "Συνέχεια..."},
        {"DatabaseMsg23",       "Πεδία με τύπο \"Εικόνα\" δεν είναι δυνατό να είναι τμήμα του κλειδιού του πίνακα"},
        {"DatabaseMsg25",       "Το πεδίο \""},
        {"DatabaseMsg26",       "\" είναι υπολογιζόμενο, οπότε δεν είναι δυνατή η άμεση μεταβολή των δεδομένων του"},
        {"DatabaseMsg27",       "Δεν είναι δυνατή η αλλαγή του τύπου του υπολογιζόμενου πεδίου \""},
        {"DatabaseMsg28",       "\", διότι είναι τμήμα του κλειδιού του πίνακα"},
        {"DatabaseMsg29",       "Η αλλαγή του κλειδιού του πίνακα μπορεί να οδηγήσει σε απώλεια δεδομένων. Θέλετε να προχωρήσει;"},
        {"DatabaseMsg30",       "Η βάση δεδομένων είναι ήδη ανοικτή"},
        {"DatabaseMsg31",       "Δεν είναι δυνατό το άνοιγμα του αρχείου βάσης δεδομένων \""},
        {"DatabaseMsg32",       "Δεν είναι δυνατό το άνοιγμα του αρχείου πίνακα \""},
        {"DatabaseMsg33",       "\". Θέλετε να το εντοπίσετε οι ίδιοι;"},
        {"DatabaseMsg34",       "\". Πιθανότατα το αρχείο έχει υποστεί βλάβη"},
        {"DatabaseMsg35",       "Καμία ανοιχτή βάση"},
        {"DatabaseMsg36",       "Βάση δεδομένων"},
        {"DatabaseMsg37",       "Άτιτλος"},
        {"DatabaseMsg39",       "Άνοιγμα βάσης δεδομένων"},
        {"DatabaseMsg40",       "Αποθήκευση βάσης δεδομένων "},
        {"DatabaseMsg41",       "Αποθήκευση βάσης δεδομένων \""},
        {"DatabaseMsg42",       "\" ως"},
        {"DatabaseMsg43",       "Εισαγωγή πίνακα από το αρχείο κειμένου"},
        {"DatabaseMsg44",       "πίνακας1.txt"},
        {"DatabaseMsg45",       "Εξαγωγή πίνακα σε αρχείο κειμένου"},
        {"DatabaseMsg46",       "Εξαγωγή πίνακα \""},
        {"DatabaseMsg47",       "\" σε αρχείο κειμένου"},
        {"DatabaseMsg48",       "Αποθήκευση αλλαγών στη βάση δεδομένων"},
        {"DatabaseMsg49",       "Αποθήκευση αλλαγών στη βάση δεδομένων \""},
        {"DatabaseMsg50",       "Προσθήκη πίνακα στη βάση δεδομένων"},
        {"DatabaseMsg51",       "Αποθήκευση πίνακα ως"},
        {"DatabaseMsg52",       "Αποθήκευση πίνακα \""},
        {"DatabaseMsg53",       "\" ως"},
        {"DatabaseMsg54",       "Επιλέξτε τον πίνακα με τον οποίο ο ενεργός πίνακας θα ενωθεί"},
        {"DatabaseMsg55",       "Επιλέξτε τον πίνακα με τον οποίο ο πίνακας \""},
        {"DatabaseMsg56",       "\" θα ενωθεί"},
        {"DatabaseMsg57",       "Επιλέξτε το πίνακα με τον οποίο θα γίνει η τομή του ενεργού πίνακα"},
        {"DatabaseMsg58",       "\" θα τμηθεί"},
        {"DatabaseMsg59",       "Επιλέξτε τον πίνακα με τον οποίο ο ενεργός πίνακας θα συνδεθεί"},
        {"DatabaseMsg60",       "\" θα συνδεθεί"},
        {"DatabaseMsg61",       "Επιλέξτε τον πίνακα με τον οποίο ο ενεργός πίνακας θα συνδεθεί υπό συνθήκη"},
        {"DatabaseMsg62",       "\" θα συνδεθεί υπό συνθήκη"},
        {"DatabaseMsg63",       "Ιδιότητες πεδίων του πίνακα \""},
        {"DatabaseMsg64",       "Ιδιότητες πεδίων του ενεργού πίνακα"},
        {"DatabaseMsg65",       "Ιδιότητες πεδίων για ολόκληρη τη βάση δεδομένων"},
        {"DatabaseMsg66",       "Χρώματα για τον πίνακα \""},
        {"DatabaseMsg67",       "Χρώματα για τον ενεργό πίνακα"},
        {"DatabaseMsg68",       "Χρώματα για ολόκληρη τη βάση δεδομένων"},
        {"DatabaseMsg69",       "Επιπρόσθετες προτιμήσεις για τον πίνακα \""},
        {"DatabaseMsg70",       "Επιπρόσθετες προτιμήσεις για τον ενεργό πίνακα"},
        {"DatabaseMsg71",       "Επιπρόσθετες προτιμήσεις για ολόκληρη τη βάση"},
        {"DatabaseMsg72",       "Άνοιγμα πίνακα"},
        {"DatabaseMsg73",       "Κενή βάση δεδομένων"},
        {"DatabaseMsg74",       "Ο πίνακας που φορτώθηκε είναι κρυφός. Έτσι ενω υπάρχει στη βάση δεδομενων δεν είναι επιτρεπτή η εμφανισή του"},
        {"DatabaseMsg75",       "Επιβεβαίωση διαγραφής των επιλεγμένων πεδίων"},
        {"DatabaseMsg76",       "Επιβεβαίωση διαγραφής των επιλεγμένων εγγραφών"},
        {"DatabaseMsg77",       "Δεν είναι δυνατή η μεταφορά πίνακα σε ψηφίδα που περιέχει την ίδια βάση δεδομένων με την ψηφίδα από την οποία προέρχεται ο πίνακας"},
        {"DatabaseMsg78",       "Καμία επιλεγμένη εγγραφή"},
        {"DatabaseMsg79",       " επιλεγμένη εγγραφή"},
        {"DatabaseMsg80",       " επιλεγμένες εγγραφές"},
        {"DatabaseMsg81",       "από "},
        {"DatabaseMsg82",        "Εγγραφή"},
        {"DatabaseMsg83",       "Προηγούμενος πίνακας"},
        {"DatabaseMsg84",       "Επόμενος πίνακας"},
        {"DatabaseMsg85",       "Προηγούμενη εγγραφή"},
        {"DatabaseMsg86",       "Επόμενη εγγραφή"},
        {"DatabaseMsg87",       "Πρώτη εγγραφή"},
        {"DatabaseMsg88",       "Τελευταία εγγραφή"},
        {"DatabaseMsg89",       " δεν είναι αριθμός εγγραφής"},
        {"DatabaseMsg90",       "Άκυρος αριθμός εγγραφής"},
        {"DatabaseMsg91",       "Το "},
        {"DatabaseMsg92",       "Η βάση δεδομένων φορτώνεται..."},
        {"DatabaseMsg93",       "Άκυρος αριθμός εγγραφών"},
        {"DatabaseMsg94",       "Άκυρος αριθμός πεδίων"},
        {"DatabaseMsg95",       " δεν είναι αριθμός"},
        {"DatabaseMsg96",       "Επιβεβαίωση διαγραφής της ενεργής εγγραφής"},
        {"DatabaseMsg97",       "Νέα βάση"},
        {"DatabaseMsg98",       "Άνοιγμα βάσης"},
        {"DatabaseMsg99",       "Αποθήκευση βάσης"},
        {"DatabaseMsg100",      "Αποκοπή"},
        {"DatabaseMsg101",      "Αντιγραφή"},
        {"DatabaseMsg102",      "Επικόλληση"},
        {"DatabaseMsg103",      "Ταξινόμηση επιλεγμένων πεδίων κατά αύξουσα σειρά"},
        {"DatabaseMsg104",      "Ταξινόμηση επιλεγμένων πεδίων κατά φθίνουσα σειρά"},
        {"DatabaseMsg105",      "Εύρεση"},
        {"DatabaseMsg106",      "Εύρεση προηγούμενου"},
        {"DatabaseMsg107",      "Εύρεση επομένου"},
        {"DatabaseMsg108",      "Νέα εγγραφή"},
        {"DatabaseMsg109",      "Διαγραφή ενεργής εγγραφής"},
        {"DatabaseMsg110",      "Διαγραφή επιλεγμένων εγγραφών"},
        {"DatabaseMsg111",      "Νέο πεδίο"},
        {"DatabaseMsg112",      "Διαγραφή επιλεγμένων πεδίων"},
        {"DatabaseMsg113",      "Ιδιότητες πεδίου"},
        {"DatabaseMsg114",      "Επιλογή όλων των εγγραφών"},
        {"DatabaseMsg115",      "Αποεπιλογή όλων των εγγραφών"},
        {"DatabaseMsg116",      "Αντιστροφή επιλεγμένων εγγραφών"},
        {"DatabaseMsg117",      "Προαγωγή επιλεγμένων εγγραφών"},
        {"DatabaseMsg118",      "Μέγεθος γραμματοσειράς"},
        {"DatabaseMsg119",      "Γραμματοσειρά"},
        {"DatabaseMsg120",      "Έντονα"},
        {"DatabaseMsg121",      "Πλαγιαστά"},
        {"DatabaseMsg122",      "Χρώμα υποβάθρου"},
        {"DatabaseMsg123",      "Χρώμα δεδομένων"},
        {"DatabaseMsg124",      "Χρώμα πλέγματος πίνακα"},
        {"DatabaseMsg125",      "Χρώμα επιλεγμένων εγγραφών"},
        {"DatabaseMsg126",      "Χρώμα ενεργής εγγραφής"},
        {"DatabaseMsg127",      "Επιλογέας πλέγματος πίνακα"},
        {"DatabaseMsg128",      "Ταυτόχρονη επιλογή εγγραφών/πεδίων"},
        {"DatabaseMsg129",      "Επίδειξη μη μεταβαλλόμενων πεδίων"},
        {"DatabaseMsg130",      "Ανεξάρτητα τύπου δεδομένων"},
        {"Field",               "Πεδίο"},
        {"New jTable",           "Νέος πίνακας"},
        {"Standard",            "Βασική γραμμή εργαλείων"},
        {"Formatting",          "Γραμμή εργαλείων μορφής πινάκων"},
        {"Cut",                     "Αποκοπή"},
        {"Copy",                    "Αντιγραφή"},
        {"Paste",                   "Επικόλληση"},
        {"Icon Editor",             "Επεξεργαστής εικονιδίων"},
        {"Insert File Path",        "Εισαγωγή διαδρομής αρχείου"},
        {"Select File",        		"Επιλογή αρχείου"},
        {"FieldWidthDialogMsg1","Πλάτη επιλεγμένων πεδίων"},
        {"FieldWidthDialogMsg2","Ελάχιστο πλάτος"},
        {"FieldWidthDialogMsg3","Μέγιστο πλάτος"},
        {"FieldWidthDialogMsg4","Ελάχιστο και μέγιστο πλάτος πεδίου"},
        {"FieldWidthDialogMsg5","Άκυρη τιμή \""},
        {"FieldWidthDialogMsg6","\" για το ελάχιστο πλάτος πεδίου"},
        {"FieldWidthDialogMsg7","Το ελάχιστο πλάτος πεδίου δεν μπορεί να είναι μικρότερο από 30"},
        {"FieldWidthDialogMsg8","\" για το μέγιστο πλάτος πεδίου"},
        {"FieldWidthDialogMsg9","Το μέγιστο πλάτος πεδίου δεν μπορεί να είναι μεγαλύτερο από 2000"},
        {"FieldWidthDialogMsg10","Το ελάχιστο πλάτος πεδίου δεν μπορεί να είναι μεγαλύτερο από το μέγιστο πλάτος"},
        {"NewFieldDialogMsg1",  "Νέο πεδίο"},
        {"EditFieldDialogMsg",  "Επεξεργασία πεδίου"},
        {"NewFieldDialogMsg2",  "Όνομα πεδίου"},
        {"NewFieldDialogMsg3",  "Κλειδί"},
        {"NewFieldDialogMsg4",  "Μεταβαλλόμενο"},
        {"NewFieldDialogMsg5",  "Διαγράψιμο"},
        {"NewFieldDialogMsg6",  "Υπολογιζόμενο"},
        {"NewFieldDialogMsg7",  "Ανήκει το πεδίο στο κλειδί του πίνακα;"},
        {"NewFieldDialogMsg8",  "Είναι το πεδίο μεταβαλλόμενο;"},
        {"NewFieldDialogMsg9",  "Είναι το πεδίο διαγράψιμο;"},
        {"NewFieldDialogMsg10", "Είναι το πεδίο υπολογιζόμενο;"},
        {"NewFieldDialogMsg11", "Τύπος πεδίου"},
        {"NewFieldDialogMsg12", "Φόρμουλα"},
        {"NewFieldDialogMsg13", "Φόλμουλα υπολογιζόμενου πεδίου"},
        {"NewFieldDialogMsg14", "Ιδιότητες πεδίου"},
        {"NewFieldDialogMsg15", "Καθαρισμός"},
        {"NewFieldDialogMsg16", "Αποθήκευση αναφορών σε εικόνες"},
        {"NewTableDialogMsg1",  "Νέος πίνακας"},
        {"NewTableDialogMsg2",  "Όνομα πίνακα"},
        {"NewTableDialogMsg3",  "Τύπος"},
        {"NewTableDialogMsg4",  "Διαγραφή πεδίου"},
        {"NewTableDialogMsg5",  "Καθαρισμός πεδίου"},
        {"NewTableDialogMsg6",  "Δημιουργία πίνακα"},
        {"NewTableDialogMsg7",  "Όνομα του νέου πεδίου"},
        {"NewTableDialogMsg8",  "Ένα άλλο πεδίο με το όνομα \""},
        {"NewTableDialogMsg9",            "\" έχει ήδη οριστεί. Το πεδίο αυτό δεν θα εισαχθεί στον νέο πίνακα"},
        {"NewTableDialogMsg10",           "Είναι το νέο πεδίο υπολογιζόμενο;"},
        {"NewTableDialogMsg11",           "Επιλέξτε τον τύπο του πεδίου"},
        {"NewTableDialogMsg12",           "Ανήκει το νέο πεδίο στο κλειδί του πίνακα;"},
        {"NewTableDialogMsg13",           "Είναι το νέο πεδίο μεταβαλλόμενο"},
        {"NewTableDialogMsg14",           "Είναι το νέο πεδίο διαγράψιμο;"},
        {"NewTableDialogMsg15",           "Συμπληρώστε την φόρμουλα του υπολογιζόμενου πεδίου"},
        {"PreferencesDialogMsg1",         "Προτιμήσεις πινάκων"},
        {"PreferencesDialogMsg2",         "Μορφή ημερομηνίας  "},
        {"PreferencesDialogMsg3",         "Μορφή ώρας  "},
        {"PreferencesDialogMsg4",         "Μορφή Ημερομηνίας/Ώρας"},
        {"PreferencesDialogMsg5",         "Εμφάνιση μόνο του ακέραιου μέρους"},
        {"PreferencesDialogMsg6",         "Χρήση εκθετικής μορφής"},
        {"PreferencesDialogMsg7",         "Συνεχής εμφάνιση της υποδιαστολής"},
        {"PreferencesDialogMsg8",         "Χαρακτήρας υποδιαστολής   "},
        {"PreferencesDialogMsg9",         "Εμφάνιση διαχωριστή χιλιάδων"},
        {"PreferencesDialogMsg10",        "Διαχωριστής χιλιάδων   "},
        {"PreferencesDialogMsg11",        "Μορφοποίηση αριθμών"},
        {"PreferencesDialogMsg12",        "Ενημέρωση του ενεργού πίνακα μόνο "},
        {"PreferencesDialogMsg13",        "Προτιμήσεις μορφοποίησης δεδομένων για ολόκληρη τη βάση"},
        {"PreferencesDialogMsg14",        "Προτιμήσεις μορφοποίησης δεδομένων για τον πίνακα \""},
        {"PreferencesDialogMsg15",        "Μορφοποίηση δεδομένων"},
        {"PreferencesDialogMsg16",        "Yπόβαθρο πίνακα"},
        {"PreferencesDialogMsg17",        "Πλέγμα"},
        {"PreferencesDialogMsg18",        "Υπόβαθρο επιλογής"},
        {"PreferencesDialogMsg19",        "Επίδειξη"},
        {"PreferencesDialogMsg20",        " Γενικά "},
        {"PreferencesDialogMsg21",        "Ακέραιοι"},
        {"PreferencesDialogMsg22",        "Αριθμοί"},
        {"PreferencesDialogMsg23",        "Αληθές/Ψευδές"},
        {"PreferencesDialogMsg24",        "Ημερομηνίες"},
        {"PreferencesDialogMsg25",        "Ώρες"},
        {"PreferencesDialogMsg26",        "URL"},
        {"PreferencesDialogMsg27",        " Χρώματα τύπων δεδομένων πεδίων "},
        {"PreferencesDialogMsg28",        "Επιλέξτε χρώμα"},
        {"PreferencesDialogMsg29",        "Επιλογέας χρωμάτων"},
        {"PreferencesDialogMsg30",        "Προτιμήσεις χρωμάτων για ολόκληρη τη βάση"},
        {"PreferencesDialogMsg31",        "Προτιμήσεις χρωμάτων για τον πίνακα \""},
        {"PreferencesDialogMsg32",        "Χρώμα"},
        {"PreferencesDialogMsg33",        "Τύπος"},
        {"PreferencesDialogMsg34",        "Μέγεθος"},
        {"PreferencesDialogMsg35",        "ΑαΒβΓγΔδΕεΖζΗηΘθΙιΚκΛλΜμΝνΞξΟοΠπΡρΣσΤτΥυΦφΧχΨψΩω"},
        {"PreferencesDialogMsg36",        " Γραμματοσειρά "},
        {"PreferencesDialogMsg37",        "Ύψος εγγραφής"},
        {"PreferencesDialogMsg38",        "Το ύψος εγγραφής πρέπει να είναι μεταξύ \"7\" και \"299\""},
        {"PreferencesDialogMsg39",        "Εμφάνιση οριζόντιων γραμμών πλέγματος"},
        {"PreferencesDialogMsg40",        "Εμφάνιση κάθετων γραμμών πλέγματος"},
        {"PreferencesDialogMsg41",        "Ταυτόχρονη επιλογή πεδίων και εγγραφών"},
        {"PreferencesDialogMsg42",        "Εμφάνιση εικονιδίων τύπου δεδομένων στην επικεφαλίδα των πεδίων"},
        {"PreferencesDialogMsg43",        "Επίδειξη μη μεταβαλλόμενων πεδίων"},
        {"PreferencesDialogMsg44",        " Γενικές ρυθμίσεις "},
        {"PreferencesDialogMsg45",        "Επιπρόσθετες προτιμήσεις για ολόκληρη τη βάση"},
        {"PreferencesDialogMsg46",        "Επιπρόσθετες προτιμήσεις για τον πίνακα \""},
        {"PreferencesDialogMsg47",        "Επιπρόσθετες προτιμήσεις"},
        {"PreferencesDialogMsg48",        "Χρώμα υποβάθρου του πίνακα"},
        {"PreferencesDialogMsg49",        "Χρώμα πλέγματος του πίνακα"},
        {"PreferencesDialogMsg50",        "Χρώμα επιλεγμένων εγγραφών του πίνακα"},
        {"PreferencesDialogMsg51",        "Χρώμα μη μεταβαλλόμενων πεδίων του πίνακα"},
        {"PreferencesDialogMsg52",        "Χρώμα ακεραίων τιμών"},
        {"PreferencesDialogMsg53",        "Χρώμα αριθμητικών τιμών"},
        {"PreferencesDialogMsg54",        "Χρώμα τιμών τύπου 'Αληθές/Ψευδές'"},
        {"PreferencesDialogMsg55",        "Χρώμα τιμών τύπου 'Ημερομηνία'"},
        {"PreferencesDialogMsg56",        "Χρώμα τιμών τύπου 'Ώρα'"},
        {"PreferencesDialogMsg57",        "Χρώμα URL τιμών"},
        {"PreferencesDialogMsg58",        "Χρώμα αλφαριθμητικών τιμών"},
        {"PreferencesDialogMsg59",        "Αλφαριθμητικά"},
        {"PreferencesDialogMsg60",        "Floats"},
        {"PreferencesDialogMsg61",        "Χρώμα τιμών τύπου float"},
        {"PreferencesDialogMsg62",        "Προσκήνιο επιλογής"},
        {"PreferencesDialogMsg63",        "Χρώμα προσκηνίου επιλεγμένων εγραφών πίνακα"},
        {"PreferencesDialogMsg64",        "Eνεργή εγγραφή"},
        {"PreferencesDialogMsg65",        "Χρώμα ενεργής εγγραφής πίνακα"},
        {"TableInfoDialogMsg1",           "Πληροφορίες για τον πίνακα \""},
        {"TableInfoDialogMsg2",           "Αριθμός εγγραφών:"},
        {"TableInfoDialogMsg3",           "Αριθμός πεδίων:"},
        {"TableInfoDialogMsg4",           "Αριθμός επιλεγμένων εγγραφών:"},
        {"TableInfoDialogMsg5",           "Αριθμός επιλεγμένων πεδίων:"},
        {"TableInfoDialogMsg6",           "Πεδία κλειδιά:"},
        {"TableInfoDialogMsg7",           "Κανένα"},
        {"TableInfoDialogMsg8",           "Υπολογιζόμενα πεδία:"},
        {"TableSortDialogMsg1",           "Ταξινόμηση πίνακα"},
        {"TableSortDialogMsg2",           "Επιλογή των πεδίων ως προς τα οποία ο πίνακας \""},
        {"TableSortDialogMsg3",           "\" θα ταξινομηθεί"},
        {"TableSortDialogMsg4",           " πίνακα \""},
        {"TableSortDialogMsg5",           "Πεδία του"},
        {"TableSortDialogMsg6",           "Ταξινόμηση ως προς τα πεδία"},
        {"TableSortDialogMsg7",           "Κατεύθυνση"},
        {"ThJoinDialogMsg1",              "Σύνδεση υπό συνθήκη: "},
        {"ThJoinDialogMsg2",              "Νέα συνθήκη"},
        {"ThJoinDialogMsg3",              "Διαγραφή συνθήκης"},
        {"ColorPanelMsg1",                "Ενεργός πίνακας μόνο"},
        {"Number of records",             "Αριθμός εγγραφών"}, //TableAutoCreateDialog
        {"Number of fields",              "Αριθμός πεδίων"},
        {"Administrator Password",        "Κωδικός διαχειριστή"},
        {"Database password",             "Κωδικός βάσης δεδομένων"},
        {"DatabaseMsg131",                "Εισαγωγή κωδικού"},
        {"DatabaseMsg132",                "Λάθος κωδικός διαχειριστή βάσης δεδομένων. Δοκιμάστε ξανά."},
        {"DatabaseMsg133",                "Ορισμός επιπέδου χρηστών"},
        {"DatabaseMsg134",                "Λάθος κωδικός βάσης. Η βάση δεδομένων παραμένει κλειδωμένη"},
        {"DatabaseMsg135",                "Η βάση δεδομένων κλείδωσε"},
        {"DatabaseMsg136",                "Άκυρος κωδικός. Η βάση δεδομένων δεν κλειδώθηκε"},
        {"Novice",                        "Αρχάριοι"},
        {"Advanced",                      "Προχωρημένοι"},
        {"User mode",                     "Επίπεδο χρηστών"},
        {"DatabasePropertiesDialogMsg1",  "Ιδιότητες βάσης δεδομένων"},
        {"DatabasePropertiesDialogMsg2",  "Όνομα"},
        {"DatabasePropertiesDialogMsg3",  "Επώνυμο"},
        {"DatabasePropertiesDialogMsg4",  "Δημιουργία"},
        {"DatabasePropertiesDialogMsg5",  ""},
        {"DatabasePropertiesDialogMsg6",  "Τελευταία τροποποίηση"},
        {"DatabasePropertiesDialogMsg7",  ""},
        {"DatabasePropertiesDialogMsg8",  "Δημιουργός βάσης δεδομένων"},
        {"DatabasePropertiesDialogMsg9",  "Επιτρεπτή η αφαίρεση πινάκων"},
        {"DatabasePropertiesDialogMsg10", "Επιτρεπτή η προσθήκη πινάκων"},
        {"DatabasePropertiesDialogMsg11", "Επιτρεπτή η εξαγωγή πινάκων"},
        {"DatabasePropertiesDialogMsg12", "Εμφάνιση \"κρυφών\" πινάκων"},
        {"DatabasePropertiesDialogMsg13", "Κλείδωμα"},
        {"DatabasePropertiesDialogMsg14", "Ξεκλείδωμα"},
        {"DatabasePropertiesDialogMsg15", "Ιδιότητες πινάκων"},
        {"DatabasePropertiesDialogMsg16", "Εισαγωγή κωδικού βάσης"},
        {"DatabasePropertiesDialogMsg17", "Επιτρεπτή η προσθήκη εγγραφών"},
        {"DatabasePropertiesDialogMsg18", "Επιτρεπτή η διαγραφή εγγραφών"},
        {"DatabasePropertiesDialogMsg19", "Επιτρεπτή η προσθήκη πεδίων"},
        {"DatabasePropertiesDialogMsg20", "Επιτρεπτή η διαγραφή πεδίων"},
        {"DatabasePropertiesDialogMsg21", "Επιτρεπτή η αναδιοργάνωση των πεδίων"},
        {"DatabasePropertiesDialogMsg22", "Επιτρεπτή η μεταβολή των δεδομένων"},
        {"DatabasePropertiesDialogMsg23", "Επιτρεπτή η αλλαγή κλειδιού του πίνακα"},
        {"DatabasePropertiesDialogMsg24", "Ιδιότητες βάσης δεδομένων"},
        {"DatabasePropertiesDialogMsg25", "Ιδιότητες πίνακα"},
        {"DatabasePropertiesDialogMsg26", "Επιτρεπτή η μεταβολή της ιδιότητας \"Μεταβαλλόμενο\""},
        {"DatabasePropertiesDialogMsg27", "Επιτρεπτή η μεταβολή της ιδιότητας \"Διαγράψιμο\""},
        {"DatabasePropertiesDialogMsg28", "Επιτρεπτή η μεταβολή της ιδιότητας \"Κλειδί\""},
        {"DatabasePropertiesDialogMsg29", "Επιτρεπτή η μεταβολή τύπου δεδομένων"},
        {"DatabasePropertiesDialogMsg30", "Επιτρεπτή η μεταβολή του πεδίου σε μη υπολογιζόμενο"},
        {"DatabasePropertiesDialogMsg31", "Ιδιότητες πεδίου"},
        {"DatabasePropertiesDialogMsg32", "Επιτρεπτή η μεταβολή της ιδιότητας \"Κρυφός\""},
        {"DatabasePropertiesDialogMsg33", "Εμφάνιση κρυφών πεδίων"},
        {"DatabasePropertiesDialogMsg34", "Επιτρεπτή η μεταβολή της ιδιότητας \"Κρυφό\""},
        {"DatabasePropertiesDialogMsg35", "Επιτρεπτή η μεταβολή της φόρμουλας του υπολογιζόμενου πεδίου"},
        {"DatabasePropertiesDialogMsg36", "Επιτρεπτή η μεταβολή των ιδιοτήτων των πεδίων"},
        {"DatabasePropertiesDialogMsg37", "Επιτρεπτή η μεταβολή του τίτλου του πίνακα"},
        {"MetadataDialogMsg1",            "Περιγραφή βάσης δεδομένων "},
        {"MetadataDialogMsg2",            "Περιγραφή πίνακα "},
        {"IconEditActionMsg1",            "Το εικονίδιο δεν αποθηκεύτηκε σε αρχείο. Δεδομένου ότι το συγκεκριμένο πεδίο αποθηκεύει μόνο αναφορές σε αρχεία εικόνων, το εικονίδιο δεν θα αποθηκευτεί"},
        {"ResultTable",                   "Απάντηση ερώτησης στον πίνακα \""},
        {"SaveDB",                        "Θέλετε να αποθηκεύσετε τη βάση δεδομένων;"},
        {"warnClose",                     "Προσοχή! Η ψηφίδα επεξεργαστής βάσεων κλείνει..."},
        {"DatabaseEntry",                 "Εισαγωγή Βάσης Δεδομένων"},
        {"ConstructorTimer",              "Κατασκευή επεξεργαστή βάσεων"},
        {"LoadTimer",                     "Ανάκτηση επεξεργαστή βάσεων"},
        {"SaveTimer",                     "Αποθήκευση επεξεργαστή βάσεων"},
        {"InitESlateAspectTimer",         "Κατασκευή αβακιακής πλευράς επεξεργαστή βάσεων"},
        {"FontType",                      "Γραμματοσειρά"},
        {"FontSize",                      "Μέγεθος γραμματοσειράς"},
        {"Bold",                          "Έντονα"},
        {"Italic",                        "Πλάγια"},
        {"BackColor",                     "Χρώμα υποβάθρου"},
        {"ForeColor",                     "Χρώμα κειμένου"},
        {"GridColor",                     "Χρώμα πλέγματος"},
        {"SelectionColor",                "Χρώμα επιλογής"},
        {"ActiveRecColor",                "Χρώμα ενεργής εγγραφής"},
        {"GridChooser",                   "Τύπος πλέγματος"},
        {"RowColumnSelection",            "Πολιτική επιλογής εγγραφών/πεδίων"},
        {"HightLightNonEditableFields",   "Τονισμός μη-μεταβαλλόμενων πεδίων"},

        {"Previous Table",		"Προηγούμενος πίνακας"},
        {"Next Table",			"Επόμενος πίνακας"},
        {"Record Number",		"Αριθμός εγγραφής"},
        {"Number of Records",	"Πλήθος εγγραφών"},
        {"First Record",		"Πρώτη εγγραφή"},
        {"Previous Record",		"Προηγούμενη εγγραφή"},
        {"Next Record",			"Επόμενη εγγραφή"},
        {"Last Record",			"Τελευταία εγγραφή"},
        {"Message",				"Ετικέτα"},
        {"Record",				"Ετικέτα2"},
    };
}
