package gr.cti.eslate.mapViewer;

import java.util.ListResourceBundle;

/**
 * MapBeanInfo Bundle.
 * <P>
 *
 * @author	Giorgos Vasiliou
 * @version	3.0.0, 05-Apr-2000
 */
public class MapViewerBeanInfoBundle_el_GR extends ListResourceBundle {
	public Object [][] getContents() {
		return contents;
	}

	static final Object[][] contents={
		{"statusBarPosition",       "Μπάρα κατάστασης"},
		{"statusBarPositionTip",    "Θέση της μπάρας κατάστασης"},
		{"statusBarVisible",        "Μπάρα κατάστασης ορατή"},
		{"statusBarVisibleTip",     "Προβολή ή απόκρυψη της μπάρας κατάστασης"},
		{"statusBarOpaque",         "Μπάρα κατάστασης αδιαφανής"},
		{"statusBarOpaqueTip",      "Η μπάρα κατάστασης μπορεί να είναι διαφανής ή αδιαφανής ανεξάρτητα από την ψηφίδα"},
		{"toolBarPosition",         "Εργαλειοθήκη"},
		{"toolBarPositionTip",      "Θέση της εργαλειοθήκης"},
		{"toolBarVisible",          "Εργαλειοθήκη ορατή"},
		{"toolBarVisibleTip",       "Προβολή ή απόκρυψη της εργαλειοθήκης"},
		{"opaque",                  "Ψηφίδα αδιαφανής"},
		{"opaqueTip",               "Το υπόβαθρο της ψηφίδας μπορεί να είναι διαφανές ή αδιαφανές"},
		{"background",              "Χρώμα υποβάθρου"},
		{"backgroundTip",           "Το χρώμα του υποβάθρου όταν δεν είναι διαφανές και δεν υπάρχει εικόνα"},
		{"image",                   "Εικόνα υποβάθρου"},
		{"imageTip",                "Μια εικόνα που εμφανίζεται στο υπόβαθρο της ψηφίδας"},
		{"imageViewPropertyTip",    "Επιλέξτε πως θα εμφανίζεται η εικόνα όταν το μέγεθός της είναι διαφορετικό από της ψηφίδας"},
		{"errorTolerance",          "Περιθώριο σφάλματος ζωγραφικής"},
		{"errorToleranceTip",       "0=μέγιστη ποιότητα, ελάχιστη ταχύτητα. >0=ελαττώνεται η ποιότητα, αυξάνει η ταχύτητα."},
		{"tools",                   "Εργαλεία"},
		{"toolVisibleTip",          "Ελέγχει αν το εργαλείο θα εμφανίζεται στην εργαλειοθήκη"},
		{"toolActivateVisible",     "Εργαλείο ενεργοποίησης ορατό"},
		{"toolSelectVisible",       "Εργαλείο επιλογής ορατό"},
		{"toolPanVisible",          "Εργαλείο κύλισης ορατό"},
		{"toolEditVisible",         "Εργαλείο μορφοποίησης ορατό"},
		{"toolZoomVisible",         "Εργαλείο μεγέθυνσης/σμίκρυνσης ορατό"},
		{"toolGridVisible",         "Εργαλείο πλέγματος ορατό"},
		{"toolGoInVisible",         "Εργαλείο εμβάθυνσης ορατό"},
		{"toolGoOutVisible",        "Εργαλείο επιστροφής ορατό"},
		{"toolRotateVisible",       "Εργαλείο περιστροφής ορατό"},
		{"circleSelectToolVisible", "Εργαλείο κυκλικής επιλογής ορατό"},
		{"browseToolVisible",       "Εργαλείο επισκόπισης ορατό"},
		{"toolMiniatureVisible",    "Εργαλείο προβολής σμικρυμένου χάρτη ορατό"},
		{"toolMeterVisible",        "Εργαλείο μέτρου ορατό"},
		{"toolIdentifyVisible",     "Εργαλείο αναγνώρισης ορατό"},
		{"toolLayerVisibilityVisible","Εργαλείο προβολής επιπέδων ορατό"},
		{"toolSpotVisible",         "Εργαλείο εντοπισμού ορατό"},
		{"toolNavigateVisible",     "Εργαλείο καθοδήγησης οντότητας ορατό"},
		{"toolLegendVisible",       "Εργαλείο υπομνήματος ορατό"},
		{"meterPopupEnabled",       "Μέτρηση αποστάσεων σε παράθυρο"},
		{"meterPopupEnabledTip",    "Παράθυρο που δείχνει την απόσταση κατά τη χρήση του εργαλείου μέτρο"},
		{"selectionPopupEnabled",   "Παράθυρο εμβαδού/ακτίνας στα εργαλεία επιλογής"},
		{"selectionPopupEnabledTip","Παράθυρο που δειχνει το εμβαδό ή την ακτίνα της περιοχής επιλογής"},
		{"selectionShapeTypeChanged","Αλλαγή τύπου σχήματος επιλογής"},
		{"selectionShapeGeometryChanged","Αλλαγή γεωμετρίας σχήματος επιλογής"},
		{"up",                      "ΕΠΑΝΩ"},
		{"down",                    "ΚΑΤΩ"},
		{"left",                    "ΑΡΙΣΤΕΡΑ"},
		{"right",                   "ΔΕΞΙΑ"},
		{"normal",                  "ΚΑΝΟΝΙΚΗ"},
		{"stretched",               "ΕΚΤΕΤΑΜΕΝΗ"},
		{"tiled",                   "ΣΕ ΠΑΡΑΘΕΣΗ"},
		{"always",                  "ΠΑΝΤΑ"},
		{"never",                   "ΠΟΤΕ"},
		{"onmouse",                 "ΟΤΑΝ ΔΕΙΧΝΕΙ ΤΟ ΠΟΝΤΙΚΙ"},
		{"antialiasing",            "Antialiasing"},
		{"antialiasingTip",         "Αν είναι αληθές, η προβολή γίνεται χρησιμοποιώντας την τεχνική antialiasing."},
		{"qualityOverSpeed",        "Υψηλή ποιότητα γραφικών"},
		{"qualityOverSpeedTip",     "Η υψηλή ποιότητα είναι αντιστρόφως ανάλογη της ταχύτητας. Μην την χρησιμοποιείτε για να αυξήσετε την ταχύτητα εκτέλεσης."},
		{"showCoordinates",         "Προβολή συντεταγμένων"},
		{"showCoordinatesTip",      "Προβάλει τις συντεταγμένες του σημείου που κινείται το ποντίκι στην περιοχή του χάρτη"},
		{"gridVisible",             "Πλέγμα: προβολή"},
		{"gridVisibleTip",          "Προβάλει πλέγμα πάνω στο χάρτη"},
		{"gridColor",               "Πλέγμα: χρώμα"},
		{"gridColorTip",            "Το χρώμα του πλέγματος όταν είναι ορατό"},
		{"gridStep",                "Πλέγμα: βήμα"},
		{"gridStepTip",             "Το βήμα μεταξύ των γραμμών του πλέγματος σε μονάδες του χάρτη"},
		{"border",                  "Περίγραμμα"},
		{"borderTip",               "Ελέγχει το περίγραμμα της ψηφίδας"},
		{"mapBackground",           "Χρώμα υποβάθρου χάρτη"},
		{"mapBackgroundTip",        "Το χρώμα του χάρτη όταν δεν υπάρχει εικόνα υποβάθρου"},
		{"font",                    "Γραμματοσειρά"},
		{"fontTip",                 "Η γραμματοσειρά εφαρμόζεται στις ετικέτες, σύντομες βοήθειες κτλ"},
		{"busyIconVisible",         "Ενδείκτης αναμονής ορατός"},
		{"busyIconVisibleTip",      "Ορίζει αν ο ενδείκτης αναμονής θα είναι ορατός"},
		{"showInactiveZoomRects",   "Προβολή ανενεργών παρ/μων μετάβασης"},
		{"showInactiveZoomRectsTip","Αν αποεπιλεγεί, τα παρ/μα μετάβασης φαίνονται μόνο όταν το ποντίκι είναι πάνω τους"},

		{"showAgentPositioningInfoDialog","Προβολή διαλόγου τοποθέτησης οντότητας"},
		{"showAgentPositioningInfoDialogTip","Όταν επιλεγεί, κατά τη σύνδεση μίας μη τοποθετημένης οντότητας εμφανίζεται ένας διάλογος με οδηγίες"},
		{"paintCrossOnAgent",       "Σταυρός στις οντότητες"},
		{"paintCrossOnAgentTip",    "Ζωγραφίζει ένα σταυρό που δείχνει τη θέση τους κάτω από τις οντότητες, με το χρώμα μονοπατιού."},
		{"mousePressedOnMapArea",   "Πλήκτρο ποντικού πατήθηκε στο χάρτη"},
		{"mouseReleasedOnMapArea",  "Πλήκτρο ποντικού απελευθερώθηκε στο χάρτη"},
		{"mouseClickedOnMapArea",   "Κλικ ποντικού στο χάρτη"},
		{"mouseEnteredOnMapArea",   "Το ποντίκι εισήλθε στο χάρτη"},
		{"mouseExitedOnMapArea",    "Το ποντίκι έφυγε από το χάρτη"},
		{"mouseDraggedOnMapArea",   "Το ποντίκι σύρθηκε (drag) στο χάρτη"},
		{"mouseMovedOnMapArea",     "Το ποντίκι κουνήθηκε στο χάρτη"},
		{"mapViewerScaleChanged",   "Αλλαγή κλίμακας στον προβολέα"},
		{"mapViewerBusyStatusChanged","Αλλαγή κατάστασης busy"},
	};
}
