/*
 * Created by IntelliJ IDEA.
 * User: tsironis
 * Date: 29 ��� 2002
 * Time: 8:11:21 ��
 * To change template for new class use 
 * Code Style | Class Templates options (Tools | IDE Options).
 */
package gr.cti.eslate.database;

import java.util.ListResourceBundle;

public class DBTableBundle_el_GR extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"ComponentName",               "Επεξεργαστής πινάκων"},
        {"ConstructorTimer",            "Κατασκευή Επεξεργαστή πινάκων"},
        {"LoadTimer",                   "Ανάκτηση Επεξεργαστή πινάκων"},
        {"SaveTimer",                   "Αποθήκευση Επεξεργαστή πινάκων"},
        {"InitESlateAspectTimer",       "Κατασκευή αβακιακής πλευράς Επεξεργαστή πινάκων"},
        {"ImportTable",                 "Εισαγωγή πίνακα"},
        {"Yes",                         "Ναί"},
        {"No",                          "Όχι"},
        {"OK",                          "Αποδοχή"},
        {"Cancel",                      "Άκυρο"},
        {"Error",                       "Λάθος"},
        {"Warning",                     "Προειδοποίηση"},
        {"WaitMessage",                 "Παρακαλώ περιμένετε..."},
        {"Confirmation",                "Επιβεβαίωση"},
        {"Confirm removal",             "Επιβεβαίωση διαγραφής"},
        {"Number",                      "Αριθμός"},
        {"Alphanumeric",                "Αλφαριθμητικός"},
        {"Boolean (Yes/No)",            "Αληθές/Ψευδές"},
        {"Date",                        "Ημερομηνία"},
        {"Time",                        "Ώρα"},
        {"CDate",                       "Ημερομηνία"},
        {"CTime",                       "Ώρα"},
        {"URL",                         "URL"},
        {"Image",                       "Εικόνα"},
        {"Boolean",                     "Αληθές/Ψευδές"},

        {"Cut",                         "Αποκοπή"},
        {"Copy",                        "Αντιγραφή"},
        {"Paste",                       "Επικόλληση"},
        {"Icon Editor",                 "Διαχειριστής εικονιδίων..."},
        {"Find Action",                 "Εύρεση..."},
        {"FindNext Action",             "Εύρεση επόμενου"},
        {"FindPrevious Action",         "Εύρεση προηγούμενου"},
        {"Multi-column sort Action",    "Ταξινόμηση..."},

        {"SelectAllRecs Action",        "Επιλογή όλων των εγγραφών"},
        {"Select All Fields Action",                "Επιλογή όλων των πεδίων"},
        {"Table Remove Record Action",              "Διαγραφή ενεργής εγγραφής..."},
        {"Table Remove Selected Records Action",    "Διαγραφή επιλεγμένων εγγραφών..."},
        {"HomeAction",                              "Κορυφή πίνακα"},
        {"EndAction",                               "Τέλος πίνακα"},
        {"Promote Action",                          "Προαγωγή επιλεγμένων εγγραφών"},

        {"DBTableMsg1",                 "Η αλλαγή τύπου του πεδίου \""},
        {"DBTableMsg2",                 "\" Θα οδηγήσει σε απώλεια δεδομένων. Θέλετε να προχωρήσει;"},
        {"DBTableMsg3",                 "Δεν είναι δυνατή η ταξινόμηση πινάκων ως προς πεδία τύπου \"Εικόνας\""},
        {"DBTableMsg4",                 "Η νέα εγγραφή δεν μπορεί να εισαχθεί στον πίνακα μέχρι να συμπληρωθούν οι τιμές των πεδίων κλειδιά"},
        {"DBTableMsg5",                 "Εμφάνιση εικονιδίων τύπου πεδίων"},
        {"DBTableMsg6",                 "Απόκρυψη εικονιδίων τύπου πεδίων"},
        {"DBTableMsg7",                 "Άνοιγμα εικόνας"},
        {"DBTableMsg8",                 "Επιβεβαίωση διαγραφής της ενεργής εγγραφής"},
        {"DBTableMsg9",                 "Η αλλαγή του κλειδιού του πίνακα μπορεί να οδηγήσει σε απώλεια δεδομένων. Θέλετε να προχωρήσει;"},
        {"DatabaseMsg21",               "Θέλετε να γίνουν οι υπόλοιπες αλλαγές;"},
        {"DatabaseMsg22",               "Συνέχεια..."},
        {"DatabaseMsg23",               "Πεδία με τύπο \"Εικόνα\" δεν είναι δυνατό να είναι τμήμα του κλειδιού του πίνακα"},
        {"DatabaseMsg27",               "Δεν είναι δυνατή η αλλαγή του τύπου του υπολογιζόμενου πεδίου \""},
        {"DatabaseMsg28",               "\", διότι είναι τμήμα του κλειδιού του πίνακα"},
        {"DatabaseMsg75",               "Επιβεβαίωση διαγραφής των επιλεγμένων πεδίων"},
        {"DatabaseMsg76",               "Επιβεβαίωση διαγραφής των επιλεγμένων εγγραφών"},
        {"DatabaseMsg90",               "Άκυρος αριθμός εγγραφής"},
        {"GridChooser1",                "Ορατές και οι κάθετες και οι οριζόντιες γραμμές"},
        {"GridChooser2",                "Μόνο οι οριζόντιες γραμμές ορατές"},
        {"GridChooser3",                "Μόνο οι κάθετες γραμμές ορατές"},
        {"GridChooser4",                "Αόρατο πλέγμα"},
        {"NewFieldDialogMsg1",          "Νέο πεδίο"},
        {"IconEditActionMsg1",          "Το εικονίδιο δεν αποθηκεύτηκε σε αρχείο. Δεδομένου ότι το συγκεκριμένο πεδίο αποθηκεύει μόνο αναφορές σε αρχεία εικόνων, το εικονίδιο δεν θα αποθηκευτεί"},
        {"AddRecordActionName",         "Προσθήκη εγγραφής"},
        {"Not Found",                   " δεν βρέθηκε"},
        {"StartSearchFromTop1",         "Δεν υπάρχουν άλλες εμφανίσεις του "},
        {"StartSearchFromTop2",         ". Πατήστε F3 για εύρεση από την κορυφή του πίνακα"},
        {"StartSearchFromBottom1",      "Δεν υπάρχουν άλλες εμφανίσεις του "},
        {"StartSearchFromBottom2",      ". Πατήστε Shift+F3 για εύρεση από το τέλος του πίνακα"},
        {"Find What",                   "Εύρεση"}, //Find dialog
        {"Up",                          "Προηγούμενο"},
        {"Down",                        "Επόμενο"},
        {"Direction",                   "Κατεύθυνση"},
        {"Search Parameters",           "Παράμετροι εύρεσης"},
        {"Match Case",                  "Ταίριασμα πεζών/κεφαλαίων"},
        {"Search Selected Columns",     "Έρευνα επιλεγμένων πεδίων"},
        {"Search Selected Rows",        "Έρευνα επιλεγμένων εγγραφών"},
        {"Find First",                  "Εύρεση πρώτου"},
        {"Find Next",                   "Εύρεση επομένου"},
        {"Close",                       "Κλείσιμο"},
        {"Find in Table",               "Εύρεση στον πίνακα"},
        {"SortField",                   "Ταξινόμηση"},
        {"SortFieldAsc",                "Αύξουσα ταξινόμηση"},
        {"SortFieldDesc",               "Φθίνουσα ταξινόμηση"},
        {"EditFieldDialogMsg",          "Επεξεργασία πεδίου"},
        {"FieldProperties",             "Ιδιότητες..."},
        {"CurrencyField",               "Πεδίο νομίσματος"},
        {"AddField",                    "Πρόσθεση πεδίου..."},
        {"FieldRemove",                 "Διαγραφή επιλεγμένων πεδίων"},
        {"TableMenuProperties",         "Πληροφορίες..."},
        {"TableMenuPreferences",        "Προτιμήσεις..."},
        {"Description",                 "Περιγραφή..."},
        {"GridChooser",                 "Επιλογή πλέγματος"},
        {"ExportTable",                 "Εξαγωγή σε αρχείο κειμένου..."},

        {"Border",                                  "Περίγραμμα"},
        {"BorderTip",                               "Ρύθμιση του περιγράμματος της Βάσης Δεδομένων"},
        {"TableHeaderExpansionChangeAllowed",       "Επικεφαλίδα πεδίων επεκτάσιμη"},
        {"TableHeaderExpansionChangeAllowedTip",    "Ρυθμίζει την επεκτασιμότητα των επικεφαλίδων των στηλών του πίνακα"},
        {"SortFromColumnHeadersEnabled",            "Ταξινόμηση από επικεφαλίδα πεδίων"},
        {"SortFromColumnHeadersEnabledTip",         "Ρυθμίζει τη δυνατότητα ταξινόμησης των πεδίων από την επικεφαλίδα τους"},
        {"TablePopupEnabled",                       "Μενού λειτουργιών πίνακα ενεργό"},
        {"TablePopupEnabledTip",                    "Ενεργοποιεί το αναδυόμενο μενού που εμφανίζεται με δεξί κλικ μέσα σε πίνακα"},
        {"ColumnPopupEnabled",                      "Μενού λειτουργιών πεδίου ενεργό"},
        {"ColumnPopupEnabledTip",                   "Ενεργοποιεί το αναδυόμενο μενού που εμφανίζεται με δεξί κλικ σε επικεφαλίδα πεδίου"},
        {"HeaderFont",                              "Γραμματοσειρά επικεφαλίδας πεδίων"},
        {"HeaderFontTip",                           "Γραμματοσειρά επικεφαλίδας πεδίων"},
        {"CalculatedFieldHeaderFont",               "Γραμματοσειρά επικεφαλίδας υπολογιζόμενων πεδίων"},
        {"CalculatedFieldHeaderFontTip",            "Γραμματοσειρά επικεφαλίδας υπολογιζόμενων πεδίων"},
        {"CalculatedFieldHeaderForeground",         "Χρώμα προσκηνίου επικεφαλίδας υπολογιζόμενων πεδίων"},
        {"CalculatedFieldHeaderForegroundtTip",     "Το χρώμα προσκηνίου της επικεφαλίδας των υπολογιζόμενων πεδίων"},
        {"HeaderForeground",                        "Χρώμα προσκηνίου επικεφαλίδας πεδίων"},
        {"HeaderForegroundTip",                     "Το χρώμα προσκηνίου της επικεφαλίδας των πεδίων"},
        {"HeaderBackground",                        "Χρώμα υποβάθρου επικεφαλίδας πεδίων"},
        {"HeaderBackgroundTip",                     "Το χρώμα υποβάθρου τηε επικεφαλίδας των πεδίων"},
        {"VerticalRowBarBrightColor",               "Ανοικτό χρώμα κάθετης μπάρας εγγραφών"},
        {"VerticalRowBarBrightColorTip",            "Το ανοικτό χρώμα που χρησιμοποεί η κάθετη μπάρα εγγραφών"},
        {"VerticalRowBarColor",                     "Βασικό χρώμα κάθετης μπάρας εγγραφών"},
        {"VerticalRowBarColorTip",                  "Το βασικό χρώμα που χρησιμοποεί η κάθετη μπάρα εγγραφών"},
        {"VerticalRowBarDarkColor",                 "Σκούρο χρώμα κάθετης μπάρας εγγραφών"},
        {"VerticalRowBarDarkColorTip",              "Το σκούρο χρώμα που χρησιμοποεί η κάθετη μπάρα εγγραφών"},
        {"TwoColorBackgroundEnabled",               "Υπόβαθρο με δύο χρώματα"},
        {"TwoColorBackgroundEnabledTip",            "Χρήση δύο διαφορετικών χρωμάτων υποβάθρου για διαδοχικές εγγραφές"},
        {"OddRowColor",                             "Χρώμα εγγραφών μονής σειράς"},
        {"OddRowColorTip",                          "Το χρώμα υποβάθρου των εγγραφών με μονή σειρά"},
        {"EvenRowColor",                            "Χρώμα εγγραφών ζυγής σειράς"},
        {"EvenRowColorTip",                         "Το χρώμα υποβάθρου των εγγραφών με ζυγή σειρά"},
        {"RecordSelectionChangeAllowed",            "Επιτρέπτη η αλλαγή επιλογής εγγραφών"},
        {"RecordSelectionChangeAllowedTip",         "Καθορίζει το αν επιτρέπεται η αλλαγή της επιλογής των εγγραφών από το UI"},
        {"ActiveRecordDrawMode",                    "Ένδειξη ενεργής εγγραφής"},
        {"ActiveRecordDrawModeTip",                 "Καθορίζει τον τρόπο με τον οποία παρουσιάζεται η ενεργή εγγραφή στον πίνακα"},
        {"SelectedRecordDrawMode",                  "Ένδειξη επιλεγμένων εγγραφών"},
        {"SelectedRecordDrawModeTip",               "Καθορίζει τον τρόπο παρουσίασης των επιλεγμένων εγγραφών του πίνακα"},
        {"NoIndication",                            "Καμία ένδειξη"},
        {"OnRowBarOnly",                            "Στην μπάρα εγγραφών μόνο"},
        {"OnTableOnly",                             "Στον πίνακα μόνο"},
        {"OnRowBarAndTable",                        "Στην μπάρα και στον πίνακα"},
        {"propertyChange",                          "Αλλαγή ιδιότητας"},
        {"mouseEntered",                            "Είσοδος ποντικού"},
        {"mouseExited",                             "Έξοδος ποντικού"},
        {"mouseMoved",                              "Μετακίνηση ποντικού"},
        {"vetoableChange",                          "Ακυρώσιμη αλλαγή ιδιότητας"},
        {"componentHidden",                         "Απόκρυψη ψηφίδας"},
        {"componentShown",                          "Εμφάνιση ψηφίδας"},
        {"dataImportAllowed",                       "Προσπάθεια εισαγωγής δεδομένων"},
        {"dataImported",                            "Εισαγωγή δεδομένων"},
        {"dataExported",                            "Εξαγωγή δεδομένων"},
        {"transferableCreated",                     "Κατασκευή Transferable"},
        {"DBTable Popup Name",                      "Αναδυόμενο μενού πίνακα"},
        {"Column Popup Name",                       "Αναδυόμενο μενού στηλών"},
        {"ResetColumnPopup",                        "Θέλετε να επαναρχικοποιηθούν τα περιεχόμενα του αναδυόμενου μενού στηλών;"},
        {"ResetColumnPopupTitle",                   "Επαναρχικοποίηση αναδυόμενου μενού"},
    };
}
