package gr.cti.eslate.database;

import java.util.ListResourceBundle;

public class InfoBundle extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"compo",                   "Database editor, version "},
        {"compo1",                  "Database Editor"},
        {"part",                    "Part of the E-Slate environment (http://E-Slate.cti.gr)"},
        //{"design",              "Design: G. Tsironis (contribution: P. Siouti, M. Koutlis)"},
        {"development",             "Development: G. Tsironis"},
        //{"funding",             "Funding: Project \"ODYSSEAS\" ((EU Support Framework II, Greek Ministry of National Education and Religious Affairs"},
        {"contribution",            "Contribution: P. Siouti, Ch. Kynigos"},
        {"copyright",       		"Copyright Ερευνητικό Ακαδημαϊκό Ινστιτούτο Τεχνολογίας Υπολογιστών-ΕΑ.ΙΤΥ 1993-2008.\nΑνάπτυξη τρέχουσας έκδοσης από τις Conceptum AE και ΕΧΟDUS AE.\nΤο Αβάκιο 2.0 υπόκειται σε διπλή άδεια (dual license), ήτοι ισχύουν οι όροι της GNU-GPL License και της L-GPL license.\n\nΕπιτρέπεται η παραγωγή, διανομή και εμπορική εκμετάλλευση κλειστού ή ανοιχτού κώδικα παράγωγων προϊόντων\nβασισμένων στην πλατφόρμα Αβάκιο 2.0 και κάθε επόμενης έκδοσής της καθώς επίσης και να συμπεριλαμβάνεται\nκαι να διανέμεται μαζί με τα προϊόντα αυτά η πλατφόρμα σε μορφή πηγαίου ή/και εκτελέσιμου κώδικα."},
        {"Table",                   "Table"},
        {"DatabaseMenu",            "Database"},
        {"DatabaseMenuNew",         "New"},
        {"DatabaseMenuOpen",        "Open"},
        {"DatabaseMenuClose",       "Close"},
        {"DatabaseMenuRename",      "Rename"},
        {"DatabaseMenuSave",        "Save"},
        {"DatabaseMenuSaveAs",      "Save As"},
        {"DatabaseMenuImport",      "Import Table"},
        {"DatabaseMenuExport",      "Export Table"},
        {"DatabaseUserLevel",       "User Level"},
        {"Description",             "Description..."},
        {"DatabaseProperties",      "Properties"},
        {"DatabaseMenuExit",        "Exit"},
        {"TableMenu",               "Table"},
        {"TableMenuNew",            "New"},
        {"TableMenuAuto",           "Auto-create"},
        {"TableMenuLoad",           "Load"},
        {"TableMenuRemove",         "Remove"},
        {"TableMenuSave",           "Save"},
        {"TableMenuSaveAs",         "Save As"},
        {"TableMenuSaveUISettings", "Save UI settings"},
        {"TableMenuRename",         "Rename"},
        {"TableMenuHidden",         "Hidden"},
        {"TableMenuSort",           "Sort"},
        {"TableMenuFind",           "Find"},
        {"TableMenuFindNext",       "Find Next"},
        {"TableMenuFindPrevious",   "Find Previous"},
        {"TableMenuUnion",          "Union"},
        {"TableMenuIntersect",      "Intersect"},
        {"TableMenuJoin",           "Join"},
        {"TableMenuThJoin",         "Th-Join"},
        {"TableMenuAutoResize",     "Autoresize Fields"},
        {"TableMenuAutoResizeOff",  "Off"},
        {"TableMenuAutoResizeLast", "Last Field"},
        {"TableMenuAutoResizeAll",  "All Fields"},
        {"TableMenuProperties",     "Information..."},
        {"TableMenuPreferences",    "Preferences..."},
        {"FieldMenu",               "Field"},
        {"FieldMenuNew",            "New"},
        {"FieldMenuEdit",           "Edit"},
        {"FieldMenuRemove",         "Remove"},
        {"FieldMenuEditable",       "Editable"},
        {"FieldMenuHidden",         "Hidden"},
        {"FieldMenuRemovable",      "Removable"},
        {"FieldMenuKey",            "Key"},
        {"FieldMenuCalculated",     "Calculated"},
        {"FieldMenuDataType",       "Data Type"},
        {"Integer",                 "Integer"},
        {"Float",                   "Float"},
        {"Number",                  "Number"},
        {"Alphanumeric",            "Alphanumeric"},
        {"Boolean (Yes/No)",        "Boolean (Yes/No)"},
        {"Date",                    "Date"},
        {"Time",                    "Time"},
        {"CDate",                   "Date"},
        {"CTime",                   "Time"},
        {"URL",                     "URL"},
        {"Image",                   "Image"},
        {"Boolean",                 "Boolean"},
        {"true",                    "True"},
        {"false",                   "False"},
        {"FieldMenuSortAsc",        "Sort Ascending"},
        {"FieldMenuSortDesc",       "Sort Descending"},
        {"FieldMenuSelectAll",      "Select All"},
        {"FieldMenuClearSel",       "Clear Selection"},
        {"FieldMenuWidth",          "Width"},
        {"FieldMenuFreeze",         "Freeze"},
        {"RecordMenu",              "Record"},
        {"RecordMenuNew",           "New"},
        {"RecordMenuRemoveSelected","Remove selected records"},
        {"RecordMenuRemoveActive",  "Remove active record"},
        {"RecordMenuSelectAll",     "Select All"},
        {"RecordMenuInvertSel",     "Invert Selection"},
        {"RecordMenuClearSel",      "Clear Selection"},
        {"RecordMenuSelectedFirst", "Promote Selected"},
        {"Yes",                     "Yes"},
        {"No",                      "No"},
        {"OK",                      "OK"},
        {"Cancel",                  "Cancel"},
        {"Confirmation",            "Confirmation"},
        {"Confirm removal",         "Confirm removal"},
        {"Error",                   "Error"},
        {"Warning",                 "Warning"},
        {"Close",                   "Close"},
        {"WaitMessage",             "Please wait..."},
        {"DatabaseMsg1",            "Cannot find \"Windows\" Look&Feel"},
        {"DatabaseMsg2",            "Cannot instantiate \"Windows\" Look&Feel"},
        {"DatabaseMsg3",            "Internal error! Unable to create new Database"},
        {"DatabaseMsg4",            "New title for the database"},
        {"DatabaseMsg5",            "Database title"},
        {"DatabaseMsg6",            "Delimiter used in file \""},
        {"DatabaseMsg7",            "Choose delimiter"},
        {"DatabaseMsg8",            "Delimiter to use in exported file"},
        {"DatabaseMsg9",            "Choose delimiter"},
        {"DatabaseMsg10",           "Quote exported jTable data?"},
        {"DatabaseMsg11",           "Quote data?"},
        {"DatabaseMsg12",           "Save database?"},
        {"DatabaseMsg13",           "New name for the jTable"},
        {"DatabaseMsg14",           "Table name"},
        {"DatabaseMsg15",           "Choose jTable"},
        {"DatabaseMsg16",           "Invalid jTable. Cannot unify a jTable with itself or a null jTable"},
        {"DatabaseMsg17",           "Invalid jTable. Cannot intersect a jTable with itself or a null jTable"},
        {"DatabaseMsg18",           "Invalid jTable. Cannot join a jTable with itself or a null jTable"},
        {"DatabaseMsg19",           "Invalid jTable. Cannot th-join a jTable with itself or a null jTable"},
        {"DatabaseMsg20",           "No selected field"},
        {"DatabaseMsg21",           "Continue with the rest of the changes?"},
        {"DatabaseMsg22",           "Continue?"},
        {"DatabaseMsg23",           "Fields of \"Image\" data type cannot be part of the jTable's key"},
        {"DatabaseMsg25",           "Field \""},
        {"DatabaseMsg26",           "\" is calculated, so it cannot be edited"},
        {"DatabaseMsg27",           "Cannot change the formula of calculated field \""},
        {"DatabaseMsg28",           "\", because it is part of the jTable's key"},
        {"DatabaseMsg29",           "Changing the key of the jTable may alter its data. Do you want to continue?"},
        {"DatabaseMsg30",           "Database already open"},
        {"DatabaseMsg31",           "Unable to open database file \""},
        {"DatabaseMsg32",           "Unable to open jTable file \""},
        {"DatabaseMsg33",           "\". Do you want to find it yourself?"},
        {"DatabaseMsg34",           "\". Probably the file is corrupted"},
        {"DatabaseMsg35",           "No open database"},
        {"DatabaseMsg36",           "Database"},
        {"DatabaseMsg37",           "Untitled"},
        {"DatabaseMsg39",           "Open database"},
        {"DatabaseMsg40",           "Save database "},
        {"DatabaseMsg41",           "Save database \""},
        {"DatabaseMsg42",           "\" as"},
        {"DatabaseMsg43",           "Import jTable from delimited ASCII file"},
        {"DatabaseMsg44",           "table1.txt"},
        {"DatabaseMsg45",           "Export jTable to delimited ASCII file"},
        {"DatabaseMsg46",           "Export jTable \""},
        {"DatabaseMsg47",           "\" to delimited ASCII file"},
        {"DatabaseMsg48",           "Save changes to database"},
        {"DatabaseMsg49",           "Save changes to database \""},
        {"DatabaseMsg50",           "Add jTable to database"},
        {"DatabaseMsg51",           "Save jTable as"},
        {"DatabaseMsg52",           "Save jTable \""},
        {"DatabaseMsg53",           "\" as"},
        {"DatabaseMsg54",           "Select the jTable to which the active jTable will be unified"},
        {"DatabaseMsg55",           "Select the jTable to which jTable \""},
        {"DatabaseMsg56",           "\" will be unified"},
        {"DatabaseMsg57",           "Select the jTable to which the active jTable will be intesected"},
        {"DatabaseMsg58",           "\" will be intersected"},
        {"DatabaseMsg59",           "Select the jTable to which the active jTable will be joined"},
        {"DatabaseMsg60",           "\" will be joined"},
        {"DatabaseMsg61",           "Select the jTable to which the active jTable will be th-joined"},
        {"DatabaseMsg62",           "\" will be th-joined"},
        {"DatabaseMsg63",           "Field properties of jTable \""},
        {"DatabaseMsg64",           "Field properties of the working jTable"},
        {"DatabaseMsg65",           "Field properties for the entire database"},
        {"DatabaseMsg66",           "Colors for jTable \""},
        {"DatabaseMsg67",           "Colors for the working jTable"},
        {"DatabaseMsg68",           "Colors for the entire database"},
        {"DatabaseMsg69",           "Advanced preferences for jTable \""},
        {"DatabaseMsg70",           "Advanced preferences for the working jTable"},
        {"DatabaseMsg71",           "Advanced preferences for the entire database"},
        {"DatabaseMsg72",           "Open jTable"},
        {"DatabaseMsg73",           "Empty database"},
        {"DatabaseMsg74",           "The loaded jTable is hidden so, while it exists in the database, it cannot be displayed"},
        {"DatabaseMsg75",           "Are you sure you want to remove the selected fields?"},
        {"DatabaseMsg76",           "Are you sure you want to remove the selected records?"},
        {"DatabaseMsg77",           "Cannot copy a jTable to a component which hosts the same database as the component to which the jTable belongs"},
        {"DatabaseMsg78",           "No record selected"},
        {"DatabaseMsg79",           " selected record"},
        {"DatabaseMsg80",           " selected records"},
        {"DatabaseMsg81",           "of "},
        {"DatabaseMsg82",           "Record"},
        {"DatabaseMsg83",           "Previous jTable"},
        {"DatabaseMsg84",           "Next jTable"},
        {"DatabaseMsg85",           "Previous record"},
        {"DatabaseMsg86",           "Next record"},
        {"DatabaseMsg87",           "First record"},
        {"DatabaseMsg88",           "Last record"},
        {"DatabaseMsg89",           " is not a record number"},
        {"DatabaseMsg90",           "Invalid record number"},
        {"DatabaseMsg91",           ""},
        {"DatabaseMsg92",           "Loading database..."},
        {"DatabaseMsg93",           "Invalid number of records"},
        {"DatabaseMsg94",           "Invalid number of fields"},
        {"DatabaseMsg95",           " is not a number"},
        {"DatabaseMsg96",           "Are you sure you want to remove the active record?"},
        {"DatabaseMsg97",           "New database"},
        {"DatabaseMsg98",           "Open database"},
        {"DatabaseMsg99",           "Save database"},
        {"DatabaseMsg100",          "Cut"},
        {"DatabaseMsg101",          "Copy"},
        {"DatabaseMsg102",          "Paste"},
        {"DatabaseMsg103",          "Sort selected columns in ascending order"},
        {"DatabaseMsg104",          "Sort selected columns in descending order"},
        {"DatabaseMsg105",          "Find"},
        {"DatabaseMsg106",          "Find previous"},
        {"DatabaseMsg107",          "Find next"},
        {"DatabaseMsg108",          "Add new record"},
        {"DatabaseMsg109",          "Remove active record"},
        {"DatabaseMsg110",          "Remove selected records"},
        {"DatabaseMsg111",          "Add new field"},
        {"DatabaseMsg112",          "Remove selected fields"},
        {"DatabaseMsg113",          "Field properties"},
        {"DatabaseMsg114",          "Select all records"},
        {"DatabaseMsg115",          "Clear record selection"},
        {"DatabaseMsg116",          "Invert record selection"},
        {"DatabaseMsg117",          "Promote selected records"},
        {"DatabaseMsg118",          "Font size"},
        {"DatabaseMsg119",          "Font name"},
        {"DatabaseMsg120",          "Bold"},
        {"DatabaseMsg121",          "Italic"},
        {"DatabaseMsg122",          "Background color"},
        {"DatabaseMsg123",          "Foreground color"},
        {"DatabaseMsg124",          "Grid color"},
        {"DatabaseMsg125",          "Selected record color"},
        {"DatabaseMsg126",          "Active record color"},
        {"DatabaseMsg127",          "Grid chooser"},
        {"DatabaseMsg128",          "Simultaneous row/column selection"},
        {"DatabaseMsg129",          "Highlight non-editable fields"},
        {"DatabaseMsg130",          "All"},
        {"Field",                   "Field"},
        {"New jTable",               "New jTable"},
        {"Standard",                "Standard"},
        {"Formatting",              "Formatting"},
        {"Cut",                     "Cut"},
        {"Copy",                    "Copy"},
        {"Paste",                   "Paste"},
        {"Icon Editor",             "Icon Editor"},
        {"Insert File Path",        "Insert file path"},
        {"Select File",        		"Select File"},
        {"FieldWidthDialogMsg1",    "Selected fields' widths"},
        {"FieldWidthDialogMsg2",    "Minimum width"},
        {"FieldWidthDialogMsg3",    "Maximum width"},
        {"FieldWidthDialogMsg4",    "Field maximum and minimum widths"},
        {"FieldWidthDialogMsg5",    "Invalid value \""},
        {"FieldWidthDialogMsg6",    "\" for field minimum width"},
        {"FieldWidthDialogMsg7",    "Field minimum width cannot be less than 30"},
        {"FieldWidthDialogMsg8",    "\" for field maximum width"},
        {"FieldWidthDialogMsg9",    "Field maximum width cannot be greater than 2000"},
        {"FieldWidthDialogMsg10",   "Minimum field width cannot be greater than maximum field width"},
        {"NewFieldDialogMsg1",      "New field"},
        {"EditFieldDialogMsg",      "Edit field"},
        {"NewFieldDialogMsg2",      "Field name"},
        {"NewFieldDialogMsg3",      "Key"},
        {"NewFieldDialogMsg4",      "Editable"},
        {"NewFieldDialogMsg5",      "Removable"},
        {"NewFieldDialogMsg6",      "Calculated"},
        {"NewFieldDialogMsg7",      "Is the field part of the jTable's key?"},
        {"NewFieldDialogMsg8",      "Is the field editable?"},
        {"NewFieldDialogMsg9",      "Is the field removable?"},
        {"NewFieldDialogMsg10",     "Is the field calculated?"},
        {"NewFieldDialogMsg11",     "Field data type"},
        {"NewFieldDialogMsg12",     "Formula"},
        {"NewFieldDialogMsg13",     "Formula of the calculated field"},
        {"NewFieldDialogMsg14",     "Field properties"},
        {"NewFieldDialogMsg15",     "Clear"},
        {"NewFieldDialogMsg16",     "Store references to images only"},
        {"NewTableDialogMsg1",      "New Table"},
        {"NewTableDialogMsg2",      "Table name"},
        {"NewTableDialogMsg3",      "Type"},
        {"NewTableDialogMsg4",      "Remove field"},
        {"NewTableDialogMsg5",      "Clear field"},
        {"NewTableDialogMsg6",      "Create jTable"},
        {"NewTableDialogMsg7",      "Enter the name of the new field"},
        {"NewTableDialogMsg8",      "Another field named \""},
        {"NewTableDialogMsg9",      "\" has already been defined. This field will not be inserted in the new jTable"},
        {"NewTableDialogMsg10",     "Is the new field calculated?"},
        {"NewTableDialogMsg11",     "Choose the field's data type"},
        {"NewTableDialogMsg12",     "Is the new field part of the jTable's key?"},
        {"NewTableDialogMsg13",     "Is the new field editable?"},
        {"NewTableDialogMsg14",     "Is the new field removable?"},
        {"NewTableDialogMsg15",     "Fill the formula of the calculated field"},
        {"PreferencesDialogMsg1",   "Table preferences"},
        {"PreferencesDialogMsg2",   "Date field format  "},
        {"PreferencesDialogMsg3",   "Time field format  "},
        {"PreferencesDialogMsg4",   "Date/Time data format"},
        {"PreferencesDialogMsg5",   "Show integer part only"},
        {"PreferencesDialogMsg6",   "Use exponentiation format"},
        {"PreferencesDialogMsg7",   "Always show decimal separator"},
        {"PreferencesDialogMsg8",   "Decimal separator   "},
        {"PreferencesDialogMsg9",   "Display thousand separator"},
        {"PreferencesDialogMsg10",  "Thousand separator   "},
        {"PreferencesDialogMsg11",  "Numeric data format"},
        {"PreferencesDialogMsg12",  "Update the working jTable only "},
        {"PreferencesDialogMsg13",  "Data format preferences for the entire database"},
        {"PreferencesDialogMsg14",  "Data format preferences for jTable \""},
        {"PreferencesDialogMsg15",  "Data format"},
        {"PreferencesDialogMsg16",  "Background color"},
        {"PreferencesDialogMsg17",  "Grid color"},
        {"PreferencesDialogMsg18",  "Selection background"},
        {"PreferencesDialogMsg19",  "Highlight color"},
        {"PreferencesDialogMsg20",  " General "},
        {"PreferencesDialogMsg21",  "Integer color"},
        {"PreferencesDialogMsg22",  "Number color"},
        {"PreferencesDialogMsg23",  "Boolean color"},
        {"PreferencesDialogMsg24",  "Date color"},
        {"PreferencesDialogMsg25",  "Time color"},
        {"PreferencesDialogMsg26",  "URL color"},
        {"PreferencesDialogMsg27",  " Field data type colors "},
        {"PreferencesDialogMsg28",  "Choose color"},
        {"PreferencesDialogMsg29",  "Color Chooser"},
        {"PreferencesDialogMsg30",  "Color preferences for the entire database"},
        {"PreferencesDialogMsg31",  "Color preferences for jTable \""},
        {"PreferencesDialogMsg32",  "Color"},
        {"PreferencesDialogMsg33",  "Font"},
        {"PreferencesDialogMsg34",  "Size"},
        {"PreferencesDialogMsg35",  "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqSsTtUuVvWwXxYyZz"},
        {"PreferencesDialogMsg36",  " Text font "},
        {"PreferencesDialogMsg37",  "Row height"},
        {"PreferencesDialogMsg38",  "Row height has to be between \"7\" and \"299\""},
        {"PreferencesDialogMsg39",  "Display horizontal lines"},
        {"PreferencesDialogMsg40",  "Display vertical lines"},
        {"PreferencesDialogMsg41",  "Allow simultaneous selection of fields and records"},
        {"PreferencesDialogMsg42",  "Include data type icons in fields' headers"},
        {"PreferencesDialogMsg43",  "Highlight non-editable fields"},
        {"PreferencesDialogMsg44",  " General settings "},
        {"PreferencesDialogMsg45",  "Advanced preferences for the entire database"},
        {"PreferencesDialogMsg46",  "Advanced preferences for jTable \""},
        {"PreferencesDialogMsg47",  "Advanced"},
        {"PreferencesDialogMsg48",  "Table background color"},
        {"PreferencesDialogMsg49",  "Table grid color"},
        {"PreferencesDialogMsg50",  "Background color of table's selected records"},
        {"PreferencesDialogMsg51",  "Color of the non-editable fields of the jTable"},
        {"PreferencesDialogMsg52",  "Color of integer values"},
        {"PreferencesDialogMsg53",  "Color of numeric values"},
        {"PreferencesDialogMsg54",  "Color of boolean values"},
        {"PreferencesDialogMsg55",  "Color of date values"},
        {"PreferencesDialogMsg56",  "Color of time values"},
        {"PreferencesDialogMsg57",  "Color of URL values"},
        {"PreferencesDialogMsg58",  "Color of alphanumeric values"},
        {"PreferencesDialogMsg59",  "Alphanumeric col."},
        {"PreferencesDialogMsg60",  "Float color"},
        {"PreferencesDialogMsg61",  "Color of float values"},
        {"PreferencesDialogMsg62",  "Selection foreground"},
        {"PreferencesDialogMsg63",  "Foreground color of the table's selected records"},
        {"PreferencesDialogMsg64",  "Active record color"},
        {"PreferencesDialogMsg65",  "Color of the table's active record"},
        {"TableInfoDialogMsg1",     "Information about jTable \""},
        {"TableInfoDialogMsg2",     "Number of records:"},
        {"TableInfoDialogMsg3",     "Number of fields:"},
        {"TableInfoDialogMsg4",     "Number of selected records:"},
        {"TableInfoDialogMsg5",     "Number of selected fields:"},
        {"TableInfoDialogMsg6",     "Key fields:"},
        {"TableInfoDialogMsg7",     "None"},
        {"TableInfoDialogMsg8",     "Calculated fields:"},
        {"TableSortDialogMsg1",     "Sort table"},
        {"TableSortDialogMsg2",     "Select the fields on which table \""},
        {"TableSortDialogMsg3",     "\" will be sorted"},
        {"TableSortDialogMsg4",     " table \""},
        {"TableSortDialogMsg5",     "Fields of"},
        {"TableSortDialogMsg6",     "Sort on fields"},
        {"TableSortDialogMsg7",     "Direction"},
        {"ThJoinDialogMsg1",        "Th-Join: "},
        {"ThJoinDialogMsg2",        "New expression"},
        {"ThJoinDialogMsg3",        "Remove expression"},
        {"ColorPanelMsg1",          "Visible jTable only"},
        {"Number of records",       "Number of records"}, //TableAutoCreateDialog
        {"Number of fields",        "Number of fields"},
        {"Administrator Password",  "Administrator Password"},
        {"Database password",       "Database password"},
        {"DatabaseMsg131",          "Enter password"},
        {"DatabaseMsg132",          "Incorrect administrator password. Try again."},
        {"DatabaseMsg133",          "Specify user mode"},
        {"DatabaseMsg134",          "Incorrect database password. The database remains locked"},
        {"DatabaseMsg135",          "The database is now protected"},
        {"DatabaseMsg136",          "Incorrect password. The database is not protected"},
        {"Novice",                  "Novice"},
        {"Advanced",                "Advanced"},
        {"User mode",               "User mode"},
        {"DatabasePropertiesDialogMsg1",  "Database properties"},
        {"DatabasePropertiesDialogMsg2",  "Name"},
        {"DatabasePropertiesDialogMsg3",  "Surname"},
        {"DatabasePropertiesDialogMsg4",  "Created"},
        {"DatabasePropertiesDialogMsg5",  ""},
        {"DatabasePropertiesDialogMsg6",  "Last modified"},
        {"DatabasePropertiesDialogMsg7",  ""},
        {"DatabasePropertiesDialogMsg8",  "Database creator"},
        {"DatabasePropertiesDialogMsg9",  "Table removal allowed"},
        {"DatabasePropertiesDialogMsg10", "Table addition allowed"},
        {"DatabasePropertiesDialogMsg11", "Table exportation allowed"},
        {"DatabasePropertiesDialogMsg12", "Display hidden tables"},
        {"DatabasePropertiesDialogMsg13", "Protect"},
        {"DatabasePropertiesDialogMsg14", "Unprotect"},
        {"DatabasePropertiesDialogMsg15", "Table properties"},
        {"DatabasePropertiesDialogMsg16", "Enter database password"},
        {"DatabasePropertiesDialogMsg17", "Record addition allowed"},
        {"DatabasePropertiesDialogMsg18", "Record removal allowed"},
        {"DatabasePropertiesDialogMsg19", "Field addition allowed"},
        {"DatabasePropertiesDialogMsg20", "Field removal allowed"},
        {"DatabasePropertiesDialogMsg21", "Field reordering allowed"},
        {"DatabasePropertiesDialogMsg22", "Data change allowed"},
        {"DatabasePropertiesDialogMsg23", "Key change allowed"},
        {"DatabasePropertiesDialogMsg24", "Database properties"},
        {"DatabasePropertiesDialogMsg25", "Table properties"},
        {"DatabasePropertiesDialogMsg26", "Modification of \"Editable\" attribute allowed"},
        {"DatabasePropertiesDialogMsg27", "Modification of \"Removable\" attribute allowed"},
        {"DatabasePropertiesDialogMsg28", "Modification of \"key\" attribute allowed"},
        {"DatabasePropertiesDialogMsg29", "Modification of data type allowed"},
        {"DatabasePropertiesDialogMsg30", "Tranformation to non-calculated allowed"},
        {"DatabasePropertiesDialogMsg31", "Field properties"},
        {"DatabasePropertiesDialogMsg32", "Modification of \"Hidden\" attribute allowed"},
        {"DatabasePropertiesDialogMsg33", "Display hidden fields"},
        {"DatabasePropertiesDialogMsg34", "Modification of \"Hidden\" attribute allowed"},
        {"DatabasePropertiesDialogMsg35", "Modification of calculated field's formula allowed"},
        {"DatabasePropertiesDialogMsg36", "Field properties editing allowed"},
        {"DatabasePropertiesDialogMsg37", "Table renaming allowed"},
        {"MetadataDialogMsg1",            "Description of database "},
        {"MetadataDialogMsg2",            "Description of jTable "},
        {"IconEditActionMsg1",            "The icon was not saved in a separate file. Since this fields stores just references to image files, the icon will not be saved"},
        {"ResultTable",                   "Query results on jTable \""},
        {"SaveDB",                        "Do you want to save the database?"},
        {"warnClose",                     "Warning! Closing Database Editor component..."},
        {"DatabaseEntry",                 "Import database"},
        {"ConstructorTimer",              "Database constructor"},
        {"LoadTimer",                     "Database load"},
        {"SaveTimer",                     "Database save"},
        {"InitESlateAspectTimer",         "Database e-Slate part creation"},
        {"FontType",                      "Font"},
        {"FontSize",                      "Font size"},
        {"Bold",                          "Bold"},
        {"Italic",                        "Italic"},
        {"BackColor",                     "Background color"},
        {"ForeColor",                     "Text color"},
        {"GridColor",                     "Grid color"},
        {"SelectionColor",                "Selection color"},
        {"ActiveRecColor",                "Active record color"},
        {"GridChooser",                   "Grid type"},
        {"RowColumnSelection",            "Record/Field selection policy"},
        {"HightLightNonEditableFields",   "Highlight non-editable fields"},

        {"Previous Table",		"Previous table"},
        {"Next Table",			"Next table"},
        {"Record Number",		"Record number"},
        {"Number of Records",	"Number of records"},
        {"First Record",		"First record"},
        {"Previous Record",		"Previous record"},
        {"Next Record",			"Next record"},
        {"Last Record",			"Last record"},
        {"Message",				"Label"},
        {"Record",				"Label2"},
    };
}
