package gr.cti.eslate.base.container;

import java.util.ListResourceBundle;

public class ContainerBundle extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"ESlate",                "E-Slate"},
        {"Yes",                   "Yes"},
        {"No",                    "No"},
        {"Cancel",                "Cancel"},
        {"MicroworldMenu",        "Microworld"},
        {"MicroworldNew",         "New"},
        {"MicroworldLoad",        "Open"},
        {"MicroworldLoadLocal",   "Load local microworld..."},
        {"MicroworldLoadRemote",  "Load remote microworld..."},
        {"MicroworldReopen",      "Reopen"},
        {"MicroworldNavigate",    "Go"},
        {"MicroworldBack",        "Back"},
        {"MicroworldForward",     "Forward"},
        {"MicroworldHistory",     "History..."},
        {"MicroworldSave",        "Save"},
        {"MicroworldSaveAs",      "Save As"},
        {"MicroworldSaveAsLocal", "Save local microworld..."},
        {"MicroworldSaveAsRemote","Save remote microworld..."},
        {"MicroworldRemoveAll",   "Remove All"},
        {"MicroworldClose",       "Close"},
        {"MicroworldRename",      "Rename..."},
        {"MicroworldNewView",     "New View"},
        {"MicroworldViewMenu",    "Views"},
        {"MicroworldPageSetup",   "Page setup..."},
        {"Print",                 "Print"},
        {"PrintPrinter",          "Printer..."},
        {"PrintPDF",              "PDF file..."},
        {"PrintRTF",              "RTF file..."},
        {"PrintFile",             "File..."},
        {"MicroworldPack",        "Pack"},
        {"MicroworldPackUp",      "Top side"},
        {"MicroworldPackDown",    "Bottom side"},
        {"MicroworldPackLeft",    "Left side"},
        {"MicroworldPackRight",   "Right side"},
        {"MicroworldPackAll",     "All sides"},
        {"MicroworldFTP",         "Share documents..."},
        {"MicroworldProperties",  "Properties..."},
//        {"MicroworldInterface",   "Interface..."},
        {"MicroworldLayers",      "Layers..."},
        {"MicroworldComponentLayers", "Component layers..."},
        {"MicroworldExit",        "Exit"},
        {"ComponentMenu",         "Component"},
        {"ComponentNew",          "New"},
        {"ComponentCut",          "Cut"},
        {"ComponentCopy",         "Copy"},
        {"ComponentPaste",        "Paste"},
        {"ComponentRename",       "Rename..."},
        {"ComponentSave",         "Save..."},
        {"ComponentLoad",         "Load..."},
        {"InvisibleComponentRename", "Rename"},
        {"ComponentRemove",       "Remove"},
        {"ComponentPrint",        "Print"},
        {"ComponentSettings",     "Settings..."},
        {"ComponentCustomizer",   "Customizer..."},
        {"ComponentHelp",         "Help"},
        {"ComponentAbout",        "About"},
        {"ComponentResizable",    "Resizable"},
        {"ComponentFrozen",       "Frozen"},
        {"ComponentActivatableByMousePress", "Activated on mouse click"},
        {"FrameTitleDisplayed",   "Component bar visible"},
        {"ComponentBarProperties",  "Control bar settings"},
        {"MinimizeVisible",       "'Hide' button visible"},
        {"MaximizeVisible",       "'Maximize' button visible"},
        {"CloseVisible",          "'Close' button enabled"},
        {"PlugVisible",           "'Plugs' button visible"},
        {"HelpVisible",           "'Help' button visible"},
        {"InfoVisible",           "'Info' button visible"},
        {"ComponentNameChangeableFromMenuBar",  "Name editing enabled"},
        {"Components",            "Components"},
        {"ComponentNameChangeable", "Rename allowed"},
        {"PreferencesMenu",       "Tools"},
        {"ShowComponentBarMI",	  "Task bar"},
//        {"PreferencesFreeze",     "Freeze"},
        {"PreferencesContainer",  "E-Slate options..."},
        {"PinView",               "Plug editor..."},
        {"ComponentEditor",       "Component editor..."},
        {"ViewEditor",            "View editor..."},
        {"PerformanceMonitor",    "Performance monitor"},
        {"PerformanceMonitorStart", "Start"},
        {"PerformanceMonitorStop",  "Stop"},
        {"PerformanceMonitorEdit",  "Edit..."},
        {"MicroworldHelpMgmt",    "Microworld help"},
        {"MicroworldHelpCreate",  "Create..."},
        {"MicroworldHelpEdit",    "Edit..."},
        {"MicroworldHelpClear",   "Clear"},
//        {"EventEditor",           "Event editor..."},
//        {"ArrangeWindows",        "Arrange windows"},
        {"PreferencesGrid",       "Grid..."},
        {"PreferencesL&F",        "Look & Feel"},
        {"PreferencesConsoles",   "Consoles..."},
        {"PreferencesLogoConsole","Logo console..."},
        {"PreferencesConsolesEnabled", "Consoles enabled"},
        {"HelpMenu",              "Help"},
        {"ESlateHelp",            "E-Slate"},
        {"AboutESlate",           "About"},
        {"MicroworldHelp",        "Microworld"},
        {"Component",             "The component"},
        {"Error",                 "Error"},
        {"Warning",               "Warning"},
        {"Info",                  "Information"},
        {"ContainerMsg1",         " is not registered to E-Slate"},
        {"ContainerMsg2",         "Unable to instantiate component "},
        {"ContainerMsg3",         "The component's constuctor throws exception: "},
        {"ContainerMsg4",         " because it is either an abstract class or an interface"},
        {"ContainerMsg5",         ". The zero-argument constructor is inaccessible"},
        {"ContainerMsg6",         ". Exception: "},
        {"ContainerMsg7",         "Save microworld"},
        {"ContainerMsg8",         "Load microworld"},
        {"ContainerMsg9",         "Wrong addres format "},
        {"ContainerMsg10",        "Please wait..."},
        {"ContainerMsg11",        "The microworld was not saved due to network failure"},
        {"ContainerMsg12",        "Unable to open microworld due to network failure"},
        {"ContainerMsg13",        "Malformed URL \""},
        {"ContainerMsg14",        "Unavailable host \""},
        {"ContainerMsg15",        "Unable to connect to host \""},
        {"ContainerMsg16",        "Error while saving microworld to file \""},
        {"ContainerMsg17",        "Error while opening microworld file \""},
        {"ContainerMsg18",        "Unable to send the file over the network because of its big size"},
        {"ContainerMsg19",        "Do you want to save microworld \""},
        {"ContainerMsg20",        "Save microworld"},
        {"ContainerMsg21",        "Rename component"},
        {"ContainerMsg22",        "Component name"},
        {"ContainerMsg23",        "Rename microworld"},
        {"ContainerMsg24",        "Microworld name"},
        {"ContainerMsg25",        " cannot be restored from the file it was writen to"},
        {"ContainerMsg26",        "Error while saving microworld. "},
        {"ContainerMsg27",        "Do you want to revert to the saved state of microworld:\n \""},
        {"ContainerMsg28",        "Are you sure you want to remove all the components of the microworld?"},
        {"ContainerMsg29",        "Remove all components"},
        {"ContainerMsg30",        "Are you sure you want to remove component \""},
        {"ContainerMsg31",        "Remove component"},
        {"ContainerMsg32",        "\"?"},
        {"ContainerMsg33",        "Problem while closing component"},
        {"ContainerMsg34",        "Trying to overcome... "},
        {"ContainerMsg35",        "Problem while disposing the handle of the component"},
        {"ContainerMsg36",        "Unable to print "},
        {"ContainerMsg37",        "Unable to get a snapshot of the specified component"},
        {"ContainerMsg38",        "Select PDF file"},
        {"ContainerMsg39",        "Select RTF file"},
        {"ContainerMsg40",        "File"},
        {"ContainerMsg41",        "does not exist"},
        {"ContainerMsg42",        "Fatal error while opening microworld file \""},
        {"ContainerMsg43",        "View \""},
        {"ContainerMsg44",        "\" was recorded"},
        {"ContainerMsg45",        " The file can not be writen because it is read-only."},
        {"ContainerMsg46",        "Unable to instantiate component"},
        {"ContainerMsg47",        "There is no registered Look&Feel named "},
        {"ContainerMsg48",        "Unknown Look&Feel class "},
        {"ContainerMsg49",        "Unable to switch to Look&Feel "},
        {"ContainerMsg50",        "Look&Feel \""},
        {"ContainerMsg51",        "\" is not supported on this platform"},
        {"ContainerMsg52",        "Unable to download the remote file"},
        {"ContainerMsg53",        "There in no component named \""},
        {"ContainerMsg54",        "\" in the microworld."},
        {"ContainerMsg55",        "Component \""},
        {"ContainerMsg56",        "\" cannot be printed because it is iconfied."},
        {"ContainerMsg57",        "Select the file to print to"},
        {"ContainerMsg58",        "Unable to save the sounds of the microworld. The sound directory in the microworld file cannot be created"},
        {"ContainerMsg59",        "Unable to save the sounds of the microworld."},
        {"ContainerMsg60",        "Some microworld sounds were not saved in the microworld file. These sounds will be used from their external files."},
        {"ContainerMsg61",        "List of sounds that were not saved"},
        {"ContainerMsg62",        "Unable to save the sound theme to file: \n\""},
        {"ContainerMsg63",        "Unable to read the ESlate sound theme file: \n\""},
        {"ContainerMsg64",        "Unable to play the sound \""},
        {"ContainerMsg65",        "\" from sound theme file: \n\""},
        {"ContainerMsg66",        "Unable to set the Look&Feel of the microworld. Unkown Look&Feel class\n"},
        {"ContainerMsg67",        "can not be saved. It is not a storeable component."},
        {"ContainerMsg68",        "can not be saved. A problem occured while saving the state of the component."},
        {"ContainerMsg69",        "Class"},
        {"ContainerMsg70",        "can not be found in the classpath"},
        {"ContainerMsg71",        "Unable to load class"},
        {"ContainerMsg72",        "has changed in an incompatible way."},
        {"ContainerMsg73",        "The class used to be Externalizable, but is not anymore."},
        {"ContainerMsg74",        "The class used to be Serializable, but is not anymore."},
        {"ContainerMsg75",        "Unable to load the state of component of class"},
        {"ContainerMsg76",        "Unable to load the e-slate state of the component"},
        {"ContainerMsg77",        "There was a problem while loading component from file"},
        {"ContainerMsg78",        "The restored component"},
        {"ContainerMsg79",        "had attached sounds, which could not be restored, because the microworld has not been saved yet for the first time."},
        {"ContainerMsg80",        "If you save the microworld before loading the component, the sounds will be restored properly."},
        {"ContainerMsg81",        "can not be copied to clipboard. A problem occured while copying the component."},
        {"ContainerMsg82",        "There was a problem pasting the component in the clipboard."},
        {"ContainerMsg83",        "The E-Slate clipboard is empty."},
        {"ContainerMsg84",        "The E-Slate clipboard does not contain a component."},
        {"ContainerMsg85",        "The help for the microworld could not be created."},
        {"ContainerMsg86",        "The microworld file may be corrupted as a result of the save failure.\nE-Slate has kept a back-up copy of the last successful save of the microworld.\nWould you like E-Slate to restore this copy?"},
        {"ContainerMsg87",        "The back-up was restored to file"},
        {"ContainerMsg88",        "The back-up of the microworld file could not be restored."},
        {"ContainerMsg89",        "There was a problem while editing the microworld's help."},
        {"Quote",                 "\""},
        {"LoadRemoteMwdMsg1",     "Open remote microworld"},
        {"LoadRemoteMwdMsg2",     "Web site"},
        {"WebSiteLocalDirName",   "Web sites"},
        {"Restore",               "Restore"},
        {"Minimize",              "Hide"},
        {"MinimizeAll",           "Hide All"},
        {"BarOffAll",             "Hide bars"},
        {"BarOnAll",              "Display bars"},
        {"Maximize",              "Maximize"},
        {"Close",                 "Close"},
        {"BarOff",                "Bar visible"},
        {"OK",                    "OK"},
        {"Cancel",                "Cancel"},
        {"Apply",                 "Apply"},
        {"ShowComponentBar",      "Show component bar"},
        {"HideComponentBar",      "Hide component bar"},
        {"ESlateHelpTitle",       "E-Slate Help"},
        {"About",                 "About E-Slate"},
        {"Customizer",            "Customizer"},
        {"Customizer1",           "This is not a visual customizer. A customizer is not useful, unless it is visual."},
        {"Customizer2",           "This customizer does not implement the \"java.beans.Customizer\" interface."},
        {"Customizer3",           "Unable to instantiate customizer"},
        {"ComponentEditorTitle",  "Component editor"},
        {"Loading1",              "Initializing microworld..."},
        {"Loading2",              "Initializing component "},
        {"Saving1",               "Saving microworld..."},
        {"View",                  "View"},
        {"ViewDefined",           "View definition"},
        {"Loading icons",         "Loading component icons. Please wait..."},
        {"ComponentPins",         "Plugs"},
        {"NativeL&F",                   "Platform Look&Feel"},
        {"JavaL&F",                     "Cross-platform Look&Feel"},
        {"Microworld",                  "Microworld"},
        {"?",                           "?"},
/////nikosM
        {"OnServer",                    " on "},
/////nikosM end
        {"PrintErrorMsg1",              "Unable to print. The bin folder of the ESlate installation is missing"},
        {"PrintErrorMsg2",              "Unable to print. The executable file"},
        {"PrintErrorMsg3",              "is missing from the bin folder of the ESlate installation."},
        {"ErrorSound",                  "Error"},
        {"InfoSound",                   "Information"},
        {"QuestionSound",               "Question"},
        {"PlugSound",                   "Plug"},
        {"UnplugSound",                 "Unplug"},
        {"StartSound",                  "E-Slate start"},
        {"EndSound",                    "E-Slate exit"},
        {"ComponentNewSound",           "Component created"},
        {"ComponentShownSound",         "Component shown"},
        {"ComponentHiddenSound",        "Component hidden"},
        {"ComponentClosedSound",        "Component closed"},
        {"MwdOpenedSound",              "Microworld opened"},
        {"MwdClosedSound",              "Microworld closed"},
        {"ViewChangedSound",            "Microworld view changed"},
        {"ComponentActivatedSound",     "Component activated"},
        {"ComponentMaximizedSound",     "Component maximized"},
        {"MicroworldLockedException",   "The microworld is locked. It's settings cannot be changed"},
        {"Microworld current view",     "Current microworld view"},
        {"SaveComponent",               "Save component"},
        {"LoadComponent",               "Load component"},
        {"CreatingMwdBackup",           "Create microworld back-up"},
        {"BackupCopy",                  "MicroworldBackup"},
        {"MicroworldSaveTimer",         "Microworld save"},
        {"MicroworldLoadTimer",         "Microworld load"},
        {"MicroworldCloseTimer",        "Microworld close"},
        {"ViewSwitchTimer",             "View switch"},
        {"MicroworldLoadGroup",         "E-Slate microworld load group"},
        {"FileReadTimer",               "Microworld file read"},
        {"ComponentInstantiationTimer", "Component instantiation"},
        {"HandleRegistrationTimer",     "Handle registration"},
        {"FrameIconCreationTimer",      "Frame & icon creation"},
        {"ScriptSoundLoadTimer",        "Script & Sound load"},
        {"MwdPropertiesRestoreTimer",   "Microworld properties restore"},
        {"MwdLoadedListenerTimer",      "Microworld loaded listener"},
        {"loadmwtip",					"<html><strong>Please press:</strong><ul><li>Ctrl+L, to load a microworld in your pc</li><li>Ctrl+R, to load a microworld from a remote server</li></ul></html>"},
    };
}
