package gr.cti.eslate.base.container;

import java.util.ListResourceBundle;


public class MwdPropertiesDialogBundle_el_GR extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"Title",                       "Ρυθμίσεις μικρόκοσμου"},
        {"ControlBar",                  "Μπάρα ελέγχου ψηφίδων"},
        {"ComponentPanel",              "Ψηφίδες"},
        {"MicroworldPanel",             "Μικρόκοσμος"},
        {"Metadata",                    "Πληροφορίες"},
        {"ControlBarTitle",             "Ρυθμίσεις μπάρας ελέγχου"},
        {"ComponentPanelTitle",         "Ρυθμίσεις ψηφίδων"},
        {"MicroworldGeneralSettings",   "Γενικές ρυθμίσεις"},
        {"MicroworldSizeSettings",      "Ρυθμίσεις επιφάνειας εργασίας"},
        {"OK",                          "Εντάξει"},
        {"Cancel",                      "Άκυρο"},
        {"Apply",                       "Εφαρμογή"},
        {"ComponentCreationEnabled",    "Επιτρέπεται η δημιουργία ψηφίδων"},
        {"ComponentRemovalEnabled",     "Επιτρέπεται η διαγραφή ψηφίδων"},
        {"MwdBackgroundChangeEnabled",  "Επιτρέπεται η διαμόρφωση του υποβάθρου"},
        {"MwdStorageEnabled",           "Επιτρέπεται η αποθήκευση"},
        {"MwdPinViewEnabled",           "Επιτρέπεται η (ανα)διαμόρφωση συνδέσμων"},
        {"MwdPopupEnabled",             "Μενού δεξιού-click ενεργό"},
        {"MenuBarVisible",              "Μπάρα μενού Αβακίου ορατή"},
        {"ComponentBarEnabled",         "Κατάλογος ψηφίδων ενεργός"},
        {"microworldNameUserDefined",   "Ανάθεση του ονόματος αρχείου στον Μικρόκοσμο"},
        {"ComponentNameChangeAllowed",  "Επιτρέπεται η αλλαγή ονόματος"},
        {"ResizeAllowed",               "Επιτρέπεται η μεταβολή μεγέθους"},
        {"MoveAllowed",                 "Επιτρέπεται η μετακίνηση"},
        {"Frozen",                      "Επιτρέπεται η μεταβολή της κατάστασης 'παγίωσης'"},
        {"ActivateOnMouseClick",        "Επιτρέπεται η μεταβολή του τρόπου ενεργοποίησης"},
        {"OutlineDrag",                 "Σύρσιμο πλαισίου μόνο"},
        {"DisplayActiveComponent",      "Οπτική ένδειξη της ενεργής ψηφίδας"},
        {"DisplayActiveComponentTip",   "Ρυθμίζει αν η ενεργή ψηφίδα θα ξεχωρίζει από τις υπόλοιπες του μικροκόσμου"},
        {"ActiveFrameVisible",          "Ενεργή ψηφίδα πάντα ορατή"},
        {"ActiveFrameVisibleTip",       "Ρυθμίζει αν το περιβάλλον του Αβακίου θα σκρολλάρει αυτόματα, ώστε η ενεργή ψηφίδα να είναι πάντα ορατή"},
        {"ComponentBarVisible",         "Μπάρα ψηφίδων ορατή"},
        {"MinimizeAllowed",             "Πλήκτρο 'Απόκρυψη' ορατό"},
        {"MaximizeAllowed",             "Πλήκτρο 'Μεγιστοποίηση' ορατό"},
        {"CloseControlEnabled",         "Πλήκτρο 'Διαγραφή' ορατό"},
        {"PinControlEnabled",           "Πλήκτρο 'Σύνδεσμοι' ορατό"},
        {"HelpEnabled",                 "Πλήκτρο 'Βοήθεια' ορατό"},
        {"ComponentInfoEnabled",        "Πλήκτρο 'Πληροφορίες' ορατό"},
        {"ComponentRenameThroughBarEnabled", "Επιτρέπεται η αλλαγή ονόματος"},
        {"Width",                       "Πλάτος"},
        {"Height",                      "Ύψος"},
        {"Resizable",                   "Μεταβαλλόμενο μέγεθος"},
        {"AutoExpandable",              "Αυτόματη επέκταση μικρόκοσμου"},
        {"AutoScrollable",              "Αυτόματη \"κύληση\" μικρόκοσμου"},
        {"ExceedBoundaries",            "Μετακίνηση ψηφίδων πέρα από τα όρια του μικρόκοσμου"},
        {"DesktopDrag",                 "Κυλιόμενη επιφάνεια εργασίας"},
        {"ScrollBarAsNeeded",           "ΟΤΑΝ ΧΡΕΙΑΖΕΤΑΙ"},
        {"ScrollBarNever",              "ΠΟΤΕ"},
        {"ScrollBarAlways",             "ΠΑΝΤΑ"},
        {"VerticalSP",                  "Εμφάνιση κάθετης μπάρας \"κύλησης\""},
        {"HorizontalSP",                "Εμφάνιση οριζόντιας μπάρας \"κύλησης\""},
        {"WidthTip",                    "Πλάτος μικρόκοσμου"},
        {"HeightTip",                   "Ύψος μικρόκοσμου"},
        {"ResizableTip",                "Επιτρέπεται η αλλαγή μεγέθους του μικρόκοσμου"},
        {"AutoExpandableTip",           "Επέκταση του μικρόκοσμου, όταν κάποια ψηφίδα μετακινηθεί πέρα από τα όριά του"},
        {"AutoScrollableTip",           "\"Κύληση\" του μικρόκοσμου, όταν κάποια ψηφίδα μετακινηθεί πέρα από τα όριά του"},
        {"DesktopDragTip",              "\"Κύληση\" του μικρόκοσμου με σύρσιμο της επιφάνειας εργασίας"},
        {"ExceedBoundariesTip",         "Επιτρέπεται η μετακίνηση ψηφίδων πέρα από τα όρια του μικρόκοσμου"},
        {"VerticalSPTip",               "Πολιτική εμφάνισης κάθετης μπάρας \"κύλησης\" μικρόκοσμου"},
        {"HorizontalSPTip",             "Πολιτική εμφάνισης οριζόντιας μπάρας \"κύλησης\" μικρόκοσμου"},
        {"MenuSystemHeavyWeight",       "Χρήση \"heavyweight\" μενού"},
        {"StoreSkinsPerView",           "Αποθήκευση skins ψηφίδων σε κάθε όψη"},
        {"StoreSkinsPerViewTip",        "Ρυθμίζει τη δυνατότητα αποθήκευσης διαφορετικών skins για τις ψηφίδες μεταξύ των όψεων του μικροκόσμου"},
        {"Profiles",                    "Προφίλ ρυθμίσεων"},

        {"MwdPrintAllowed",             "Εκτύπωση μικρόκοσμου"},
        {"MwdPageSetupAllowed",         "Διαμόρφωση σελίδας εκτύπωσης"},
        {"ViewCreationAllowed",         "Δημιουργία όψεων"},
        {"ViewRemovalAllowed",          "Διαγραφή όψεων"},
        {"ViewRenameAllowed",           "Αλλαγή ονόματος όψεων"},
        {"ViewActivationAllowed",       "Αλλαγή ενεργής όψης"},
        {"ViewMgmtAllowed",             "Χρήση διαχειριστή όψεων"},
        {"ESlateOptionMgmtAllowed",     "Χρήση διαλόγου ρυθμίσεων Αβακίου"},
        {"ComponentPropertyMgmtAllowed","Διαχείριση ιδιοτήτων ψηφίδων ενεργή"},
        {"ComponentEventMgmtAllowed",   "Διαχείριση γεγονότων ψηφίδων ενεργή"},
        {"ComponentSoundMgmtAllowed",   "Διαχείριση ήχων ψηφίδων ενεργή"},
        {"MwdLAFChangeAllowed",         "Αλλαγή θέματος περιβάλλοντος μικρόκοσμου"},
        {"ConsolesAllowed",             "Κονσόλες ενεργές"},
        {"ESlateComponentBarMenuEnabled", "Pop-up μενού μπάρας ψηφίδων Αβακίου ενεργό"},
        {"ESlateComponentBarEnabled",   "Μπάρα ψηφίδων Αβακίου ενεργή"},
        {"MwdNameChangeAllowed",        "Αλλαγή ονόματος μικροκόσμου"},
        {"ComponentNameChangeAllowed",  "Αλλαγή ονόματος ψηφίδων"},
        {"ComponentBarMenuEnabled",     "Pop-up μενού μπάρας τίτλου ψηφίδων ενεργό"},
        {"MwdLayerMgmtAllowed",         "Διαχείριση επιπέδων ψηφίδων ενεργή"},
        {"GridMgmtAllowed",             "Διαχείριση πλέγματος επιφάνειας εργασίας ενεργή"},
        {"ComponentMinimizeAllowed",    "Επιτρέπεται η απόκρυψη ψηφίδων"},
        {"ComponentMaximizeAllowed",    "Επιτρέπεται η μεγιστοποίηση ψηφίδων"},
    };
}
