package gr.cti.eslate.base.container;

import java.util.ListResourceBundle;
//import org.netbeans.editor.LocaleSupport;


public class ScriptDialogBundle_el_GR extends ListResourceBundle { //implements LocaleSupport.Localizer {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"DialogTitle1",    "Ενέργεια γεγονότος \""},
        {"DialogTitle2",    " της ψηφίδας \""},
        {"DialogTitle",     "Διαχειριστής προγραμμάτων ενεργειών ψηφίδων"},
        {"Apply",           "Εφαρμογή"},
        {"Close",           "Κλείσιμο"},
        {"Remove",          "Διαγραφή"},
        {"Error",           "Λάθος"},
        {"ScriptName",      "Ενέργεια"},
        {"CompileFailureMessage", "Η διαδικασία compilation τελείωσε με απρόσμενα λάθη. Πιθανότατα δεν έχει τεθεί σωστά το classpath"},
        {"CompileFailureMessage2","Δεν είναι δυνατή η μετάφραση του κώδικα. Ο μεταφραστής \"jikes\" δεν μπορεί να βρεθεί"},
        {"CompileFailureMessage3","Αδύνατος ο ορισμός της ενέργειας"},
        {"CompileDenialMsg1",  "Η ψηφίδα \""},
        {"CompileDenialMsg2",  "\" δεν υπάρχει πια στον μικρόκοσμο. Η διαδικασία μετάφρασης εγκαταλείπεται."},
        {"CompileDenialMsg3",  "\" δεν υπάρχει πια στον μικρόκοσμο."},
        {"AvailableVariables",  "Mεταβλητές"},
        {"CutTip",              "Αποκοπή"},
        {"CopyTip",             "Αντιγραφή"},
        {"PasteTip",            "Επικόλληση"},
        {"UndoTip",             "Ακύρωση"},
        {"RedoTip",             "Επανάληψη"},
		{"NewScriptTip",        "Νέα Java κλάσση"},
        {"LoadTip",             "Άνοιγμα προγράμματος"},
        {"SaveTip",             "Αποθήκευση προγράμματος"},
        {"FindTip",             "Εύρεση"},
        {"FindNextTip",         "Εύρεση επόμενου"},
        {"FindPrevTip",         "Εύρεση προηγούμενου"},
        {"ReplaceTip",          "Αντικατάσταση"},
        {"GoToLineTip",         "Μετακίνηση στη γραμμή"},
        {"CompileTip",          "Ορισμός ενέργειας"},
        {"ClearTip",            "Διαγραφή ενέργειας"},
        {"RunTip",              "Εκτέλεση επιλογής προγράμματος"},
        {"ColorsTip",           "Ρυθμίσεις εμφάνισης κώδικα"},
        {"FileDialogTitle",     "Αποθήκευση προγράμματος"},
        {"OpenFileDialogTitle", "Άνοιγμα προγράμματος"},
        {"Error",               "Λάθος"},
        {"UnableToSave",        "Αδύνατη η αποθήκευση του προγράμματος στο αρχείο \""},
        {"UnableToLoad",        "Αδύνατη η ανάκτηση του προγράμματος από το αρχείο \""},
        {"Find",                "Εύρεση"},
        {"FindWhat",            "Εύρεση στο Logo πρόγραμμα"},
        {"UnableToFind1",       "Δεν βρέθηκε το \""},
        {"UnableToFind2",       "\" στο πρόγραμμα."},
        {"UnableToFind3",       "Δεν βρέθηκαν άλλες εμφανίσεις του \""},
        {"GoTo",                "Μετακίνηση στη γραμμή"},
        {"GoToLine",            "Πήγαινε στη γραμμή:"},
        {"BadLineNumber1",      "Μη αποδεκτός αριθμός γραμμής"},
        {"BadLineNumber2",      "Το πρόγραμμα δεν περιλαμβάνει περισσότερες από "},
        {"BadLineNumber3",      " γραμμές"},
        {"LineCount",           "Αριθμός γραμμών: "},
        {"SaveChanges",         "Αποθήκευση αλλαγών?"},
        {"ScriptChanged",       "Το πρόγραμμα έχει αλλάξει. Θέλετε να αποθηκευτούν οι αλλαγές;"},
        {"Yes",                 "Ναι"},
        {"No",                  "Όχι"},
        {"Cancel",              "Άκυρο"},
        {"NoScript",            "Καμία ενέργεια"},
        {"Modified",            "Τροποποιημένο"},
        {"New script",          "Νέο"},
        {"ConfirmScriptRemoval","Επιβεβαίωση διαγραφής προγράμματος"},
        {"RemoveScript?",       "Θέλετε σίγουρα να διαγραφεί το πρόγραμμα της ενέργειας "},
        {"?",                   ";"},
        {"EventClassChanged",   "Αδύνατη η μετάφραση του Java προγράμματος. Η δήλωση της κλάσης του προγράμματος θα έπρεπε να είναι: "},
		{"NewScriptMsg",        "Εισάγετε το όνομα του νέου προγράμματος"},
		{"NewScriptTitle",      "Νέα Java κλάσση"},
		{"ClassNameExists",     "Δεν στάθηκε δυνατός ο ορισμός της Java κλάσσης.\n Υπάρχει ήδη κλάσση με το όνομα "},
		{"Java classes",        "Java κλάσσεις"},
		{"Class Type",          "Τύπος κλάσσης"},
		{"Class Name",          "Όνομα κλάσσης (*)"},
		{"Class Package",       "Πακέτο κλάσσης"},
		{"Plain Class",         "Κανονική"},
		{"Singleton Class",     "Singleton"},
		{"OK",                  "Εντάξει"},
		{"Cancel",              "Άκυρο"},
		{"Notes1",              "(*) To πακέτο της κλάσσης μπορεί να αλλαχθεί στο μέλλον από το χρήστη."},
		{"Notes2",              "Ωστόσο δεν επιτρέπεται η αλλαγή του ονόματος της κλάσσης."},
    };
}

