package gr.cti.eslate.utils.browser.webWindow;

import gr.cti.eslate.utils.browser.*;

import horst.webwindow.event.*;

/**
 * Event generated when a link is followed by clicking on it with the mouse.
 *
 * @author      Kriton Kyrimis
 * @version     2.0.0, 18-May-2006
 */
public class WWLinkFollowedEvent extends LinkFollowedEvent
{
  /**
    * The encapsulated event.
    */
  LinkEvent wwEvent;

  /**
   * Create a WWLinkFollowedEvent by converting a LinkEvent
   * generated by the ICE browser.
   * @param     e       The event to convert.
   */
  public WWLinkFollowedEvent(LinkEvent e)
  {
    wwEvent = e;
  }

  /**
   * Returns the URL of the link that was followed.
   * @return    The requested URL.
   */
  public String getLink()
  {
    return wwEvent.getLink();
  }
}
