package gr.cti.eslate.base.container;

import java.util.ListResourceBundle;

/**
 * User: yiorgos
 * Date: 17 Δεκ 2007
 * Time: 11:52:53 πμ
 */
public class ContainerBundle_el_GR extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
            {"ESlate",                "Αβάκιο"},
            {"Yes",                   "Ναι"},
            {"No",                    "Όχι"},
            {"Cancel",                "Άκυρο"},
            {"MicroworldMenu",        "Μικρόκοσμος"},
            {"MicroworldNew",         "Νέος"},
            {"MicroworldLoad",        "Άνοιγμα"},
            {"MicroworldLoadLocal",   "Άνοιγμα τοπικού μικρόκοσμου..."},
            {"MicroworldLoadRemote",  "Άνοιγμα απομακρυσμένου μικρόκοσμου..."},
            {"MicroworldReopen",      "Άνοιγμα εκ νέου"},
            {"MicroworldNavigate",    "Πλοήγηση"},
            {"MicroworldBack",        "Προηγούμενος"},
            {"MicroworldForward",     "Επόμενος"},
            {"MicroworldHistory",     "Ιστορία..."},
            {"MicroworldSave",        "Αποθήκευση"},
            {"MicroworldSaveAs",      "Αποθήκευση ως"},
            {"MicroworldSaveAsLocal", "Αποθήκευση τοπικού μικρόκοσμου..."},
            {"MicroworldSaveAsRemote","Αποθήκευση απομακρυσμένου μικρόκοσμου..."},
            {"MicroworldRemoveAll",   "Αφαίρεση ψηφίδων"},
            {"MicroworldClose",       "Κλείσιμο"},
            {"MicroworldRename",      "Αλλαγή τίτλου..."},
            {"MicroworldNewView",     "Νέα όψη"},
            {"MicroworldViewMenu",    "Όψεις"},
            {"MicroworldPageSetup",   "Διαμόρφωση σελίδας..."},
            {"Print",                 "Εκτύπωση"},
            {"PrintPrinter",          "Εκτυπωτής..."},
            {"PrintPDF",              "PDF αρχείο..."},
            {"PrintRTF",              "RTF αρχείο..."},
            {"PrintFile",             "Αρχείο..."},
            {"MicroworldPack",        "Πακετάρισμα"},
            {"MicroworldPackUp",      "Πάνω πλευρά"},
            {"MicroworldPackDown",    "Κάτω πλευρά"},
            {"MicroworldPackLeft",    "Αριστερή πλευρά"},
            {"MicroworldPackRight",   "Δεξιά πλευρά"},
            {"MicroworldPackAll",     "Όλες τις πλευρές"},
            {"MicroworldFTP",         "Ανταλλαγή αρχείων..."},
            {"MicroworldExit",        "Έξοδος"},
            {"MicroworldProperties",  "Ιδιότητες..."},
//        {"MicroworldInterface",   "Εμφάνιση..."},
            {"MicroworldLayers",      "Επίπεδα..."},
            {"MicroworldComponentLayers", "Επίπεδα ψηφίδων..."},
            {"ComponentMenu",         "Ψηφίδα"},
            {"ComponentNew",          "Νέα"},
            {"ComponentCut",          "Αποκοπή"},
            {"ComponentCopy",         "Αντιγραφή"},
            {"ComponentPaste",        "Επικόλληση"},
            {"ComponentRemove",       "Αφαίρεση"},
            {"ComponentRename",       "Αλλαγή ονόματος..."},
            {"ComponentSave",         "Αποθήκευση..."},
            {"ComponentLoad",         "Ανάκτηση..."},
            {"InvisibleComponentRename", "Αλλαγή ονόματος"},
            {"ComponentPrint",        "Εκτύπωση..."},
            {"ComponentSettings",     "Ρυθμίσεις..."},
            {"ComponentCustomizer",   "Προσαρμοστής..."},
            {"ComponentHelp",         "Βοήθεια"},
            {"ComponentAbout",        "Περί της ψηφίδας"},
            {"ComponentResizable",    "Μεταβαλλόμενο μέγεθος"},
            {"ComponentFrozen",       "Παγιωμένη"},
            {"ComponentActivatableByMousePress", "Ενεργοποίηση με click"},
            {"FrameTitleDisplayed",   "Μπάρα ψηφίδας ορατή"},
            {"ComponentBarProperties","Ρυθμίσεις μπάρας"},
            {"MinimizeVisible",       "Πλήκτρο 'Απόκρυψη' ορατό"},
            {"MaximizeVisible",       "Πλήκτρο 'Μεγιστοποίηση' ορατό"},
            {"CloseVisible",          "Πλήκτρο 'Διαγραφή' ορατό"},
            {"PlugVisible",           "Πλήκτρο 'Σύνδεσμοι' ορατό"},
            {"HelpVisible",           "Πλήκτρο 'Βοήθεια' ορατό"},
            {"InfoVisible",           "Πλήκτρο 'Πληροφορίες' ορατό"},
            {"ComponentNameChangeableFromMenuBar",  "Επιτρέπεται η αλλαγή ονόματος"},
            {"ComponentNameChangeable", "Δυνατότητα αλλαγής ονόματος"},
            {"Components",            "Ψηφίδες"},
            {"PreferencesMenu",       "Εργαλεία"},
//        {"PreferencesFreeze",     "Παγίωση"},
            {"ShowComponentBarMI",	  "Γραμμή εργασίας"},
            {"PreferencesContainer",  "Ρυθμίσεις Αβακίου..."},
            {"PinView",               "Διαχείριση συνδέσμων..."},
            {"ComponentEditor",       "Διαχείριση ψηφίδων..."},
            {"ViewEditor",            "Διαχείριση όψεων..."},
            {"PerformanceMonitor",    "Μέτρηση απόδοσης μικρόκοσμου"},
            {"PerformanceMonitorStart", "Έναρξη"},
            {"PerformanceMonitorStop",  "Παύση"},
            {"PerformanceMonitorEdit",  "Διαχείριση..."},
            {"MicroworldHelpMgmt",    "Bοήθεια μικρόκοσμου"},
            {"MicroworldHelpCreate",  "Δημιουργία..."},
            {"MicroworldHelpEdit",    "Διαχείριση..."},
            {"MicroworldHelpClear",   "Καθαρισμός"},
//        {"EventEditor",           "Διαχείριση γεγονότων..."},
//        {"ArrangeWindows",        "Τακτοποίηση παραθύρων"},
            {"PreferencesGrid",       "Πλέγμα..."},
            {"PreferencesL&F",        "Θέμα περιβάλλοντος"},
            {"PreferencesConsolesEnabled", "Χρήση κονσολών"},
            {"PreferencesConsoles",   "Κονσόλες..."},
            {"PreferencesLogoConsole","Logo κονσόλα..."},
            {"HelpMenu",              "Βοήθεια"},
            {"ESlateHelp",            "Αβάκιο"},
            {"AboutESlate",           "Περί του Αβακίου"},
            {"MicroworldHelp",        "Μικρόκοσμος"},
            {"Component",             "Η ψηφίδα"},
            {"Error",                 "Λάθος"},
            {"Warning",               "Προειδοποίηση"},
            {"Info",                  "Πληροφορία"},
            {"ContainerMsg1",         " δεν είναι γνωστή στο Αβάκιο"},
            {"ContainerMsg2",         "Δεν είναι δυνατή η δημιουργία ψηφίδας τύπου "},
            {"ContainerMsg3",         "Ο constuctor της ψηφίδας πετάει το exception: "},
            {"ContainerMsg4",         " διότι πρόκειται είτε για abstract κλάση είτε για interface"},
            {"ContainerMsg5",         ". Δεν είναι επιτρεπτή η πρόσβαση στο άνευ παραμέτρων constructor"},
            {"ContainerMsg6",         ". Πρόβλημα: "},
            {"ContainerMsg7",         "Αποθήκευση μικρόκοσμου"},
            {"ContainerMsg8",         "Ανάκτηση μικρόκοσμου"},
            {"ContainerMsg9",         "Άκυρη μορφή διεύθυνσης "},
            {"ContainerMsg10",        "Παρακαλώ περιμένετε..."},
            {"ContainerMsg11",        "Αποτυχία αποθήκευσης μικρόκοσμου λόγω σφάλματος δικτύου"},
            {"ContainerMsg12",        "Αποτυχία ανοίγματος μικρόκοσμου λόγω σφάλματος δικτύου"},
            {"ContainerMsg13",        "Λάθος URL \""},
            {"ContainerMsg14",        "Άγνωστος ή μη διαθέσιμος δικτυακός τόπος \""},
            {"ContainerMsg15",        "Αδυναμία επαφής με τον δικτυακό τόπο \""},
            {"ContainerMsg16",        "Σφάλμα κατά την αποθήκευση του μικρόκοσμου στο αρχείο \""},
            {"ContainerMsg17",        "Σφάλμα κατά τo άνοιγμα του αρχείου μικρόκοσμου \""},
            {"ContainerMsg18",        "Αδύνατη η μεταφορά και αποθήκευση του αρχείου λόγω μεγάλου μεγέθους"},
            {"ContainerMsg19",        "Θέλετε να αποθηκευτεί ο μικρόκοσμος"},
            {"ContainerMsg20",        "Αποθήκευση μικρόκοσμου"},
            {"ContainerMsg21",        "Αλλαγή ονόματος ψηφίδας"},
            {"ContainerMsg22",        "Όνομα ψηφίδας"},
            {"ContainerMsg23",        "Αλλαγή τίτλου μικρόκοσμου"},
            {"ContainerMsg24",        "Τίτλος μικρόκοσμου"},
            {"ContainerMsg25",         " δεν μπορεί να δημιουργηθεί από το αρχείο στο οποίο αποθηκεύτηκε"},
            {"ContainerMsg26",        "Σφάλμα κατά την αποθήκευση του μικρόκοσμου."},
            {"ContainerMsg27",        "Eπαναφορά της αποθηκευμένης κατάστασης του μικρόκοσμου:\n \""},
            {"ContainerMsg28",        "Είστε σίγουροι ότι θέλετε να αφαιρέσετε όλες τις ψηφίδες του μικρόκοσμου;"},
            {"ContainerMsg29",        "Αφαίρεση ψηφίδων"},
            {"ContainerMsg30",        "Είστε σίγουροι ότι θέλετε να αφαιρέσετε την ψηφίδα \""},
            {"ContainerMsg31",        "Αφαίρεση ψηφίδας"},
            {"ContainerMsg32",        "\";"},
            {"ContainerMsg33",        "Πρόβλημα κατά το κλείσιμο της ψηφίδας"},
            {"ContainerMsg34",        "Έγινε προσπάθεια αντιμετώπισής του... "},
            {"ContainerMsg35",        "Πρόβλημα κατά την απόρριψη του handle της ψηφίδας"},
            {"ContainerMsg36",        "Δεν ήταν δυνατή η ολοκλήρωση της διαδικασίας εκτύπωσης"},
            {"ContainerMsg37",        "Δεν στάθηκε δυνατή η φωτογράφηση της ψηφίδας"},
            {"ContainerMsg38",        "Επιλογή PDF αρχείου"},
            {"ContainerMsg39",        "Επιλογή RTF αρχείου"},
            {"ContainerMsg40",        "Το αρχείο"},
            {"ContainerMsg41",        "δεν υπάρχει"},
            {"ContainerMsg42",        "Μη αποκαταστάσιμο σφάλμα κατά το άνοιγμα του αρχείου μικρόκοσμου \""},
            {"ContainerMsg43",        "Καταγράφηκε νέα όψη με το όνομα \""},
            {"ContainerMsg44",        "\""},
            {"ContainerMsg45",        " Το αρχείο δεν είναι εγγράψιμο."},
            {"ContainerMsg46",        "Δεν είναι εκκίνηση της ψηφίδας"},
            {"ContainerMsg47",        "Δεν υπάρχει εγκατεστημένο θέμα περιβάλλοντος με όνομα "},
            {"ContainerMsg48",        "Άγνωστη κλάση θέματος περιβάλλοντος "},
            {"ContainerMsg49",        "Δεν στάθηκε δυνατή η ενεργοποίηση του θέματος περιβάλλοντος "},
            {"ContainerMsg50",        "Το θέμα περιβάλλοντος \""},
            {"ContainerMsg51",        "\" δεν υποστηρίζεται σε αυτή την πλατφόρμα"},
            {"ContainerMsg52",        "Στάθηκε αδύνατη η μεταφορά του απομακρυσμένου αρχείου"},
            {"ContainerMsg53",        "Δεν υπάρχει ψηφίδα με όνομα \""},
            {"ContainerMsg54",        "\" στον μικρόκοσμο."},
            {"ContainerMsg55",        "Η ψηφίδα \""},
            {"ContainerMsg56",        "\" δεν είναι δυνατό να εκτυπωθεί, διότι έχει αποκρυφτεί."},
            {"ContainerMsg57",        "Επιλέξτε το αρχείο στο οποίοθα γίνει η εκτύπωση"},
            {"ContainerMsg58",        "Δε στάθηκε δυνατή η πλήρης αποθήκευση των ήχων του μικρόκοσμου. Αδύνατη η δημιουργία καταλόγου ήχων στο αρχείο μικροκόσμου."},
            {"ContainerMsg59",        "Δε στάθηκε δυνατή η πλήρης αποθήκευση των ήχων του μικρόκοσμου."},
            {"ContainerMsg60",        "Κάποιοι ήχοι δεν αποθηκεύτηκαν στο αρχείο του μικρόκοσμου. Οι ήχοι αυτοί θα συνεχίσουν να χρησιμοποιούνται από τα εξωτερικά αρχεία τους."},
            {"ContainerMsg61",        "Λίστα ήχων που δεν αποθηκεύτηκαν"},
            {"ContainerMsg62",        "Δε στάθηκε δυνατή η αποθήκευση του θέματος ήχων στο αρχείο: \n\""},
            {"ContainerMsg63",        "Δε στάθηκε δυνατή η ανάγνωση του αρχείου ήχων του Αβακίου: \n\""},
            {"ContainerMsg64",        "Δεν στάθηκε δυνατό το παίξιμο του ήχου \""},
            {"ContainerMsg65",        "\" από το αρχείο θέματος ήχων: \n\""},
            {"ContainerMsg66",        "Αδύνατη η ανάθεση θέματος περιβάλλοντος στον μικροκόσμο.\nΆγνωστη κλάση θέματος περιβάλλοντος:\n"},
            {"ContainerMsg67",        "δεν μπορεί να αποθηκευτεί. Δεν είναι αποθηκεύσιμη ψηφίδα."},
            {"ContainerMsg68",        "δεν μπορεί να αποθηκευτεί. Πρόβλημα κατά την αποθήκευση της κατάστασης της ψηφίδας."},
            {"ContainerMsg69",        "Η κλάση"},
            {"ContainerMsg70",        "δεν υπάρχει στο classpath."},
            {"ContainerMsg71",        "Πρόβλημα κατά το φόρτωμα της κλάσης"},
            {"ContainerMsg72",        "έχει αλλάξει με μη συμβατό τρόπο."},
            {"ContainerMsg73",        "Η κλάση ενώ ήταν Externalizable, δεν είναι πια."},
            {"ContainerMsg74",        "Η κλάση ενώ ήταν Serializable, δεν είναι πια."},
            {"ContainerMsg75",        "Δεν στάθηκε δυνατή η αποκατάσταση της κατάστασης ψηφίδας της κλάσης"},
            {"ContainerMsg76",        "Δεν στάθηκε δυνατή η αποκατάσταση της Αβακιακής πλευράς της ψηφίδας"},
            {"ContainerMsg77",        "Παρουσιάστηκε πρόβλημα κατά την ανάκτηση ψηφίδας από το αρχείο"},
            {"ContainerMsg78",        "Η εισαχθείσα ψηφίδα"},
            {"ContainerMsg79",        "χρησιμοποιεί ήχους, οι οποίοι δεν μπόρεσαν να διαβαστούν, διότι ο μικρόκοσμος δεν έχει αποθηκευτεί ακόμη για πρώτη φορά."},
            {"ContainerMsg80",        "Αν θέλετε να εισαχθεί η ψηφίδα με τους ήχους της, πρέπει πρώτα να αποθηκεύσετε τον μικρόκοσμο και μετά να εισάγετε την ψηφίδα."},
            {"ContainerMsg81",        "δεν μπορεί να αντιγραφεί στο πρόχειρο. Παρουσιάστηκε πρόβλημα κατά την αντιγραφή της."},
            {"ContainerMsg82",        "Πρόβλημα κατά την επικόλληση ψηφίδας από το πρόχειρο."},
            {"ContainerMsg83",        "Το πρόχειρο του Αβακίου είναι άδειο."},
            {"ContainerMsg84",        "Το πρόχειρο του Αβακίου δεν περιέχει κάποια ψηφίδα."},
            {"ContainerMsg85",        "Δε στάθηκε δυνατή η σύνταξη της βοήθειας του μικρόκοσμου."},
            {"ContainerMsg86",        "To αρχειο του μικροκόσμου μπορεί να έχει καταστραφεί ως αποτέλεσμα του λάθους στην διαδικασία αποθήκευσης.\nΤο Αβάκιο έχει κρατήσει αντίγραφο του αρχείου του μικρόκοσμου από την τελευταία επιτυχημένη αποθήκευση.\nΘέλετε να αποκατασταθεί το αντιγραφό;"},
            {"ContainerMsg87",        "Το αντίγραφο ασφαλείας αποκαταστάθηκε στο αρχείο"},
            {"ContainerMsg88",        "Δεν στάθηκε δυνατή η αποκατάσταση του αντιγράφου ασφαλείας του μικρόκοσμου."},
            {"ContainerMsg89",        "Παρουσιάστηκε πρόβλημα κατά τη διαχείριση της βοήθειας του μικρόκοσμου."},
            {"Quote",                 "\""},
            {"LoadRemoteMwdMsg1",     "Άνοιγμα απομακρυσμένου μικρόκοσμου"},
            {"LoadRemoteMwdMsg2",     "Web site"},
            {"WebSiteLocalDirName",   "Δικτυακοί τόποι"},
            {"Restore",               "Αποκατάσταση"},
            {"Minimize",              "Απόκρυψη"},
            {"MinimizeAll",           "Απόκρυψη όλων"},
            {"BarOffAll",             "Απόκρυψη μπαρών"},
            {"BarOnAll",                    "Εμφάνιση μπαρών"},
            {"Maximize",                    "Μεγιστοποίηση"},
            {"Close",                       "Κλείσιμο"},
            {"BarOff",                      "Μπάρα ορατή"},
            {"OK",                          "Εντάξει"},
            {"Cancel",                      "Άκυρο"},
            {"Apply",                       "Εφαρμογή"},
            {"ShowComponentBar",            "Εμφάνιση μπάρας ψηφίδων"},
            {"HideComponentBar",            "Απόκρυψη μπάρας ψηφίδων"},
            {"ESlateHelpTitle",             "Βοήθεια Αβακίου"},
            {"About",                       "Περί του Αβακίου"},
            {"Customizer",                  "Προσαρμοστής"},
            {"Customizer1",                 "Ο προσαρμοστής δεν είναι ορατός. Ένας χρήσιμος προσαρμοστής πρέπει οπωσδήποτε να είναι ορατός."},
            {"Customizer2",                 "Ο συγκεκριμένος προσαρμοστής δεν υλοποιεί το \"java.beans.Customizer\" interface."},
            {"Customizer3",                 "Αδύνατη η αρχικοποίηση του προσαρμοστή"},
            {"ComponentEditorTitle",        "Διαχείριση ψηφίδων"},
            {"Loading1",                    "Αρχικοποίηση μικρόκοσμου..."},
            {"Loading2",                    "Εκκίνηση ψηφίδας "},
            {"Saving1",                     "Αποθήκευση μικρόκοσμου..."},
            {"View",                        "Όψη"},
            {"ViewDefined",                 "Καταγραφή όψης"},
            {"Loading icons",               "Ανάκτηση εικονιδίων ψηφίδων. Παρακαλώ περιμένετε..."},
            {"ComponentPins",               "Σύνδεσμοι"},
            {"NativeL&F",                   "Τρέχουσας πλατφόρμας"},
            {"JavaL&F",                     "Metal"},
            {"Microworld",                  "Μικρόκοσμος"},
            {"?",                           ";"},
////nikosM
            {"OnServer",                    " στον "},
////nikosM end
            {"PrintErrorMsg1",              "Δεν στάθηκε δυνατή η εκτύπωση. Ο κατάλογος \"bin\" της εγκατάστασης του Αβακίου δεν υπάρχει."},
            {"PrintErrorMsg2",              "Δεν στάθηκε δυνατή η εκτύπωση. Το εκτελέσιμο αρχείο"},
            {"PrintErrorMsg3",              "δεν υπάρχει στον κατάλογο \"bin\" της εγκατάστασης του Αβακίου."},
            {"ErrorSound",                  "Λάθος"},
            {"InfoSound",                   "Ειδοποίηση"},
            {"QuestionSound",               "Ερώτηση"},
            {"PlugSound",                   "Σύνδεση συνδέσμων"},
            {"UnplugSound",                 "Αποσύνδεση συνδέσμων"},
            {"StartSound",                  "Έναρξη Αβακίου"},
            {"EndSound",                    "Κλείσιμο Αβακίου"},
            {"ComponentNewSound",           "Δημιουργία ψηφίδας"},
            {"ComponentShownSound",         "Εμφάνιση ψηφίδας"},
            {"ComponentHiddenSound",        "Απόκρυψη ψηφίδας"},
            {"ComponentClosedSound",        "Κλείσιμο ψηφίδας"},
            {"MwdOpenedSound",              "Άνοιγμα μικρόκοσμου"},
            {"MwdClosedSound",              "Κλείσιμο μικρόκοσμου"},
            {"ViewChangedSound",            "Αλλαγή όψης μικρόκοσμου"},
            {"ComponentActivatedSound",     "Ενεργοποίηση ψηφίδας"},
            {"ComponentMaximizedSound",     "Μεγιστοποίηση ψηφίδας"},
            {"MicroworldLockedException",   "O μικρόκοσμος είναι κλειδωμένος και δεν είναι δυνατή η αλλαγή των ρυθμίσεών του"},
            {"Microworld current view",     "Τρέχουσα όψη μικρόκοσμου"},
            {"SaveComponent",               "Αποθήκευση ψηφίδας"},
            {"LoadComponent",               "Ανάκτηση ψηφίδας"},
            {"CreatingMwdBackup",           "Δημιουργία αντιγράφου ασφαλείας μικρόκοσμου"},
            {"BackupCopy",                  "ΑντίγραφοΜικρόκοσμου"},
            {"MicroworldSaveTimer",         "Aποθήκευση μικρόκοσμου"},
            {"MicroworldLoadTimer",         "Ανάκτηση μικρόκοσμου"},
            {"MicroworldCloseTimer",        "Κλείσιμο μικρόκοσμου"},
            {"ViewSwitchTimer",             "Αλλαγή όψης"},
            {"MicroworldLoadGroup",         "Ομάδα μετρητών φορτώματος μικρόκοσμου"},
            {"FileReadTimer",               "Ανάγνωση αρχείου μικρόκοσμου"},
            {"ComponentInstantiationTimer", "Εκκίνηση ψηφίδων"},
            {"HandleRegistrationTimer",     "Registration handles ψηφίδων"},
            {"FrameIconCreationTimer",      "Δημιουργία παραθύρων και εικονιδίων"},
            {"ScriptSoundLoadTimer",        "Φόρτωμα scripts & ήχων"},
            {"MwdPropertiesRestoreTimer",   "Αποκατάσταση ιδιοτήτων μικροκόσμου"},
            {"MwdLoadedListenerTimer",      "Γεγονός ανοίγματος μικρόκοσμου"},
            {"loadmwtip",					"<html><strong>Πατήστε:</strong><ul><li>Ctrl+L, για να ανοίξετε ένα μικρόκοσμο που βρίσκεται στο PC σας</li><li>Ctrl+R, για να ανοίξετε ένα μικρόκοσμο που βρίσκεται σε απομακρυσμένο εξυπηρετητή</li></ul></html>"},
    };
}
