package gr.cti.eslate.base.container;

import java.util.ListResourceBundle;


public class MicroworldPropertiesDialogBundle_el_GR extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"Title",                           "Ιδιότητες μικρόκοσμου"},
        {"OK",                              "Εντάξει"},
        {"Cancel",                          "Άκυρο"},
        {"Apply",                           "Εφαρμογή"},
        {"Profiles",                        "Προφίλ ρυθμίσεων"},
        {"MicroworldInfo",                  "Πληροφορίες"},
        {"MicroworldBackground",            "Εμφάνιση"},
        {"ControlBar",                      "Μπάρα ελέγχου ψηφίδων"},
        {"ComponentPanel",                  "Ψηφίδες"},
        {"MicroworldPanel",                 "Μικρόκοσμος"},
        {"Metadata",                        "Πληροφορίες"},
        {"Settings",                        "Ρυθμίσεις"},
        {"Microworld Settings",             "Ρυθμίσεις μικρόκοσμου"},
        {"UI Settings",                     "Ρυθμίσεις UI"},
        {"View Settings",                   "Ρυθμίσεις όψεων"},
        {"Storage Settings",                "Ρυθμίσεις αποθήκευσης"},
        {"Popup-Menus settings",            "Ρυθμίσεις αναδυόμενων μενού"},
        {"Component mgmt settings",         "Ρυθμίσεις Διαχειριστή Ψηφίδων"},
        {"View Based Settings",             "Ρυθμίσεις σε επίπεδο όψης"},
        {"Microworld View Based Settings",  "Ρυθμίσεις μικρόκοσμου"},
        {"Component View Based Settings",   "Ρυθμίσεις ψηφίδων"},
        {"View",                            "Όψη"},
        {"Microworld UI View Based Settings",         "Ρυθμίσεις UI"},
        {"Microworld Print View Based Settings",      "Ρυθμίσεις εκτύπωσης"},
        {"Microworld UI Menus View Based Settings",   "Ρυθμίσεις μενού"},
        {"Microworld UI Desktop View Based Settings", "Ρυθμίσεις επιφάνειας εργασίας"},
        {"Component Bar View Based Settings",         "Ρυθμίσεις μπάρας ψηφίδων"},
        {"Component Bar Button View Based Settings",  "Ρυθμίσεις κουμπιών μπάρας"},
        {"eslateComponentBarMenuEnabled",     "Αναδυόμενο μενού καταλόγου ψηφίδων μικρόκοσμου ενεργό"},
        {"eslateComponentBarMenuEnabledTip",  "Ρυθμίζει τη δυνατότητα εμφάνισης αναδυόμενου μενού με δεξί click <br>στα εικονίδια του κεντρικού καταλόγου ψηφίδων του μικρόκοσμου"},
        {"componentBarMenuEnabled",         "Αναδυόμενο μενού μπάρας ψηφίδων ενεργό"},
        {"componentBarMenuEnabledTip",      "Ρυθμίζει τη δυνατότητα εμφάνισης αναδυομενου μενού <br>με δεξί click στην μπάρα της ψηφίδας"},
        {"mwdPopupEnabled",                 "Αναδυόμενο μενού μικρόκοσμου ενεργό"},
        {"mwdPopupEnabledTip",              "Ρυθμίζει τη δυνατότητα εμφάνισης αναδυομενου μενού <br>με δεξί click στην επιφάνεια εργασίας"},
        {"mwdLayerMgmtAllowed",             "Επιτρέπεται η διαχείριση των επιπέδων του μικρόκοσμου"},
        {"mwdLayerMgmtAllowedTip",          "Ρυθμίζει την δυνατότητα αλλαγής στα επίπεδα του μικρόκοσμου"},
        {"viewMgmtAllowed",                 "Επιτρέπεται η διαχείριση των όψεων του μικρόκοσμου"},
        {"viewMgmtAllowedTip",              "Ρυθμίζει τη δυνατότητα επέμβασης στις όψεις του μικρόκοσμου"},
        {"gridMgmtAllowed",                 "Επιτρέπεται η διαχείριση του πλέγματος του μικρόκοσμου"},
        {"gridMgmtAllowedTip",              "Ρυθμίζει τη δυνατότητα επέμβασης στις ρυθμίσεις πλέγματος του μικρόκοσμου"},
        {"eslateOptionMgmtAllowed",         "Διάλογος ρυθμίσεων Αβακίου ενεργός"},
        {"eslateOptionMgmtAllowedTip",      "Ρυθμίζει την δυνατότητα πρόσβασης στις ρυθμίσεις του Αβακίου, <br>μέσω του σχετικού διαλόγου"},
        {"componentPropertyMgmtAllowed",    "Επιτρέπεται η διαχείριση των ιδιοτήτων των ψηφίδων"},
        {"componentPropertyMgmtAllowedTip", "Ρυθμίζει την πρόσβαση στις ιδιότητες των ψηφίδων του μικρόκοσμου <br>μέσω του Διαχειριστή Ψηφίδων"},
        {"componentEventMgmtAllowed",       "Επιτρέπεται η διαχείριση των γεγονότων των ψηφίδων"},
        {"componentEventMgmtAllowedTip",    "Ρυθμίζει την πρόσβαση στα γεγονότα των ψηφίδων του μικρόκοσμου <br>μέσω του Διαχειριστή Ψηφίδων"},
        {"componentSoundMgmtAllowed",       "Επιτρέπεται η διαχείριση των ήχων των ψηφίδων"},
        {"componentSoundMgmtAllowedTip",    "Ρυθμίζει την πρόσβαση στους ήχους των ψηφίδων του μικρόκοσμου <br>μέσω του Διαχειριστή Ψηφίδων"},
        {"mwdLAFChangeAllowed",             "Επιτρέπεται η αλλαγή του θέματος περιβάλλοντος του μικρόκοσμου"},
        {"mwdLAFChangeAllowedTip",          "Αφορά τη δυνατότητα αλλαγής του θέματος περιβάλλοντος του μικρόκοσμου"},
        {"eslateComponentBarEnabled",       "Κατάλογος ψηφίδων ενεργός"},
        {"eslateComponentBarEnabledTip",    "Ρυθμίζει τη δυνατότητα εμφάνισης του κεντρικού καταλόγου <br>ψηφίδων του μικρόκοσμου"},
        {"consolesAllowed",                 "Κονσόλες ενεργές"},
        {"consolesAllowedTip",              "Ρυθμίζει τη δυνατότητα εμφάνισης των κονσολών"},
        {"componentNameChangeAllowed",      "Επιτρέπεται η αλλαγή του ονόματος των ψηφίδων"},
        {"componentNameChangeAllowedTip",   "Ρυθμίζει τη δυνατότητα αλλαγής του ονόματος των ψηφίδων"},
        {"microworldNameUserDefined",       "Το όνομα του μικρόκοσμου καθορίζεται από το χρήστη"},
        {"microworldNameUserDefinedTip",    "Ρυθμίζει το αν ο μικρόκοσμος θα παίρνει το όνομα του αρχείου <br>από το οποίο προέρχεται ή όνομα που δίνεται από το χρήστη"},
        {"componentInstantiationAllowed",   "Επιτρέπεται η δημιουργία νέων ψηφίδων"},
        {"componentInstantiationAllowedTip","Ρυθμίζει το αν επιτρέπεται η δημιουργία νέων ψηφίδων στον μικρόκοσμο"},
        {"componentRemovalAllowed",         "Επιτρέπεται η διαγραφή ψηφίδων"},
        {"componentRemovalAllowedTip",      "Ρυθμίζει τη δυνατότητα διαγραφής ψηφίδων από τον μικρόκοσμο"},
        {"mwdNameChangeAllowed",            "Επιτρέπεται η αλλαγή ονόματος του μικρόκοσμου"},
        {"mwdNameChangeAllowedTip",         "Ρυθμίζει την δυνατότητα  αλλαγής του ονόματος του μικρόκοσμου από τον χρήστη, <br>εφόσον ο μικρόκοσμος δεν παίρνει το όνομα του αρχείου του"},
        {"performanceMgrActive",            "Μετρητής απόδοσης μικρόκοσμου ενεργός"},
        {"performanceMgrActiveTip",         "Ρυθμίζει τον αν λαμβάνονται μετρήσεις απόδοσης για τον μικρόκοσμο"},
        {"mwdStorageAllowed",               "Επιτρέπεται η αποθήκευση μικρόκοσμου"},
        {"mwdStorageAllowedTip",            "Ρυθμίζει τη δυνατότητα αποθήκευσης του μικρόκοσμου"},
        {"mwdAutoBackupEnabled",            "Μηχανισμός αυτόματης λήψης αντιγράφου ασφαλείας μικρόκοσμου ενεργός"},
        {"mwdAutoBackupEnabledTip",         "Ρυθμίζει το αν το Αβάκιο θα κρατά αντίγραφο ασφαλείας κάθε φορά<br>που ένας μικρόκοσμος αποθηκεύεται"},
        {"storeSkinOnAPerViewBasis",        "Επιτρέπονται πολλαπλά skins ψηφίδων (skin ανά όψη)"},
        {"storeSkinOnAPerViewBasisTip",     "Ρυθμίζει τη δυνατότητα να έχουν οι ψηφίδες πολλαπλά skins από όψη σε όψη"},
        {"viewCreationAllowed",             "Επιτρέπεται η δημιουργία νέων όψεων"},
        {"viewCreationAllowedTip",          "Ρυθμίζει τη δυνατότητα δημιουργίας νέων όψεων στον μικρόκοσμο"},
        {"viewRemovalAllowed",              "Επιτρέπεται η διαγραφή όψεων"},
        {"viewRemovalAllowedTip",           "Ρυθμίζει τη δυνατότητα διαγραφής όψεων από τον μικρόκοσμο"},
        {"viewRenameAllowed",               "Eπιτρέπεται η αλλαγή ονόματος όψεων"},
        {"viewRenameAllowedTip",            "Ρυθμίζει τη δυνατότητα αλλαγής ονόματος όψης του μικρόκοσμου"},
        {"viewActivationAllowed",           "Επιτρέπεται η ενεργοποίηση όψεων"},
        {"viewActivationAllowedTip",        "Ρυθμίζει τη δυνατότητα ενεργοποίησης όψεων του μικρόκοσμου"},
        {"plugConnectionChangeAllowed",     "Επιτρέπεται η (ανα)διαμόρφωση συνδέσμων"},
        {"plugConnectionChangeAllowedTip",  "Ρυθμίζει το αν είναι δυνατό να γίνουν νέες συνάψεις ή να καταστραφούν <br>συνάψεις συνδέσμων μεταξύ των ψηφίδων του μικρόκοσμου"},
        {"mwdBgrdChangeAllowed",            "Επιτρέπεται η διαμόρφωση του υποβάθρου"},
        {"mwdBgrdChangeAllowedTip",         "Ρυθμίζει την πρόσβαση στο υπόβαθρο του μικρόκοσμου"},
        {"menuSystemHeavyWeight",           "Χρήση 'heavyweight' μενού"},
        {"menuSystemHeavyWeightTip",        "Προσφέρει τη δυνατότητα μετατροπής των μενού του Αβακίου σε 'heavyweight'"},
        {"menuBarVisible",                  "Μπάρα μενού Αβακίου ορατή"},
        {"menuBarVisibleTip",               "Ρυθμίζει την ορατότητα μενού του Αβακίου"},
        {"mwdAutoExpandable",               "Αυτόματη επέκταση μικρόκοσμου"},
        {"mwdAutoExpandableTip",            "Καθιστά δυνατή την αυτόματη επέκταση της επιφάνειας του μικρόκοσμου, <br>όταν κάποια ψηφίδα ξεπερνά τα όριά της"},
        {"mwdAutoScrollable",               "Αυτόματη 'κύληση' μικρόκοσμου"},
        {"mwdAutoScrollableTip",            "Ρυθμίζει τη δυνατότητα αυτόματου scrolling της επιφάνειας του Αβακίου, <br>καθώς η ενεργή ψηφίδα μετακινείται εκτός του ορατού τμήματος της επιφάνειας"},
        {"horizontalScrollbarPolicy",       "Εμφάνιση οριζόντιας μπάρας 'κύλησης'"},
        {"horizontalScrollbarPolicyTip",    "Ρυθμίζει την πολιτική εμφάνισης της οριζόντιας μπάρας 'κύλησης'"},
        {"verticalScrollbarPolicy",         "Εμφάνιση κάθετης μπάρας 'κύλησης'"},
        {"verticalScrollbarPolicyTip",      "Ρυθμίζει την πολιτική εμφάνισης της κάθετης μπάρας 'κύλησης'"},
        {"desktopDraggable",                "Κυλιόμενη επιφάνεια εργασίας"},
        {"desktopDraggableTip",             "Ρυθμίζει το αν η επιφάνεια του μικρόκοσμου μπορεί να γίνεται 'drag' <br>από τον χρήση με χρήση του ποντικού"},
        {"mwdResizable",                    "Μεταβαλλόμενο μέγεθος"},
        {"mwdResizableTip",                 "Ρυθμίζει το αν ο μικρόκοσμος θα έχει μεταβαλλόμενο μέγεθος"},
        {"componentsMoveBeyondMwdBounds",   "Επιτρέπεται η μετακίνηση ψηφίδων πέρα από τα όρια του μικρόκοσμου"},
        {"componentsMoveBeyondMwdBoundsTip","Ρυθμίζει τη δυνατότητα μετακίνησης των ψηφίδων πέρα από τα <br>όρια του μικρόκοσμου"},
        {"desktopWidth",                    "Πλάτος"},
        {"desktopWidthTip",                 "Πλάτος μικρόκοσμου"},
        {"desktopHeight",                   "Ύψος"},
        {"desktopHeightTip",                "Ύψος μικρόκοσμου"},
        {"mwdPageSetupAllowed",             "Επιτρέπεται η διαμόρφωση της σελίδας εκτύπωσης"},
        {"mwdPageSetupAllowedTip",          "Ρυθμίζει τη δυνατότητα πρόσβασης στον διάλογο ρυθμίσεων <br>της σελίδας εκτύπωσης"},
        {"mwdPrintAllowed",                 "Επιτρέπεται η εκτύπωση του μικρόκοσμου"},
        {"mwdPrintAllowedTip",              "Ρυθμίζει τη δυνατότητα εκτύπωσης του μικρόκοσμου"},
        {"componentPrintAllowed",           "Επιτρέπεται η εκτύπωση ψηφίδων"},
        {"componentPrintAllowedTip",        "Ρυθμίζει τη δυνατότητα εκτύπωσης ψηφίδων στον μικρόκοσμο"},
        {"componentMinimizeAllowed",        "Επιτρέπεται η απόκρυψη ψηφίδων"},
        {"componentMinimizeAllowedTip",     "Ρυθμίζει τη δυνατότητα απόκρυψης ψηφίδων στον μικρόκοσμο"},
        {"componentMaximizeAllowed",        "Επιτρέπεται η μεγιστοποίηση ψηφίδων"},
        {"componentMaximizeAllowedTip",     "Ρυθμίζει τη δυνατότητα μεγιστοποίησης ψηφίδων στον μικρόκοσμο"},
        {"ensureActiveComponentVisible",    "Ενεργή ψηφίδα πάντα ορατή"},
        {"ensureActiveComponentVisibleTip", "Ρυθμίζει το αν η επιφάνεια εργασίας θα μετακινείται αυτόματα, <br>ώστε η ενεργή ψηφίδα να είναι πάντα ορατή"},
        {"componentActivationMethodChangeAllowed",    "Επιτρέπεται αλλαγή της μεθόδου ενεργοποίησης ψηφίδας"},
        {"componentActivationMethodChangeAllowedTip", "Ρυθμίζει το αν θα επιτρέπεται η αλλαγή της μεθόδου <br>ενεργοποίησης ψηφίδας"},
        {"activeComponentHighlighted",      "Οπτική ένδειξη της ενεργής ψηφίδας"},
        {"activeComponentHighlightedTip",   "Ρυθμίζει το αν θα υπάρχει στον μικρόκοσμο οπτική ένδειξη της <br>ενεργής ψηφίδας"},
        {"outlineDragEnabled",              "Σύρσιμο πλαισίου μόνο"},
        {"outlineDragEnabledTip",           "Ρυθμίζει το αν η ψηφίδα ζωγραφίζεται ενώ μετακινείται μέσα στο μικρόκοσμο"},
        {"controlBarTitleActive",           "Επιτρέπεται η αλλαγή ονόματος ψηφίδας μέσω μπάρας τίτλου"},
        {"controlBarTitleActiveTip",        "Ρυθμίζει το αν θα μπορεί ο χρήστης να μεταβάλει τον τίτλο της ψηφίδας <br>μέσα σπό την μπάρα τίτλου (με Ctrl-click)"},
        {"controlBarsVisible",              "Μπάρα τίτλου ψηφίδας ορατή"},
        {"controlBarsVisibleTip",           "Ρυθμίζει την ορατότητα της μπάρας τίτλου των ψηφίδων του μικρόκοσμου"},
        {"minimizeButtonVisible",           "Πλήκτρο 'Απόκρυψη' ορατό"},
        {"minimizeButtonVisibleTip",        "Ρυθμίζει την ορατότητα του πλήκτρου 'Απόκρυψη' της <br>μπάρας τίτλου των ψηφίδων"},
        {"maximizeButtonVisible",           "Πλήκτρο 'Μεγιστοποίηση' ορατό"},
        {"maximizeButtonVisibleTip",        "Ρυθμίζει την ορατότητα του πλήκτρου 'Μεγιστοποίηση' <br>της μπάρας τίτλου των ψηφίδων"},
        {"closeButtonVisible",              "Πλήκτρο 'Διαγραφή' ορατό"},
        {"closeButtonVisibleTip",           "Ρυθμίζει την ορατότητα του πλήκτρου 'Διαγραφή' της <br>μπάρας τίτλου των ψηφίδων"},
        {"helpButtonVisible",               "Πλήκτρο 'Βοήθεια' ορατό"},
        {"helpButtonVisibleTip",            "Ρυθμίζει την ορατότητα του πλήκτρου 'Βοήθεια' της <br>μπάρας τίτλου των ψηφίδων"},
        {"plugButtonVisible",               "Πλήκτρο 'Σύνδεσμοι' ορατό"},
        {"plugButtonVisibleTip",            "Ρυθμίζει την ορατότητα του πλήκτρου 'Σύνδεσμοι' της <br>μπάρας τίτλου των ψηφίδων"},
        {"infoButtonVisible",               "Πλήκτρο 'Πληροφορίες' ορατό"},
        {"infoButtonVisibleTip",            "Ρυθμίζει την ορατότητα του πλήκτρου 'Πληροφορίες' της <br>μπάρας τίτλου των ψηφίδων"},
        {"resizeAllowed",                   "Μεταβαλλόμενο μέγεθος ψηφίδων"},
        {"resizeAllowedTip",                "Ρυθμίζει το αν οι ψηφίδες έχουν μεταβαλλόμενο μέγεθος"},
        {"moveAllowed",                     "Μεταβαλλόμενη θέση ψηφίδων"},
        {"moveAllowedTip",                  "Ρυθμίζει τη δυνατότητα μετακίνησης των ψηφίδων μέσα στην <br>επιφάνεια εργασίας του Αβακίου"},
        {"ScrollBarAsNeeded",               "ΟΤΑΝ ΧΡΕΙΑΖΕΤΑΙ"},
        {"ScrollBarNever",                  "ΠΟΤΕ"},
        {"ScrollBarAlways",                 "ΠΑΝΤΑ"},
    };
}
