package gr.cti.eslate.base.container;

import java.util.ListResourceBundle;


public class MwdPropertiesDialogBundle extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"Title",                       "Microworld settings"},
        {"ControlBar",                  "Component control bar"},
        {"ComponentPanel",              "Components"},
        {"MicroworldPanel",             "Microworld"},
        {"Metadata",                    "Information"},
        {"ControlBarTitle",             "Component bar settings"},
        {"ComponentPanelTitle",         "Component settings"},
        {"MicroworldGeneralSettings",   "General settings"},
        {"MicroworldSizeSettings",      "Desktop settings"},
        {"OK",                          "OK"},
        {"Cancel",                      "Cancel"},
        {"Apply",                       "Apply"},
        {"ComponentCreationEnabled",    "Allow component creation"},
        {"ComponentRemovalEnabled",     "Allow component removal"},
        {"MwdBackgroundChangeEnabled",  "Allow background change"},
        {"MwdStorageEnabled",           "Allow saving"},
        {"MwdPinViewEnabled",           "Allow Plug editing"},
        {"MwdPopupEnabled",             "Right-click menu enabled"},
        {"MenuBarVisible",              "E-Slate menu bar visible"},
        {"ComponentBarEnabled",         "Component index enabled"},
        {"MicroworldNameUserDefined",   "Use file name as Microworld's title"},
        {"ComponentNameChangeAllowed",  "Allow renaming"},
        {"ResizeAllowed",               "Resizable"},
        {"MoveAllowed",                 "Moveable"},
        {"Frozen",                      "Allow change in 'freeze' state"},
        {"ActivateOnMouseClick",        "Allow activation method change"},
        {"OutlineDrag",                 "Outline drag mode"},
        {"DisplayActiveComponent",      "Visual indication of active component"},
        {"DisplayActiveComponentTip",   "Determines whether the active component will be highlighted in the microworld"},
        {"ActiveFrameVisible",          "Active component always visible"},
        {"ActiveFrameVisibleTip",       "Makes sure that the ESlate desktop scrolls, so that the active component is always visible"},
        {"ComponentBarVisible",         "Component bar visible"},
        {"MinimizeAllowed",             "'Hide' button visible"},
        {"MaximizeAllowed",             "'Maximize' button visible"},
        {"CloseControlEnabled",         "'Remove' button visible"},
        {"PinControlEnabled",           "'Plugs' button visible"},
        {"HelpEnabled",                 "'Help' button visible"},
        {"ComponentInfoEnabled",        "'Info' button visible"},
        {"ComponentRenameThroughBarEnabled", "Name editing enabled"},
        {"Width",                       "Width"},
        {"Height",                      "Height"},
        {"Resizable",                   "Resizable"},
        {"AutoExpandable",              "Auto-expandable"},
        {"AutoScrollable",              "Auto-scrollable"},
        {"ExceedBoundaries",            "Components may exceed microworld boundaries"},
        {"DesktopDrag",                 "Drag desktop"},
        {"ScrollBarAsNeeded",           "AS NEEDED"},
        {"ScrollBarNever",              "NEVER"},
        {"ScrollBarAlways",             "ALWAYS"},
        {"VerticalSP",                   "Vertical scroll bar display policy"},
        {"HorizontalSP",                 "Horizontal scroll bar display policy"},
        {"WidthTip",                    "Microworld width"},
        {"HeightTip",                   "Microworld height"},
        {"ResizableTip",                "Allow microworld resize"},
        {"AutoExpandableTip",           "Microwold expands whenever a component is moved beyond its borders"},
        {"AutoScrollableTip",           "Microwold scrolls whenever a component is moved beyond its borders"},
        {"DesktopDragTip",              "Enable microworld scroll by dragging the desktop"},
        {"ExceedBoundariesTip",         "Allow components to move beyond the microworld's borders"},
        {"VerticalSPTip",               "Vertical scroll bar display policy"},
        {"HorizontalSPTip",             "Horizontal scroll bar display policy"},
        {"MenuSystemHeavyWeight",       "Use heavyweight menus"},
        {"StoreSkinsPerView",           "Store component skins on per view basis"},
        {"StoreSkinsPerViewTip",        "The component skins may be different from one view to another"},
        {"Profiles",                    "Setting profiles"},

        {"MwdPrintAllowed",             "Microworld printing"},
        {"MwdPageSetupAllowed",         "Microworld page set-up"},
        {"ViewCreationAllowed",         "View creation"},
        {"ViewRemovalAllowed",          "View removal"},
        {"ViewRenameAllowed",           "View renaming"},
        {"ViewActivationAllowed",       "View activation"},
        {"ViewMgmtAllowed",             "View manager"},
        {"ESlateOptionMgmtAllowed",     "ESlate options adjustment"},
        {"ComponentPropertyMgmtAllowed","Component property editing"},
        {"ComponentEventMgmtAllowed",   "Component event editing"},
        {"ComponentSoundMgmtAllowed",   "Component sound editing"},
        {"MwdLAFChangeAllowed",         "Look and Feel adjustment"},
        {"ConsolesAllowed",             "ESlate consoles active"},
        {"ESlateComponentBarMenuEnabled", "ESlate component bar pop-up menu active"},
        {"ESlateComponentBarEnabled",   "ESlate component bar active"},
        {"MwdNameChangeAllowed",        "Microworld renaming"},
        {"ComponentNameChangeAllowed",  "Component renaming"},
        {"ComponentBarMenuEnabled",     "Component title bar pop-up menu active"},
        {"MwdLayerMgmtAllowed",         "Layer management"},
        {"GridMgmtAllowed",             "Desktop grid management"},
        {"ComponentMinimizeAllowed",    "Component hiding enabled"},
        {"ComponentMaximizeAllowed",    "Component maximizing allowed"},
    };
}
