package gr.cti.eslate.imageEditor;

import java.util.ListResourceBundle;

public class IEBundle_el_GR extends ListResourceBundle {
	public Object[][] getContents() {
		return contents;
	}

	static final Object[][] contents= {
        {"Error",               "Λάθος "},
        {"Cancel",              "Άκυρο "},
        {"okDialog",            "Εντάξει "},
        {"IconEditorMsg1",      "Αποθήκευση εικόνας "},
        {"IconEditorMsg2",      "Εικόνα "},
        {"IconEditorMsg3",      "Άνοιγμα εικόνας "},
        {"IconEditorMsg4",      "Πολύ μεγάλη εικόνα (w: "},
        {"IconEditorMsg5",      " h: "},
        {"IconEditorMsg6",      ") για να χωρέσει στον διαχειριστή εικόνων "},
        {"IconEditorMsg7",      "Σβήσιμο "},
        {"IconEditorMsg8",      "Διαχειριστής εικονιδίων "},
        {"IconEditorMsg9",      "Χρώμα στυλού "},
        {"IconEditorMsg10",     "Επιλογέας χρωμάτων "},
        {"IconEditorMsg11",     "Χρώμα υποβάθρου "},
        {"IconEditorMsg12",     "Επιλογή "},
        {"IconEditorMsg13",     "Ζωγράφισε "},
        {"IconEditorMsg14",     "Σβήσιμο επιλογής "},
        {"IconEditorMsg15",     "Γέμισμα επιλογής "},
        {"IconEditorMsg16",     "Αντιστροφή επιλογής "},
        {"IconEditorMsg17",     "Άνοιγμα "},
        {"IconEditorMsg18",     "Αποθήκευση "},
        {"IconEditorMsg19",     "Δεν είναι δυνατή η δημιουργία της εικόνας. Το αρχείο \""},
        {"IconEditorMsg20",     "\" δεν υπάρχει "},
        {"IconEditorMsg21",     "Επιλογή χρώματος από το εικονίδιο "},
        {"IconEditorMsg22",     "Αδύνατο το άνοιγμα του εικονιδίου στον διαχειριστή εικονιδίων. Οι διαστάσεις του εικονιδίου είναι μεγαλύτερες από 32x32 "},
        {"IconEditorMsg23",     "Πλέγμα "},
        {"IconEditorMsg24",     "Οχι πλέγμα "},
        {"IconEditorMsg25",     "Μέγεθος κελιού "},
        {"IconEditorMsg26",     "Γόμα "},
        {"IconEditorMsg27",     "Μολύβι "},
        {"IconEditorMsg28",     "Πάρε χρώμα προσκηνίου "},
        {"IconEditorMsg29",     "Πάρε χρώμα υποβάθρου "},
        {"IconEditorMsg30",     "Μετακίνηση "},
        {"IconEditorMsg31",     "Μέγεθος εικόνας "},
        {"IconEditorMsg32",     "Μεγέθυνση "},
        {"IconEditorMsg33",     "Σμίκρυνση "},
        {"IconEditorMsg34",     "Μαγικό Ραβδί "},
        {"IconEditorMsg35",     "Νέα εικόνα "},
        {"pin",                 "Εικονίδιο"},
        {"componame",           "Επεξεργαστής Εικόνων"},
        {"IconEditorMsg36",     "Στείλε εικόνα "},
        {"big",                 "Πολύ μεγάλη εικόνα "},
        {"alert",               "Προσοχή !! "},
        {"alertPalette",        "Προσοχή !! Η παλέττα εικονιδίων άλλαξε..."},
        {"alertColorPalette",   "Προσοχή !! Η παλέττα χρωμάτων άλλαξε..."},
        {"saving",              "Θέλετε να αποθηκεύσετε την εικόνα; "},
        {"clickto",             "Πατήστε για"},
        {"preview",             "Προεπισκόπηση"},
        {"imgprev",             "Προεπισκόπηση εικόνας"},
        {"loading",             "Φόρτωμα Εικόνας..."},
        {"IconChooser",         "Επιλογέας εικονιδίων"},
        {"openIconPalette",         "Άνοιγμα παλέττας Εικονιδίων..."},
        {"newIconPalette",          "Νέα παλέττα Εικονιδίων..."},
        {"saveIconPalette",         "Αποθήκευση παλέττας Εικονιδίων..."},
        {"wannaSavePalette",      "Θέλετε να αποθηκεύσετε την παλέττα εικονιδίων σε αρχείο?"},
        {"wannaSaveColorPalette",   "Θέλετε να αποθηκεύσετε την παλέττα χρωμάτων σε αρχείο?"},
        {"newColorPalette",         "Νέα παλέττα Χρωμάτων... "},
        {"openColorPalette",         "Άνοιγμα παλέττας Χρωμάτων..."},
        {"saveColorPalette",         "Αποθήκευση παλέττας Χρωμάτων..."},

        {"palette",             "Παλέττα"},
        {"saveThisPalette?",     "   Θελετε να αποθηκεύσετε την παλέττα; "},
        {"yes",                 "Ναι"},
        {"no",                 "Όχι"},
        {"addtopalette",       "Προσθήκη στην παλέττα"},
        {"cPalette",       "Παλέττα Χρωμάτων"},
        {"iPalette",       "Παλέττα Εικονιδίων"},
        {"colorPalette",       "Χρώματα"},
        {"iconPalette",       "Εικονίδια"},
        {"noimage",           "Δεν υπάρχει αυτό το αρχείο "},
        {"cannotLoad1",           "Η εικόνα "},
        {"cannotLoad2",           " δεν μπορεί να ανοίξει!! "},
        {"line",              "Γραμμή "},
        {"rectangle",         "Ορθογώνιο "},
        {"ellipse",           "Έλλειψη "},
        {"poly",           		"Πολυγραμμή "},
        {"file",              "Αρχείο "},
        {"new",              "Νέο... "},
        {"openM",              "Άνοιγμα... "},
        {"saveM",              "Αποθήκευση "},
        {"printPr",         "Προεπισκόπηση Εκτύπωσης... "},
        {"print",         		"Εκτύπωση... "},
        {"exit",              "Έξοδος "},
        {"image",         		"Εικόνα "},
        {"imsize",         "Μέγεθος Εικόνας... "},
        {"clearim",         "Καθαρισμός Εικόνας... "},
        {"grid",         "Πλέγμα... "},
        {"zoom",         "Μεγέθυνση... "},
        {"initiallevel",         "Αρχικό επίπεδο "},
        {"tools",         "Εργαλεία "},
        {"cropText",         "Αποκοπή τμήματος "},
        {"undoText",         "Ακύρωση "},
        {"copyText",         "Αντιγραφή "},
        {"cutText",         "Αποκοπή "},
        {"pasteText",         "Επικόλληση "},
        {"jpggif",         "Αποθήκευση σαν .gif(Ναι) ή .jpg(Oχι);"},
        {"ChooseType",      "Επιλογή τύπου αποθήκευσης"},
        {"ok",               "Εντάξει"},
        {"cancel",           "Άκυρο"},
        {"select",           "Επιλογή μεγέθους εικόνας"},
        {"xdim",             "Πλάτος: "},
        {"ydim",             "Ύψος: "},
        {"fFill",             "Γέμισμα "},
        {"palettes",             "Παλέττες "},
        {"totalColors",             " Αριθμός συνολικών χρωμάτων "},
        {"customColors",             " Αριθμός μεταβλητών χρωμάτων "},
        {"totalIcons",             " Αριθμός συνολικών εικονιδίων "},
        {"edit",                  "Επεξεργασία "},
        {"pencilMode",         " Λειτουργία Μολυβιού "},
        {"lineMode",         " Λειτουργία Γραμμής "},
        {"rectMode",         " Λειτουργία Ορθογωνίου "},
        {"ellMode",         " Λειτουργία Έλλειψης "},
        {"polyMode",         " Λειτουργία Πολυγραμμής "},
        {"rubberMode",         " Λειτουργία Γόμας "},
        {"wandMode",         " Λειτουργία Μαγικού Ραβδιού "},
        {"panMode",         " Λειτουργία Μετακίνησης "},
        {"pickMode",         " Λειτουργία λήψης χρώματος "},
        {"flatMode",         " Λειτουργία γεμίσματος "},
        {"selectMode",         " Λειτουργία Επιλογής "},
        {"remSelMode",         " Λειτουργία Αφαίρεσης Επιλογής "},
        {"addSelMode",         " Λειτουργία Προσθήκης Επιλογής "},
        {"imSize",         " Μέγεθος Εικόνας:  "},
        {"cell",         " Σημείο:  "},
        {"pleasewait",         " Παρακαλώ περιμένετε...  "},
        {"noflatMode",         " Δεν επιτρέπεται γέμισμα εδώ! "},
        {"SaveIm",             "Θέλετε να αποθηκεύσετε την εικόνα;"},
        {"warnClose",          "Προσοχή! Η ψηφίδα επεξεργαστής εικόνων κλείνει..."},
	};
}
