package gr.cti.eslate.database.engine;

import java.util.ListResourceBundle;


public class CTableResourceBundle extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"Integer",         "Integer"},
        {"Alphanumeric",    "Alphanumeric"},
        {"Number",          "Number"},
        {"Double",          "Number"},
        {"Image",           "Image"},
        {"URL",             "URL"},
        {"Boolean",         "Boolean"},
        {"Date",            "Date"},
        {"Time",            "Time"},
        {"true",            "true"},
        {"false",           "false"},
        {"CTableMsg1",      "No name was provided for the new field"},
        {"CTableMsg2",      "\" not defined. Another field with the same name is already defined"},
        {"CTableMsg3",      "Cannot add a key field into an non-empty table."},
        {"CTableMsg4",      "\" not defined. "},
        {"CTableMsg5",      "\" not defined. A key field cannot be added to a non-empty table"},
        {"CTableMsg6",      "Cannot edit the formula of field \""},
        {"CTableMsg7",      "\", because this field does not exist"},
        {"CTableMsg8",      "You haven't specified a formula for field \""},
        {"CTableMsg9",      "No closing square bracket(]) found"},
        {"CTableMsg10",     "Invalid formula \""},
        {"CTableMsg11",     "Invalid integer number: "},
        {"CTableMsg12",     "Invalid double number: "},
        {"CTableMsg13",     "Only Fields of type \"Number\" or \"Integer\" can be used to calculate field \""},
        {"CTableMsg14",     "\" has \""},
        {"CTableMsg15",     "\" type"},
        {"CTableMsg16",     "Only Fields of type \"Boolean\" can be used to calculate field \""},
        {"CTableMsg17",     "Only Fields of type \"Date\" or \"Integer\" or \"Number\" can be used to calculate field \""},
        {"CTableMsg18",     "Only Fields of type \"Time\" or \"Integer\" can be used to calculate field \""},
        {"CTableMsg19",     "Fields of type \"Image\" or \"Sound\" cannot be used to query field \""},
        {"CTableMsg20",     "Illegal addition of two Date/Time values"},
        {"CTableMsg21",     "Only Fields of type \"URL\" or \"String\" can be used to calculate field \""},
        {"CTableMsg22",     "Fields of type \"Image\" cannot be used in calculated field expressions"},
        {"CTableMsg23",     "Fields of type \""},
        {"CTableMsg24",     "\" cannot be used in calculated field expressions"},
        {"CTableMsg25",     "The new formula alters the data type of the calculated field. There exist other calculated fields which depend on this one, so altering its datatype may invalidate these fields"},
        {"CTableMsg26",     "Cell editing aborted: Null value was calculated for the calculated key field \""},
        {"CTableMsg27",     "Cell editing aborted. Dublicate key value \""},
        {"CTableMsg28",     "\" for calculated field \""},
        {"CTableMsg29",     "Cell editing aborted. Dublicate URL key value \""},
        {"CTableMsg30",     "Null value calculated for field \""},
        {"CTableMsg31",     "Dublicate value \""},
        {"CTableMsg32",     "No field name was supplied"},
        {"CTableMsg33",     "No field exists with name \""},
        {"CTableMsg34",     "\" is not removable"},
        {"CTableMsg35",     "Cannot remove this field. There exist calculated field(s) in this table which depend on the field you want to remove"},
        {"CTableMsg36",     "Unable to remove the field. The field is part of the table's key, so its removal will lead to the deletion of several records, which is not permitted"},
        {"CTableMsg37",     "Record insertion failed: Records cannot be added to this table"},
        {"CTableMsg38",     "No fields defined yet. Record insertion failed!"},
        {"CTableMsg39",     "Record not inserted: "},
        {"CTableMsg40",     " cannot be cast to Date"},
        {"CTableMsg41",     " cannot be cast to Time"},
        {"CTableMsg42",     "Cell wan not changed: \""},
        {"CTableMsg43",     "\" cannot be cast to "},
        {"CTableMsg44",     "Record insertion failed: \""},
        {"CTableMsg45",     "Record insertion failed due to one or more null values in the record's key"},
        {"CTableMsg46",     "Record insertion failed due to dublicate key existense"},
        {"CTableMsg47",     "Records cannot be removed from this table"},
        {"CTableMsg48",     "Invalid record index: "},
        {"CTableMsg49",     "Cannot add a record to a table which contains a non-editable, key field, i.e. field \""},
        {"CTableMsg50",     "This record is invalid"},
        {"CTableMsg51",     "Invalid field index"},
        {"CTableMsg52",     "Invalid cell address. Field index: "},
        {"CTableMsg53",     ", record index: "},
        {"CTableMsg54",     "Invalid cell address. Field name: "},
        {"CTableMsg55",     "Record "},
        {"CTableMsg56",     " or field "},
        {"CTableMsg57",     " is not valid"},
        {"CTableMsg58",     "Cell's value wasn't changed: A null value was supplied for a cell of the field \""},
        {"CTableMsg59",     "\", which belongs to the table's key"},
        {"CTableMsg60",     "Cell was not changed: key value \""},
        {"CTableMsg61",     "\" already exists"},
        {"CTableMsg62",     "The supplied field isn't valid"},
        {"CTableMsg63",     "Invalid cell address. The supplied CTableField is not valid"},
        {"CTableMsg64",     "Invalid record supplied"},
        {"CTableMsg65",     "No field named \""},
        {"CTableMsg66",     "\" exists in the table"},
        {"CTableMsg67",     "Fields of type \"Image\" can not be part of the table's key"},
        {"CTableMsg68",     "\" is already in the table's key"},
        {"CTableMsg69",     "\" cannot be part of the table's key, because it contains empty cells"},
        {"CTableMsg70",     "Unable to remove records in order to establish key: record removal is disabled this table"},
        {"CTableMsg71",     "\" is not part of the table's key"},
        {"CTableMsg72",     "Cannot change the type of field \""},
        {"CTableMsg73",     "\" because it is calculated"},
        {"CTableMsg74",     "\" because it is part of the key"},
        {"CTableMsg75",     "\" because it is not editable"},
        {"CTableMsg76",     "\" because there exist calculated fields, which depend on it"},
        {"CTableMsg77",     "Invalid field data type: "},
        {"CTableMsg78",     "\" has the same data type as the specified one"},
        {"CTableMsg79",     "The type of field \""},
        {"CTableMsg80",     "\" cannot be changed from \"Integer\" to \""},
        {"CTableMsg81",     "Invalid field name \""},
        {"CTableMsg82",     "Field name "},
        {"CTableMsg83",     " is already used by another field in the same table"},
        {"CTableMsg84",     "The title \""},
        {"CTableMsg85",     "\" is already used by another table in the database"},
        {"CTableMsg86",     "The field cannot be deleted, because record removal is not allowed in this table"},
        {"CTableMsg87",     "Unable to remove field. Field removal is not allowed from this table"},
        {"CTableMsg88",     "Unable to add new field. Field addition to this table is not allowed"},
        {"CTableMsg89",     "Data editing is not allowed in this table"},
        {"CTableMsg90",     "Changing the key of the table is not allowed"},
        {"CTableMsg91",     "The hidden attribute of the table cannot be modified"},
        {"CTableMsg92",     "Record insertion failed because one of the key fields of the table is hidden and this table does not display its hidden fields."},
        {"CTableMsg93",     "Unable to add a new record to this table, because it has key and its data cannot be changed"},
        {"CTableMsg94",     "\" cannot be changed to \""},
        {"CTableMsg95",     "\" cannot be changed from \"Double\" to \""},
        {"CTableMsg96",     "\" cannot be changed from \"boolean\" to \""},
        {"CTableMsg97",     "\" cannot be changed from \"URL\" to \""},
        {"CTableMsg98",     "Cannot sort tables on fields of type Image"},
        {"CTableMsg99",     "Unable to add a new record to this table, because the insertion of the previous record has not been completed"},
        {"CTableMsg100",    "Field \""},
        {"CTableMsg101",    "\" does not exist in the table "},
        {"CTableMsg102",    "A table can not have an empty title"},
        {"CTableMsg103",    "The properties of the fields are not editable in table"},
        {"CTableMsg104",    "The name of the table can not be edited"},
        {"CTableMsg105",    "The key of the record is no unique in the table."},
        {"CTableMsg106",     "Null value was supplied for a cell of the field \""},
        {"CTableMsg107",     "\", which belongs to the table's key"},
        {"ImageFieldMsg1",  "Images or changes to images, which are not saved in files, will be lost. Do you want to continue?"},
        {"Table",           "Table"},
        {"Record",          "Record"},
        {"of",              "of"},
        {"Error",           "Error"},
        {"ConstructorTimer","Table constructor"},
        {"LoadTimer",       "Table load"},
        {"SaveTimer",       "Table save"},
        {"InitESlateAspectTimer",        "Table e-Slate part creation"},
        {"FieldMapTimer",                "Table FieldMap read"},
		{"TableView",       "Table View"},
		{"TableViewMsg1",    "\" does not exist in this table view."},
		{"View",                    "View"},
		{"ViewOf",                  "View of"},
    };
}