package gr.cti.eslate.database.query;

import java.util.ListResourceBundle;

public class InfoBundle extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"compo",               "Query component V1.5.5"},
        {"compo1",              "Query"},
        {"part",                "Part of the E-Slate environment (http://E-Slate.cti.gr)"},
        {"design",              "Design idea: G. Tsironis"},
        {"development",         "Development: G. Tsironis (1997-98) G.Dimitrakopoulos (1999-2000)"},
//        {"funding",             "Funding: Project \"ODYSSEAS\" ((EU Support Framework II, Greek Ministry of National Education and Religious Affairs)"},
        {"copyright",           "Copyright Ερευνητικό Ακαδημαϊκό Ινστιτούτο Τεχνολογίας Υπολογιστών-ΕΑ.ΙΤΥ 1993-2008.\nΑνάπτυξη τρέχουσας έκδοσης από τις Conceptum AE και ΕΧΟDUS AE.\nΤο Αβάκιο 2.0 υπόκειται σε διπλή άδεια (dual license), ήτοι ισχύουν οι όροι  της GNU-GPL License και της  L-GPL license.\n\nΕπιτρέπεται η παραγωγή, διανομή και εμπορική εκμετάλλευση κλειστού ή ανοιχτού κώδικα παράγωγων προϊόντων\nβασισμένων στην πλατφόρμα Αβάκιο 2.0 και κάθε επόμενης έκδοσής της καθώς επίσης και να συμπεριλαμβάνεται\nκαι να διανέμεται μαζί με τα προϊόντα αυτά η πλατφόρμα σε μορφή πηγαίου ή/και εκτελέσιμου κώδικα."},
        {"Error",               "Error"},
        {"Warning",             "Warning"},
        {"true",                "true"},
        {"false",               "false"},
        {"OR",                  "OR"},
        {"LowerOR",             "OR"},
        {"AND",                 "AND"},
        {"LowerAND",            "AND"},
        {"NOT",                 "NOT"},
        {"LowerNOT",            "NOT"},
        {"Contains",            "Contains"},
        {"Contained",           "Contained"},
        {"QueryComponentMsg1",  "Display field headers"},
        {"QueryComponentMsg2",  "Execute query"},
        {"QueryComponentMsg3",  "Clear query"},
        {"QueryComponentMsg4",  "Add empty row"},
        {"QueryComponentMsg5",  "Remove row"},
        {"QueryComponentMsg6",  "New selection set"},
        {"QueryComponentMsg7",  "Add to selected set"},
        {"QueryComponentMsg8",  "Remove from selected set"},
        {"QueryComponentMsg9",  "Select from selected set"},
        {"QueryComponentMsg10", "Toggle between QBE and textual query representations"},
        {"QueryComponentMsg11", "Your query could not be moved to the QBE query representation"},
        {"QueryComponentMsg12", "Database"},
        {"QueryComponentMsg13", "No tables in database"},
        {"QueryComponentMsg14", "Unknown operator \""},
        {"QueryComponentMsg15", "Invalid query expression. No closing quote"},
        {"QueryComponentMsg16", "Untitled"},
        {"ResultTable",         "Query results on table \""},
        {"SortUp",		          "Sort Up"},
        {"queryAreaTip",        "The field where you formulate the query "},
        {"fieldListTip",        "<html><font face=Helvetica size=1>Columns of the active table, double <p>click to add it to your query.</font>"},
        {"false",               "false"},
        {"propertyWarning",     "This property is not valid for the current query view"},
        {"propertyWarning2",     "Without the Execution button you want be able to run a query"},
        {"ORtip",               "OR"},
        {"ANDtip",              "AND"},
        {"NOTtip",              "NOT"},
        {"Containstip",         "Contains"},
        {"Containedtip",        "Is contained in"},
        {"Equaltip",            "Equals"},
        {"NotEqualtip",         "Not equals"},
        {"Greatertip",          "Greather than"},
        {"GreaterEqualtip",     "Greater than or equals to"},
        {"Lesstip",             "Less than"},
        {"LessEqualtip",        "Less than or equals to"},
        {"Quotestip",           "Places the selected part of the query in quotes"},
        {"Parenthstip",         "Places the selected part of the query in parenthesis"},
        {"Bracketstip",         "Places the selected part of the query in brackets"},
        {"ConstructorTimer",              "Query constructor"},
        {"LoadTimer",                     "Query load"},
        {"SaveTimer",                     "Query save"},
        {"InitESlateAspectTimer",         "Query e-Slate part creation"},
    };
}
