package gr.cti.eslate.database.engine;

import java.util.ListResourceBundle;

public class DBResourceBundle extends ListResourceBundle {
    public Object [][] getContents() {
        return contents;
    }

    static final Object[][] contents={
        {"Error",           "Error"},
        {"Warning",         "Warning"},
        {"Integer",         "Integer"},
        {"Float",           "Float"},
        {"Alphanumeric",    "Alphanumeric"},
        {"Number",          "Number"},
        {"Double",          "Number"},
        {"Image",           "Image"},
        {"URL",             "URL"},
        {"Boolean",         "Boolean"},
        {"Date",            "Date"},
        {"Time",            "Time"},
        {"IntegerAit",      "Integer"},
        {"AlphanumericAit", "Alphanumeric"},
        {"NumberAit",       "Number"},
        {"DoubleAit",       "Number"},
        {"Error",           "Error"},
        {"Yes",             "Yes"},
        {"No",              "No"},
        {"Cancel",          "Cancel"},
        {"AND",             "and"},
        {"and",             "and"},
        {"OR",              "or"},
        {"or",              "or"},
        {"NOT",             "not"},
        {"not",             "not"},
        {"CONTAINS",        "contains"},
        {"Contains",        "contains"},
        {"contains",        "contains"},
        {"CONTAINED",       "contained"},
        {"Contained",       "contained"},
        {"contained",       "contained"},
        {"true",            "true"},
        {"false",           "false"},
        {"CDatabaseMsg1",   "Unable to open database file \""},
        {"CDatabaseMsg2",   "Unable to open table file \""},
        {"CDatabaseMsg3",   "\". Probably the file is corrupted"},
        {"CDatabaseMsg4",   "Database already open"},
        {"CDatabaseMsg5",   "\". Do you want to open file \""},
        {"CDatabaseMsg6",   "\". Do you want to find it yourself?"},
        {"CDatabaseMsg7",   "\", instead?"},
        {"CDatabaseMsg8",   "Open table"},
        {"CDatabaseMsg9",   "\". Probably the file is corrupted"},
        {"CDatabaseMsg11",  "Error: restored table was not added to the Database, because it does not belong to it"},
        {"CDatabaseMsg12",  "You didn't specify a file name"},
        {"CDatabaseMsg13",  "Directory "},
        {"CDatabaseMsg14",  " does not exist"},
        {"CDatabaseMsg15",  " is not a directory"},
        {"CDatabaseMsg16",  "Invalid file name \""},
        {"CDatabaseMsg17",  "File \""},
        {"CDatabaseMsg18",  "\" does not exist"},
        {"CDatabaseMsg19",  "Char '"},
        {"CDatabaseMsg20",  "' is not a supported delimeter"},
        {"CDatabaseMsg21",  "Cannot read text file \""},
        {"CDatabaseMsg22",  "\" is empty!"},
        {"CDatabaseMsg23",  "\" contains a null field name"},
        {"CDatabaseMsg24",  "\" contains invalid or dublicate field names."},
        {"CDatabaseMsg25",  "\" contains a null field name"},
        {"CDatabaseMsg26",  "Invalid file. Unable to process record #"},
        {"CDatabaseMsg28",  "Invalid file \""},
        {"CDatabaseMsg29",  "\". Record #"},
        {"CDatabaseMsg30",  " contains more fields that the fields of the table(="},
        {"CDatabaseMsg31",  "Cannot close text file \""},
        {"CDatabaseMsg32",  "Cannot open file \""},
        {"CDatabaseMsg33",  "\". Probably incorrect path or invalid file name was specified"},
        {"CDatabaseMsg34",  "Unable to close file \""},
        {"CDatabaseMsg35",  "Saving database"},
        {"CDatabaseMsg36",  "Unable to save database \""},
        {"CDatabaseMsg37",  "\" to file \""},
        {"CDatabaseMsg38",  "Save changes to table \""},
        {"CDatabaseMsg39",  "\" ?"},
        {"CDatabaseMsg40",  "Save table"},
        {"CDatabaseMsg41",  "Save changes to database \""},
        {"CDatabaseMsg42",  "Save database"},
        {"CDatabaseMsg43",  "Unable to save: Insufficient permission to overwrite file \""},
        {"CDatabaseMsg44",  "Saving table"},
        {"CDatabaseMsg45",  "Unable to overwrite: File \""},
        {"CDatabaseMsg46",  "\" is loaded inside table \""},
        {"CDatabaseMsg47",  "\" of this database"},
        {"CDatabaseMsg48",  "Unable to save table \""},
        {"CDatabaseMsg49",  "\" to file \""},
        {"CDatabaseMsg50",  "Revert to original table?"},
        {"CDatabaseMsg51",  "Open table"},
        {"CDatabaseMsg52",  "Unable to open file \""},
        {"CDatabaseMsg53",  "\". Probably it is not a valid \"table\" file"},
        {"CDatabaseMsg54",  "Save table before closing it?"},
        {"CDatabaseMsg55",  "Save table \""},
        {"CDatabaseMsg56",  "\" before closing it?"},
        {"CDatabaseMsg58",  "Overwrite existing file?"},
        {"CDatabaseMsg59",  "Tables \""},
        {"CDatabaseMsg60",  "\" and \""},
        {"CDatabaseMsg61",  "\" don't have any common fields"},
        {"CDatabaseMsg62",  "The common fields between tables \""},
        {"CDatabaseMsg63",  "\" are of type \"Sound\". Join cannot be performed on \"Sound\" fields and on tables that contain \"Sound\" fields"},
        {"CDatabaseMsg64",  "Join("},
        {"CDatabaseMsg65",  "No fields supplied for table \""},
        {"CDatabaseMsg66",  "No operators supplied"},
        {"CDatabaseMsg67",  "You must specify equal number of fields from both tables"},
        {"CDatabaseMsg68",  "Either there are less operators than fields or less fields than operators"},
        {"CDatabaseMsg69",  "Table \""},
        {"CDatabaseMsg70",  "\" is empty!"},
        {"CDatabaseMsg71",  "No field supplied"},
        {"CDatabaseMsg72",  "No comparator supplied"},
        {"CDatabaseMsg73",  "Invalid input parameter data type"},
        {"CDatabaseMsg74",  "Field \""},
        {"CDatabaseMsg75",  "\" does not exist in the table "},
        {"CDatabaseMsg76",  "Fields "},
        {"CDatabaseMsg77",  " and "},
        {"CDatabaseMsg78",  " have incompatible data types"},
        {"CDatabaseMsg79",  "Operator \""},
        {"CDatabaseMsg80",  "\" cannot be used on "},
        {"CDatabaseMsg81",  " fields"},
        {"CDatabaseMsg82",  "Th-join("},
        {"CDatabaseMsg83",  "\" are not identical in structure"},
        {"CDatabaseMsg84",  "Fields \""},
        {"CDatabaseMsg85",  "\" do not have the same data type"},
        {"CDatabaseMsg86",  "Unable to intersect tables that contain only fields of \"Image\" data type"},
        {"CDatabaseMsg87",  "Intersection("},
        {"CDatabaseMsg88",  "Union("},
        {"CDatabaseMsg89",  "Cannot add table to database. "},
        {"CDatabaseMsg90",  "Untitled"},
        {"CDatabaseMsg91",  "Null argument supplied"},
        {"CDatabaseMsg92",  "The table's title is null"},
        {"CDatabaseMsg93",  "The database is protected by \""},
        {"CDatabaseMsg94",  "\". No table can be added to it."},
        {"CDatabaseMsg95",  "\". No table can be removed from it."},
        {"CDatabaseMsg96",  "\". No table can be exported from it."},
        {"CDatabaseMsg97",  "Unable to open database"},
        {"CDatabaseMsg98",  "The title \""},
        {"CDatabaseMsg99",  "\" is already used by another table in the database"},
        {"CDatabaseMsg100", "Table"},
        {"CDatabaseMsg101", "Record addition can not be enabled or disabled for table \""},
        {"CDatabaseMsg102", "Record deletion can not be enabled or disabled for table \""},
        {"CDatabaseMsg103", "Field addition can not be enabled or disabled for table \""},
        {"CDatabaseMsg104", "Field deletion can not be enabled or disabled for table \""},
        {"CDatabaseMsg105", "Field re-ordering can not be enabled or disabled for table \""},
        {"CDatabaseMsg106", "Key editability can not be enabled or disabled for table \""},
        {"CDatabaseMsg107", "Hidden field display can not be enabled or disabled for table \""},
        {"CDatabaseMsg108", "The editability of the data of the table \""},
        {"CDatabaseMsg109", "The visibility state of the table \""},
        {"CDatabaseMsg110", "\" can not change"},
        {"CDatabaseMsg111", "The editability of the data of the field \""},
        {"CDatabaseMsg112", "\" of the table \""},
        {"CDatabaseMsg113", "Deletion can not be enabled or disabled for the field \""},
        {"CDatabaseMsg114", "Data type change can not be enabled or disabled for the field \""},
        {"CDatabaseMsg115", "'Calculated' attribute change can not be enabled or disabled for the field \""},
        {"CDatabaseMsg116", "'Key' attribute change can not be enabled or disabled for the field \""},
        {"CDatabaseMsg117", "Visibility change can not be enabled or disabled for the field \""},
        {"CDatabaseMsg118", "Formula editability can not be enabled or disabled for the field \""},
        {"CDatabaseMsg119", "Unable to rename table \""},
        {"CDatabaseMsg120", "\". The name \""},
        {"CDatabaseMsg121", "\" is already used in database \""},
        {"CBooleanOperandExpressionMsg1",   "Wrong operand expression \""},
        {"CBooleanOperandExpressionMsg2",   ". Parenthesis are not matching"},
        {"CBooleanOperandExpressionMsg3",   "Invalid operand expression. No closing '\"'"},
        {"CBooleanOperandExpressionMsg4",   "Unable to evaluate expression: "},
        {"CBooleanOperandExpressionMsg5",   "\" cannot be cast to Boolean"},
        {"CBooleanOperandExpressionMsg6",   "Wrong operand expression. Invalid comparator \""},
        {"CBooleanOperandExpressionMsg7",   "Invalid operand expression \""},
        {"CBooleanOperandExpressionMsg8",   "\" . No closing '\"'"},
        {"CImageIconMsg1",  "Unable to create Image. File \""},
        {"CImageIconMsg2",  "\" does not exist"},
        {"CDateOperandExpressionMsg1",      "Invalid formula \""},
        {"CDateOperandExpressionMsg2",      "\". Integer fields should be followed by one of characters 'd', 'm' or 'y' in Date calculated field formulas"},
        {"CDateOperandExpressionMsg3",      "\". Integer fields should be followed by one of characters 'h' or 'm' in time calculated field formulas"},
        {"CDateOperandExpressionMsg4",      "\". Constants in date calculated field formulas should have the format <integer_value>x, where x is one of {'d', 'm', 'y'} characters"},
        {"CDateOperandExpressionMsg5",      "Unable to evaluate expression \""},
        {"CDateOperandExpressionMsg6",      "\" cannot be cast to Time"},
        {"CDateOperandExpressionMsg7",      "\". Constants in time calculated field formulas should have the format <integer_value>x, where x is one of {'h', 'm'} characters"},
        {"CDateOperandExpressionMsg8",      "Invalid date expression \""},
        {"CDateOperandExpressionMsg9",      "Invalid operand \""},
        {"CDateOperandExpressionMsg10",     "\". Cannot add two Date/Time operands"},
        {"CDateOperandExpressionMsg11",     "\". Cannot add operands \""},
        {"CDateOperandExpressionMsg12",     "\" add \""},
        {"CDateOperandExpressionMsg13",     "Invalid operand expression"},
        {"CDateOperandExpressionMsg14",     "Cannot add two Date/Time operands"},
        {"CDoubleNumberFormatMsg1",         "\" cannot be cast to Number"},
        {"ElementaryLogicalExceptionMsg1",  "Unaccepted operand: "},
        {"ElementaryLogicalExceptionMsg2",  "Incorrect formatted date. '*' can only be used in the place of days, months, years and not inside them"},
        {"ElementaryLogicalExceptionMsg3",  "Invalid type: \""},
        {"ElementaryLogicalExceptionMsg4",  "Incorrect formatted time. '*' can only be used in the place of minutes and hours and not inside them"},
        {"ElementaryLogicalExceptionMsg5",  "Invalid comparator \""},
        {"ElementaryLogicalExceptionMsg6",  "\". Formatted operands can only be used with the \"=\" comparator"},
        {"ElementaryLogicalExceptionMsg7",  "Operator \""},
        {"ElementaryLogicalExceptionMsg8",  "\" cannot be used on "},
        {"ElementaryLogicalExceptionMsg9",  " fields"},
        {"FieldELEMsg1",    "URL field \""},
        {"FieldELEMsg2",    "\" can only be queried against a field of type \"URL\" or \"String\""},
        {"FieldELEMsg3",    "Only Fields of type \"Number\" or \"Integer\" can be used to query field \""},
        {"FieldELEMsg4",    "\" cannot be queried on other fields"},
        {"FieldELEMsg5",    "Fields of type \"Image\" or \"Sound\" cannot be used to query field \""},
        {"FieldELEMsg6",    "Only Fields of type \"Date\" can be used to query field \""},
        {"FieldELEMsg7",    "Only Fields of type \"Time\" can be used to query field \""},
        {"LogicalExpressionMsg1",           "Unsupported selection mode"},
        {"LogicalExpressionMsg2",           "Invalid query expression. No closing '\"'"},
        {"LogicalExpressionMsg3",           "Invalid query expression. \"(\" do not match \")\""},
        {"ParenthesizedELEMsg1",            "Invalid logical expression. No matching '\"'"},
        {"ParenthesizedELEMsg2",            "Invalid query expression"},
        {"ParenthesizedELEMsg3",            "Invalid query expression. You didn't supply an operand"},
        {"RecordMsg1",      "Record indices cannot have negative values"},
        {"CTableFieldMsg1",                 "The \"Key\" attribute of the field is locked"},
        {"CTableFieldMsg2",                 "The data type of the field is locked"},
        {"CTableFieldMsg3",                 "The \"Editable\" attribute of the field is locked"},
        {"CTableFieldMsg4",                 "The \"Removable\" attribute of the field is locked"},
        {"CTableFieldMsg5",                 "The \"Calculated\" attribute of the field is locked"},
        {"CTableFieldMsg6",                 "The \"Hidden\" attribute of the field is locked"},
        {"CTableFieldMsg7",                 "The \"Formula\" of the calculated field is locked"},
        {"Database1",                       ". Database \""},
        {"DBLocked",                        "\" is locked."},
        {"Database",                        "Database"},
        {"Table",                           "Table"},
        {"ImportTable",                     "Import table"},
        {"SaveDB",                          "The database has changed. Do you want to save the changes?"},
        {"WarnClose",                       "Warning! Closing Database component..."},
        {"ConstructorTimer",                "DBase constructor"},
        {"LoadTimer",                       "DBase load"},
        {"SaveTimer",                       "DBase save"},
        {"InitESlateAspectTimer",           "DBase e-Slate part creation"},
        {"FieldMapTimer",                   "DBase FieldMap read"},
    };
}