package gr.cti.eslate.mapModel;

import java.util.ListResourceBundle;

/**
 * Creator Bundle.
 * <P>
 *
 * @author	Giorgos Vasiliou
 * @version	3.0.0, 24-Jan-2000
 */
public class BundleCreator extends ListResourceBundle {
	public Object [][] getContents() {
		return contents;
	}

	static final Object[][] contents={
		{"title",           "Map Creator"},
		{"map",             "Region"},
		{"newregion",       "New"},
		{"newmapname",      "My map"},
		{"newregionname",   "My region"},
		{"date",            "Creation date"},
		{"author",          "Author"},
		{"comments",        "Comments"},
		{"precision",       "Data precision"},
		{"singleprecision", "Single precision"},
		{"doubleprecision", "Double precision"},
		{"confirmsingle",   "Changing to single precision causes non-restorable loss of data precision.\nAre you sure you want to change it?"},
		{"confirmdouble",   "Changing to double precision increases the size of the map in the memory and in the disk.\nAre you sure you want to change it?"},
		{"projection",      "Projection"},
			{"none",            "None"},
		{"database",        "Database"},
		{"browse",          "Browse"},
		{"mustdefdatabase", "Database not defined."},
		{"newdb",           "New"},
		{"givedbname",      "Please provide a name for the new database:"},
		{"dbnotcreated",    "Cannot create the database!"},
		{"erasealltables",  "Defining a new datadase will cause the disconnection of the associated tables from all the layers!\nAre you sure you want to define a new database?"},
		{"dbnotcompatible", "The new database is not compatible with the old one, i.e. the tables associated with layers do not have the same properties (fields, field types etc)."},
		{"coordinates",     "Geographic coordinates of this region"},
		{"minlong",         "Bottom-Left lambda:"},
		{"minlat",          "Bottom-Left phi:"},
		{"maxlong",         "Top-Right lambda:"},
		{"maxlat",          "Top-Right phi:"},
		{"minlongcart",     "Bottom-Left X:"},
		{"minlatcart",      "Bottom-Left Y:"},
		{"maxlongcart",     "Top-Right X:"},
		{"maxlatcart",      "Top-Right Y:"},
		{"zoomrect",        "On the parent coordinate system: (Blank for the same)"},
		{"images",          "Background images"},
		{"add",             "Add"},
		{"cannotaddback",   "You have to save the map or the microworld to a file before adding background images to regions.\nPlease go back and save before trying again."},
		{"delete",          "Delete"},
		{"default",         "Set as default"},
		{"isdefault",       "This is the default background"},
		{"defaulttip",      "The default background is the background shown when no other applies"},
		{"properties",      "Properties"},
		{"propertiestip",   "Changes the description and the era of time that the selected background exists"},
		{"nodate",          "All time periods"},
		{"orientation",     "Orientation "},
		{"linked",          "Region layers same as in"},
		{"notlinked",       "--None, has its own--"},
		{"confirmlink",     "Do you want to change the region link?"},
		{"scale",           "Scale "},
		{"degrees",         " degrees"},
		{"oneover",         "1 / "},
		{"available",       "Available Layers"},
		{"clickonimage",    "Right-click on an image to preview"},
		{"addlayertip",     "Add layer to the region"},
		{"removelayertip",  "Delete layer from region"},
		{"layeruptip",      "Move layer up"},
		{"layerdowntip",    "Move layer down"},
		{"maplayers",       "Region Layers:"},
		{"newlayertip",     "New layer"},
		{"importlayer",     "Import layer"},
		{"importlayertip",  "Import layer from file"},
		{"inslayernotable", "You canceled the creation of the database\nwhich would host the layer table.\n\nDo you want to import the layer without the accompaning table?"},
		{"cannotloadfile",  "Cannot import layer.\n\nEither the file is corrupt\nor does not have the correct format."},
		{"nevermind",       "Nothing. That's OK for me."},
		{"replace",         "Replace the old one."},
		{"wait",            "Please wait..."},
		{"importregion",    "Import region"},
		{"importregioninfo","Importing region and its layers, if any exist. Database creation if needed..."},
		{"exportregion",    "Export region: "},
		{"exportlayrsaswell","Export associated layers as well?"},
		{"layernameexists", "Another layer with the same name exists.\nWhat do you want to do?"},
		{"exportlayer",     "Export layer: "},
		{"exportlayertip",  "Export layer to a file"},
		{"cannotcreatefile","Cannot export.\n\nEither the file already exists and cannot be replaced\nor it doesnot exist and cannot be created\nor for some unknown reason the system cannot write in the file\nor a folder name has been given."},
		{"previewlayertip", "Preview layer"},
		{"deletelayertip",  "Delete layer from the list"},
		{"deletelayers",    "Are you sure you want to delete the selected layers? They will be deleted from all the regions that use them!"},
		{"roadlayertip",    "Define as road layer"},
		{"railwaylayertip", "Define as railway layer"},
		{"sealayertip",     "Define as sea layer"},
		{"nothingtip",      "Remove"},
		{"newregiontip",    "Add a new region"},
		{"newregionroottip", "New region incumbent to all regions"},
		{"deleteregiontip", "Delete a region"},
		{"entryregiontip",  "Define region as the entry region"},
		{"entryregiontreetip","This is the entry region"},
		{"importregiontip", "Import a region from a file amenable to the active one"},
		{"importregionroottip","Import a region from a file, incumbent to all regions (new root)"},
		{"exportregiontip", "Export region to a file"},
		{"confirmdeleteregion","Do you realy want to delete this region and all its inner regions?"},
		{"checktip",        "Check the integrity of the map"},
		{"image",           "Image"},
		{"motion",          "This defines the selected layer as a motion layer"},
		{"motionlayer",     "This is a motion layer"},
		{"idtip",           "Either select from the predefned types, or give your own ID for the motion layer."},
		{"$$$__typeroad",   "ROADS"},
		{"$$$__typerailway","RAILWAYS"},
		{"$$$__typesea",    "SEA"},
		{"$$$__typeair",    "AIRLANES"},
		{"coordtype",       "Coordinates"},
		{"lambaphi",        "Terrestrial (lamba,phi)"},
		{"cartesian",       "Cartesian (x,y)"},
		{"units",           "Unit"},
		{"unknown",         "Unknown"},
		{"meters",          "Meters"},
		{"unitsPerMeter",   "Units/m"},
		//LayerInfo
		{"layer",           "My layer"},
		{"mustdefshapefile","Geographic data file or layer type must be defined."},
		{"shapefiledefined","Geographic data defined."},
		{"shapefile",       "Geographic data"},
		{"errorshapefile",  "Couldn't load the shapefile. Possible reasons:\n1) Incorrect file format or currupted file,\n2) Missing shapefile index file (.shx) (for .shp files only),\n3) Unsupported shape type."},
		{"objects",         "objects."},
		{"records",         "records"},
		{"1",               "(Point layer)"},
		{"3",               "(Line layer)"},
		{"5",               "(Polygon layer)"},
		{"2147483647",      "(Raster layer)"},
		{"newlayer",        "New user-defined layer."},
		{"newlayertype",    "Blank layer"},
		{"property",        "View information"},
		{"tabledata",       "Associated database table"},
		{"tooltip",         "Tooltip field"},
		{"label",           "Label field"},
		{"timefromto",      "Time being field (from-to)"},
		{"none",            "--None--"},
		{"newtable",        "New table"},
		{"newfield",        "Field"},
		{"givetablename",   "Please provide a name for the new table:"},
		{"tablenotcreated", "Cannot create the table!"},
		{"color",           "Color"},
		{"colors",          "Colors"},
		{"rastertransp",    "Raster view with transparency"},
		{"outline",         "Outline"},
		{"fill",            "Fill"},
		{"normal",          "Normal"},
		{"selected",        "Selected"},
		{"highlighted",     "Highlighted"},
		{"editable",        "Editable by the user"},
		{"visible",         "Visible on first showing"},
		{"shownotselected", "Show unselected objects"},
		{"selectobjects",   "Objects may be selected"},
		{"propagateobjsel", "Do you want the value of this property to pass to all existing views?"},
		{"enablevisible",   "Enable user change"},
		{"enableshownotselected","Enable user change"},
		{"showblankrecord", "Show objects with blank associated records in the table"},
		{"ok",              "Accept"},
		{"cancel",          "Cancel"},
		{"apply",           "Apply"},
		{"definename",      "You must specify the name of the layer!"},
		{"cannotbuildlayer","The layer cannot be built. Check the definition again."},
		{"tablenotdefined", "No data table defined. Please choose one or define a new one."},
		{"dbnotdefined",    "No data table defined.\nGo to the map definition (no need to close the layer window), define a database and retry."},
		{"transparency",    "Transparency"},
		{"rastercoordinates","Geographic coordinates of this raster"},
		//PointLayerProperties
		{"viewproperties",  "View properties"},
		{"pointview",       "View this layer points as:"},
		{"ascircle",        "A circle with radius of"},
		{"asicons",         "Icons (same for all points)"},
		{"filledcircle",    "Filled"},
		{"pixels",          "pixels."},
		{"define",          "Define"},
		{"asmultipleicons", "Multiple icons based on a property"},
		{"asmultipleiconsunbound","Multiple icons"},
		{"helpmultiple",    "For multiple icon view a database table must exist"},
		{"boundfield",      "Property field to select icon from:"},
		{"addline",         "Add line"},
		{"deleteline",      "Remove line"},
		{"value",           "Value"},
		{"close",           "Close"},
		{"clearicon",       "Clear"},
		//PolyLineLayerProperties
		{"lineview",        "View this layer lines as:"},
		{"straight",        "a straight line"},
		{"dashed",          "a dashed line"},
		{"dotted",          "a dotted line"},
		{"width",           "which is"},
		{"linepixels",      "pixel(s) wide."},
		{"antialiasdefault","Antialiasing as in the viewer"},
		{"antialiason",     "Antialiasing ON"},
		{"antialiasoff",    "Antialiasing OFF"},
		{"errorTolerance",  "Drawing error tolerance"},
		{"errorTolerance2", "(Use negative value for viewer default)"},
		//PolygonLayerProperties
		{"polygonview",     "View this layer polygon outlines as:"},
		{"filledpolygon",   "Filled polygons"},
		//Errors, warnings
		{"integritycheck",  "Map integrity check"},
		{"checking",        "Checking E-Slate Map file (.esm)..."},
		{"version",         "Version 3.0.19991113"},
		{"closeandexit",    "Accept map and close"},
		{"returntocreator", "Return to map definition"},
		{"viewerrors",      "Show error log"},
		{"errorsencountered","Errors detected in the map definition. Please choose one of the following:"},
		{"warningsencountered","Posible problems (warnings) in the map definition. Please choose one of the following:"},
		{"errors",          "***ERRORS DETECTED IN THE MAP DEFINITION!***"},
		{"warnings",        "***Possible problems in the map definition! Shown as warnings.***"},
		{"noerrors",        "***No errors detected in the map definition!***"},
		{"errnoentryregion","No entry region defined in"},
		{"errminlong",      "Undefined bottom-left corner longitude in region"},
		{"errminlat",       "Undefined bottom-left corner latitude in region"},
		{"errmaxlong",      "Undefined top-right corner longitude in region"},
		{"errmaxlat",       "Undefined top-right corner latitude in region"},
		{"errnoregions",    "There are no regions defined."},
		{"errnoshapefile",  "No geographic data file defined in layer"},
		{"errdiffdb",       "Unknown database table in layer"},
		{"warnnodatabase",  "WARNING: No database file defined in"},
		{"warnnotable",     "WARNING: No database table associated with layer"},
		{"warnnoimages",    "WARNING: No background images defined in region"},
		{"warnnolayers",    "WARNING: No layers defined."},
		{"warnnolayersinregion","WARNING: No layers defined in region"},
		//Time era selector
		{"timeera",         "Existence of background in time"},
		{"alleras",         "In all time periods."},
		{"specific",        "In a specific time period:"},
		{"from",            "From"},
		{"to",              "To"},
		{"ok",              "Accept"},
		{"cancel",          "Cancel"},
		{"dateformat",      "Date Format (by example)"},
		{"dateformattip",   "Define how you will enter the dates"},
		{"errordate",       "One of the dates is not in the date format you specified."},
		{"errordatesbeforeafter","\"To\" date is earlier than \"From\" date!"},
		{"backname",        "What is the description of this background?"},
		{"nobackname",      "A background must have a description. Please, repeat your actions."},
		{"backgrounddescr", "Description:"},
	};
}
