package gr.cti.eslate.editor;

import java.util.*;

import org.netbeans.editor.*;

/**
 * Greek language localized strings for the editor panel.
 *
 * @author      Kriton Kyrimis
 * @version     2.0.0, 24-May-2006
 */
public class EditorResource_el extends ListResourceBundle
  implements LocaleSupport.Localizer
{
  public Object[][] getContents()
  {
    return contents;
  }

  static final Object[][] contents = {
    {"file", "Αρχείο"},
    {"new", "Νέο..."},
    {"open", "’νοιγμα αρχείου..."},
    {"close", "Κλείσιμο"},
    {"save", "Αποθήκευση"},
    {"saveAs", "Αποθήκευση ως..."},
    {"saveAll", "Αποθήκευση Όλων"},
    {"print", "Εκτύπωση..."},
    {"exit", "Έξοδος"},
    {"newTip", "Νέο αρχείο"},
    {"openTip", "’νοιγμα αρχείου"},
    {"closeTip", "Κλείσιμο αρχείου"},
    {"saveTip", "Αποθήκευση αρχείου"},
    {"saveAllTip", "Αποθήκευση όλων των αρχείων"},
    {"printTip", "Εκτύπωση κειμένου"},
    {"copyTip", "Αντιγραφή κειμένου"},
    {"pasteTip", "Επικόλληση κειμένου"},
    {"cutTip", "Αποκοπή κειμένου"},
    {"undoTip", "Ακύρωση"},
    {"redoTip", "Επανάληψη"},
    {"findTip", "Εύρεση"},
    {"findNextTip", "Εύρεση επομένου"},
    {"replaceTip", "Αντικατάσταση"},
    {"fileExists1", "Το αρχείο "},
    {"fileExists2", " υπάρχει ήδη. Να αντικατασταθεί?"},
    {"fileExists3", "Το αρχείο υπάρχει"},
    {"cantWrite1", "Δεν είναι δυνατόν να γραφεί το αρχείο '"},
    {"cantWrite2", "'."},
    {"error", "Σφάλμα"},
    {"cantRead1", "Δεν είναι δυνατόν να διαβαστεί το αρχείο '"},
    {"cantRead2", "'."},
    {"fileModified1", "Το αρχείο "},
    {"fileModified2", " έχει τροποποιηθεί. Να αποθηκευτεί?"},
    {"fileModified3", "Το αρχείο έχει τροποποιηθεί"},
    {"discard", "Απόρριψη"},
    {"yes", "Ναι"},
    {"no", "Όχι"},
    {"cancel", "’κυρο"},
    {"noTemplate", "Δεν πορεί να διαβαστεί το υπόδειγμα"},
    {"eSlateEd", "Συντάκτης Κειμένου"},
    {"noFile", "[κανένα αρχείο]"},
    {"ok", "Εντάξει"},
    {"allRecognized", "Όλα τα αναγνωριζόμενα αρχεία"},
    {"edit", "Επεξεργασία"},
    {"undo", "Ακύρωση"},
    {"redo", "Επανάληψη"},
    {"cut", "Αποκοπή"},
    {"copy", "Αντιγραφή"},
    {"paste", "Επικόλληση"},
    {"delete", "Διαγραφή"},
    {"selectAll", "Επιλογή όλων"},
    {"search", "Αναζήτηση"},
    {"find", "Εύρεση..."},
    {"replace", "Αντικατάσταση..."},
    {"searchAgain", "Εύρεση Επομένου..."},
    {"gotoLine", "Εύρεση Γραμμής..."},
    {"fontSize", "Μέγεθος γραμμάτων"},
    {"options", "Επιλογές"},
    {"configuration", "Ρυθμίσεις..."},
    {"configTitle", "Ρυθμίσεις συντάκτη κειμένου"},
    {"noFileEdited", "Δεν είναι ανοικτό κανένα αρχείο"},
    {"noSuchLine", "Η γραμμή αυτή δεν υπάρχει"},

    {"plain", "Απλό κείμενο"},
    {"java", "Κώδικας Java"},

    {"line-number", "Αριθμοί γραμμής"},
    {"status-bar-bold", "Αναζήτηση απ' την αρχή"},
    {"inc-search", "Σταδιακή αναζήτηση"},
    {"highlight-match-brace", "Τονισμένη αντίστοιχη αγκύλη"},
    {"highlight-caret-row", "Τονισμένες γραμμές"},
    {"bookmark", "Σελιδοδείκτες"},
    {"default", "Βασική γραμματοσειρά"},
    {"status-bar", "Γραμμή κατάστασης"},
    {"selection", "Επιλεγμένο κείμενο"},
    {"guarded", "Προστατευμένες περιοχές"},
    {"highlight-search", "Τονισμός μετά από αναζήτηση"},

    {"java-layer-method", "Μέθοδοι Java"},
    {"java-string-literal", "Σταθερές (συμβολοσειρές)"},
    {"java-whitespace", "Κενά διαστήματα"},
    {"java-numeric-literals", "Σταθερές (αριθμοί)"},
    {"java-errors", "Σφάλματα"},
    {"java-identifier", "Μεταβλητές Java"},
    {"java-operators", "Τελεστές Java"},
    {"java-block-comment", "Ομαδικά σχόλια"},
    {"java-keywords", "Λέξεις-κλειδιά Java"},
    {"java-char-literal", "Σταθερες (χαρακτήρες)"},
    {"java-line-comment", "Σχόλια μιας γραμμής"},

    {"font", "Γραμματοσειρά"},
    {"sample", "Δείγμα"},
    {"abcd", "ABCDabcdΑΒΓΔαβγδ"},
    {"bold", "Έντονα"},
    {"italic", "Πλάγια"},
    {"fgColor", "Χρώμα"},
    {"bgColor", "Χρώμα υποβάθρου"},
    //
    // BeanInfo resources
    //
    {"menuBarVisible", "Μπάρα μενού ορατή"},
    {"menuBarVisibleTip", "Ορίστε αν θα είναι ορατή η μπάρα του μενού"},
    {"toolBarVisible", "Μπάρα εργαλείων ορατή"},
    {"toolBarVisibleTip", "Ορίστε αν θα είναι ορατή η μπάρα εργαλείων"},
    {"statusBarVisible", "Μπάρα κατάστασης ορατή"},
    {"statusBarVisibleTip", "Ορίστε αν θα είναι ορατή η μπάρα κατάστασης"},
    {"propertyChange", "Αλλαγή ιδιότητας"},
    {"mouseEntered", "Είσοδος ποντικού"},
    {"mouseExited", "Έξοδος ποντικού"},
    {"mouseMoved", "Μετακίνηση ποντικού"},
    {"vetoableChange", "Ακυρώσιμη αλλαγή ιδιότητας"},
    {"componentHidden", "Απόκρυψη ψηφίδας"},
    {"componentShown", "Εμφάνιση ψηφίδας"},
    {"multipleEditor", "Χειρισμός πολλαπλών αρχείων"},
    {"multipleEditorTip", "Ορίστε αν ο συντάκτης κειμένου μπορεί να χειριστεί πολλα αρχεία ταυτοχρόνως"},
    //
    // NetBeans resources
    //
    {"find-button-find", "Εύρεση"},
    {"find-button-replace", "Αντικατάσταση"},
    {"find-button-replace-all", "Αντικατάσταση όλων"},
    {"find-button-cancel", "’κυρο"},
    {"find-what", "Εύρεση:"},
    {"find-replace-with", "Αντικατάσταση με:"},
    {"find-title", "Αναζήτηση"},
    {"replace-title", "Αντικατάσταση"},
    {"find-found", "βρέθηκε στη γραμμή"},
    {"find-wrap-start", "Τέλος αρχείου. Επανάληψη εύρεσης από την αρχή."},
    {"find-not-found", "δεν βρέθηκε"},
    {"goto-button-goto", "Εύρεση"},
    {"goto-button-cancel", "’κυρο"},
    {"goto-line", "Εύρεση γραμμής:"},
    {"goto-title", "Εύρεση γραμμής"},
    {"popup-cut-to-clipboard", "Αποκοπή"},
    {"popup-copy-to-clipboard", "Αντιγραφή"},
    {"paste-from-clipboard", "Επικόλληση"},
    {"popup-remove-selection", "Διαγράφή"},
    {"status-bar-insert", "ΕΙΣ"},
    {"status-bar-overwrite", "ΣΒΗ"},
    {"find-what-mnemonic", ""},
    {"find-highlight-search-mnemonic", ""},
    {"find-inc-search-mnemonic", ""},
    {"find-match-case-mnemonic", ""},
    {"find-smart-case-mnemonic", ""},
    {"find-whole-words-mnemonic", ""},
    {"find-reg-exp-mnemonic", ""},
    {"find-backward-search-mnemonic", ""},
    {"find-wrap-search-mnemonic", ""},
    {"find-button-find-mnemonic", ""},
    {"find-button-replace-mnemonic", ""},
    {"find-button-replace-all-mnemonic", ""},
    {"find-items-replaced", "αντικαταστάθηκαν {0} από {1} αντικείμενα"},
    // These netbeans resources do not actually exist, and are faked.
    {"find-highlight-search", "Τονισμός ευρεθέντος κειμένου"},
    {"find-inc-search", "Σταδιακή αναζήτηση"},
    {"find-match-case", "Ταίριασμα πεζών/κεφαλαίων"},
    {"find-smart-case", "Έξυπνο ταίριασμα πεζών/κεφαλαίων"},
    {"find-whole-words", "Εύρεση ολόκληρων λέξεων"},
    {"find-backward-search", "Αναζήτηση προς τα πίσω"},
    {"find-wrap search", "Συνεχής αναζήτηση"},
  };
}
